"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { loadProfileLocations, type ProfileLocationOption } from "@/app/lib/account/profileLocations";

export function ProfileLocationFields({ country, region, city, disabled, onCountry, onRegion, onCity }: { country:string;region:string;city:string;disabled?:boolean;onCountry:(v:string)=>void;onRegion:(v:string)=>void;onCity:(v:string)=>void }) {
  const [countries,setCountries]=useState<ProfileLocationOption[]>([]),[regions,setRegions]=useState<{country:string;options:ProfileLocationOption[]}>({country:"",options:[]}),[cities,setCities]=useState<{country:string;region:string;options:ProfileLocationOption[]}>({country:"",region:"",options:[]});
  const [unavailable,setUnavailable]=useState(false);
  useEffect(()=>{let active=true;loadProfileLocations("countries").then(r=>{if(active){setCountries(r.options);setUnavailable(false);}}).catch(()=>active&&setUnavailable(true));return()=>{active=false;};},[]);
  useEffect(()=>{let active=true;if(country)loadProfileLocations("regions",country).then(r=>active&&setRegions({country,options:r.options})).catch(()=>active&&setUnavailable(true));return()=>{active=false;};},[country]);
  useEffect(()=>{let active=true;if(country&&region)loadProfileLocations("cities",country,region).then(r=>active&&setCities({country,region,options:r.options})).catch(()=>active&&setUnavailable(true));return()=>{active=false;};},[country,region]);
  const chooseRegion=async(next:string)=>{if(next===region)return;onRegion(next);if(!next||!city)return;try{const result=await loadProfileLocations("cities",country,next);if(result.options.length&&!result.options.some(option=>option.value.toLocaleLowerCase()===city.toLocaleLowerCase()))onCity("");}catch{/* Keep the readable saved city when compatibility cannot be established. */}};
  return <>
    <SearchableLocation label="COUNTRY" value={country} options={countries} disabled={disabled} allowManual pattern={/^[A-Z]{2}$/} manualTransform={v=>v.trim().toUpperCase()} empty="Country not listed? Enter its two-letter country code." onChange={next=>{if(next!==country)onCountry(next);}} />
    <SearchableLocation label="STATE / REGION" value={region} options={regions.country===country?regions.options:[]} disabled={disabled||!country} allowManual empty={country?"Not listed? Enter the state or region name.":"Choose a country first."} onChange={next=>{void chooseRegion(next);}} />
    <SearchableLocation label="CITY" value={city} options={cities.country===country&&cities.region===region?cities.options:[]} disabled={disabled||!country} allowManual empty={country?"Not listed? Enter the city name.":"Choose a country first."} onChange={onCity} />
    {unavailable?<p role="status" className="md:col-span-2 text-xs text-amber-700">Location suggestions are temporarily unavailable. Saved values remain visible; use the not-listed entry when needed.</p>:null}
  </>;
}

function SearchableLocation({label,value,options,onChange,disabled,allowManual=false,empty,pattern,manualTransform}: {label:string;value:string;options:ProfileLocationOption[];onChange:(v:string)=>void;disabled?:boolean;allowManual?:boolean;empty:string;pattern?:RegExp;manualTransform?:(v:string)=>string}) {
  const [open,setOpen]=useState(false),[query,setQuery]=useState(""); const trigger=useRef<HTMLButtonElement>(null), input=useRef<HTMLInputElement>(null);
  const optionId=`profile-${label.replace(/\W/g,"-")}-options`;
  const labelId=`${optionId}-label`;
  const selected=options.find(o=>o.value===value); const filtered=useMemo(()=>{const n=query.trim().toLowerCase();return n?options.filter(o=>`${o.label} ${o.value} ${o.detail??""}`.toLowerCase().includes(n)).slice(0,150):options.slice(0,150);},[options,query]);
  const manual=(manualTransform??((v:string)=>v.trim()))(query); const canManual=allowManual&&!!manual&&(!pattern||pattern.test(manual))&&!options.some(o=>o.value.toLowerCase()===manual.toLowerCase());
  useEffect(()=>{if(!open)return;input.current?.focus();const esc=(e:KeyboardEvent)=>{if(e.key==="Escape"){setOpen(false);trigger.current?.focus();}};document.addEventListener("keydown",esc);return()=>document.removeEventListener("keydown",esc);},[open]);
  const choose=(v:string)=>{onChange(v);setOpen(false);setQuery("");queueMicrotask(()=>trigger.current?.focus());};
  return <div><span id={labelId} className="mb-2 block text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</span><button ref={trigger} type="button" disabled={disabled} aria-labelledby={labelId} aria-haspopup="dialog" aria-expanded={open} aria-controls={optionId} onClick={()=>setOpen(true)} className="flex h-12 w-full items-center justify-between rounded-xl border border-gray-300 bg-white px-4 text-left text-sm font-medium text-slate-900 disabled:bg-slate-100 disabled:text-slate-500"><span>{(selected?.label ?? value) || "Select"}</span><span aria-hidden>⌄</span></button>
    {open?<div className="fixed inset-0 z-[90] flex items-end justify-center bg-slate-950/40 p-0 sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-label={label} onKeyDown={event=>{if(event.key!=="Tab")return;const nodes=[...event.currentTarget.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled])')];if(!nodes.length)return;const first=nodes[0]!,last=nodes[nodes.length-1]!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}} onMouseDown={e=>{if(e.target===e.currentTarget){setOpen(false);trigger.current?.focus();}}}><div className="flex max-h-[85vh] w-full max-w-xl flex-col rounded-t-2xl bg-white p-4 shadow-2xl sm:rounded-2xl"><div className="flex items-center justify-between"><h3 className="text-lg font-semibold text-slate-900">{label}</h3><button type="button" onClick={()=>{setOpen(false);trigger.current?.focus();}} aria-label={`Close ${label}`} className="h-11 w-11 rounded-xl">✕</button></div><input ref={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${label.toLowerCase()}`} aria-label={`Search ${label}`} className="mt-3 h-12 rounded-xl border border-slate-300 px-4 text-slate-900"/><div className="mt-2 overflow-y-auto" id={optionId}>{canManual?<button type="button" onClick={()=>choose(manual)} className="block min-h-12 w-full border-b px-3 py-3 text-left font-medium text-blue-700">Use “{manual}” <span className="text-xs text-slate-500">· Not listed</span></button>:null}{filtered.map(o=><button key={`${o.value}-${o.label}`} type="button" onClick={()=>choose(o.value)} className="flex min-h-12 w-full items-center justify-between border-b px-3 py-3 text-left hover:bg-blue-50"><span>{o.label}</span><span className="text-xs text-slate-500">{o.detail??(o.value!==o.label?o.value:"")}</span></button>)}{!filtered.length&&!canManual?<p className="p-4 text-sm text-slate-600">{empty}</p>:null}</div>{value?<button type="button" onClick={()=>choose("")} className="mt-3 min-h-11 rounded-xl border text-sm font-semibold text-slate-700">Clear selection</button>:null}</div></div>:null}
  </div>;
}
