"use client";

import { useMemo, useState } from "react";
import { Search } from "lucide-react";
import { useAuth } from "@/app/hooks/useAuth";
import { useRouter } from "next/navigation";
import { creatorCollectionConfigs } from "@/app/lib/creators/creatorCollectionPageConfig";
import CreatorMarketplaceHeader from "../CreatorMarketplaceHeader";
import CreatorMarketplaceFooter from "../CreatorMarketplaceFooter";
import CreatorCollectionCard from "./CreatorCollectionCard";
import typography from "../CreatorTypography.module.css";

const groups = ["Featured", "Popular", "Destination", "Seasonal", "Creator", "Business", "Trending"] as const;
export default function CreatorCollectionsPage() {
  const router = useRouter(); const { user, isAuthenticated, openLoginModal } = useAuth();
  const [query, setQuery] = useState(""); const [group, setGroup] = useState("All"); const [sort, setSort] = useState("featured");
  const collections = useMemo(() => creatorCollectionConfigs.filter((item) => (group === "All" || item.group === group) && (!query.trim() || [item.title, item.description, item.theme, ...item.popularTags].join(" ").toLowerCase().includes(query.toLowerCase()))).sort((a, b) => sort === "title" ? a.title.localeCompare(b.title) : sort === "assets" ? Number.parseFloat(b.assetCount) - Number.parseFloat(a.assetCount) : groups.indexOf(a.group) - groups.indexOf(b.group)), [group, query, sort]);
  const sections = group === "All" ? groups.map((name) => ({ name, items: collections.filter((item) => item.group === name) })).filter((section) => section.items.length) : [{ name: group, items: collections }];
  const studio = () => { if (isAuthenticated && user) router.push("/creator-studio"); else openLoginModal(); };
  return <div className={`${typography.scope} min-h-screen overflow-x-clip bg-slate-50 text-slate-950`}><CreatorMarketplaceHeader onStudio={studio} userName={user?.fullName ?? user?.email ?? "Account"} /><main><section className="bg-[#071831] px-4 py-10 text-white sm:px-6 lg:px-10"><div className="mx-auto max-w-[1360px]"><p className="text-[9px] font-black uppercase tracking-[0.18em] text-blue-300">Curated by TPL Creators</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Premium Collections</h1><p className="mt-2 max-w-2xl text-sm font-medium text-slate-300">Handpicked creative assets for destinations, campaigns, stories and modern content teams.</p><div className="mt-6 flex max-w-3xl overflow-hidden rounded-lg bg-white p-1"><Search className="ml-3 mt-3 h-4 w-4 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search collections..." className="h-10 min-w-0 flex-1 px-3 text-sm font-semibold text-slate-900 outline-none" /><button type="button" className="rounded-md bg-blue-600 px-5 text-[10px] font-black">Search</button></div></div></section><section className="mx-auto max-w-[1440px] px-4 py-8 sm:px-6 lg:px-10"><div className="flex flex-col gap-3 border-b border-slate-200 pb-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-2 overflow-x-auto">{["All", ...groups].map((item) => <button type="button" key={item} onClick={() => setGroup(item)} className={`shrink-0 rounded-full px-3 py-1.5 text-[10px] font-black ${group === item ? "bg-[#071831] text-white" : "border border-slate-200 bg-white text-slate-600"}`}>{item}</button>)}</div><select aria-label="Sort collections" value={sort} onChange={(event) => setSort(event.target.value)} className="h-9 rounded-md border border-slate-200 bg-white px-3 text-[10px] font-bold"><option value="featured">Featured first</option><option value="title">A–Z</option><option value="assets">Most assets</option></select></div>{collections.length ? sections.map((section) => <div key={section.name} className="pt-8"><div><h2 className="text-xl font-black">{section.name} Collections</h2><p className="mt-1 text-xs font-medium text-slate-500">{section.items.length} curated {section.items.length === 1 ? "collection" : "collections"}</p></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{section.items.map((item) => <CreatorCollectionCard key={item.slug} collection={item} />)}</div></div>) : <div className="mt-6 rounded-xl border border-dashed border-slate-300 bg-white py-16 text-center"><h2 className="text-lg font-black">No matching collections</h2><button onClick={() => { setQuery(""); setGroup("All"); }} type="button" className="mt-3 text-xs font-black text-blue-700">Clear filters</button></div>}</section></main><CreatorMarketplaceFooter onStudio={studio} /></div>;
}
