"use client";

import { useEffect, useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useAuth } from "@/app/hooks/useAuth";
import type { CreatorAsset, CreatorCategory } from "@/app/lib/creators/creatorCatalogTypes";
import type { CreatorCollectionConfig } from "@/app/lib/creators/creatorCollectionPageConfig";
import CreatorMarketplaceHeader from "../CreatorMarketplaceHeader"; import CreatorMarketplaceFooter from "../CreatorMarketplaceFooter";
import CreatorSearchFilters from "../search/CreatorSearchFilters"; import CreatorSearchToolbar from "../search/CreatorSearchToolbar"; import CreatorSearchResults from "../search/CreatorSearchResults"; import CreatorSearchPagination from "../search/CreatorSearchPagination"; import CreatorSearchBanner from "../search/CreatorSearchBanner";
import CreatorCollectionHero from "./CreatorCollectionHero"; import CreatorCollectionInfo from "./CreatorCollectionInfo";
import typography from "../CreatorTypography.module.css";
const pageSize = 6;
const mediaFor = (type: string) => ({ photo: "image", photos: "image", video: "video", videos: "video", reel: "template", reels: "template", drone: "video", template: "template", presets: "template", graphics: "document", guides: "document" }[type] ?? type);
const durationSeconds = (duration?: string) => { if (!duration) return 0; const parts = duration.split(":").map(Number); return parts.reduce((total, value) => total * 60 + value, 0); };
export default function CreatorCollectionDetail({ config, assets, categories }: { config: CreatorCollectionConfig; assets: CreatorAsset[]; categories: CreatorCategory[] }) {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const { user, isAuthenticated, openLoginModal } = useAuth(); const [studioRequested, setStudioRequested] = useState(false); const [view, setView] = useState<"grid" | "list">("grid"); const [saved, setSaved] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { if (studioRequested && isAuthenticated && user) router.push("/creator-studio"); }, [isAuthenticated, router, studioRequested, user]);
  const update = (patch: Record<string, string | null>, resetPage = true) => { const next = new URLSearchParams(params.toString()); for (const [key, value] of Object.entries(patch)) { if (value) next.set(key, value); else next.delete(key); } if (resetPage && !("page" in patch)) next.delete("page"); router.push(`${pathname}?${next.toString()}`, { scroll: false }); };
  const clear = () => router.push(pathname, { scroll: false }); const studio = () => { if (isAuthenticated && user) router.push("/creator-studio"); else { setStudioRequested(true); openLoginModal(); } };
  const collectionAssets = useMemo(() => { const featured = config.featuredAssets.map((slug) => assets.find((asset) => asset.slug === slug)).filter((asset): asset is CreatorAsset => Boolean(asset)); const terms = [config.slug, config.title, config.theme, ...config.popularTags].join(" ").toLowerCase().split(/\W+/).filter((item) => item.length > 3); const ranked = assets.filter((asset) => !config.featuredAssets.includes(asset.slug)).map((asset) => { const searchable = [asset.category, asset.subcategory, asset.creatorName, ...asset.tags].join(" ").toLowerCase(); const membership = asset.collectionSlugs.includes(config.slug) ? 10_000 : 0; return { asset, score: membership + terms.filter((term) => searchable.includes(term)).length * 100 + asset.rating }; }).sort((a, b) => b.score - a.score).map((item) => item.asset); return [...featured, ...ranked]; }, [assets, config]);
  const filtered = useMemo(() => { const q = (params.get("q") ?? "").toLowerCase(); const type = mediaFor(params.get("type") ?? ""); const orientation = params.get("orientation") ?? ""; const resolution = (params.get("resolution") ?? "").toLowerCase(); const duration = params.get("duration") ?? ""; const license = params.get("license") ?? ""; const price = params.get("price") ?? ""; const category = params.get("category") ?? ""; const color = params.get("color") ?? ""; const location = (params.get("location") ?? "").toLowerCase(); const values = collectionAssets.filter((asset) => { const text = [asset.title, asset.subtitle, asset.description, asset.creatorName, asset.creatorRole, asset.category, asset.subcategory, ...asset.tags].join(" ").toLowerCase(); if (q && !text.includes(q)) return false; if (type && asset.mediaType !== type) return false; if (orientation && asset.orientation !== orientation) return false; if (resolution && !(asset.resolution ?? "").toLowerCase().includes(resolution)) return false; if (duration === "short" && (!asset.duration || durationSeconds(asset.duration) > 60)) return false; if (duration === "long" && (!asset.duration || durationSeconds(asset.duration) <= 60)) return false; if (license && !asset.licenses.includes(license as never)) return false; if (price === "under-499" && asset.price > 499) return false; if (price === "under-999" && asset.price > 999) return false; if (category && asset.category !== category) return false; if (color && !text.includes(color)) return false; if (location && !text.includes(location)) return false; return true; }); const sort = params.get("sort") ?? "popular"; return [...values].sort((a, b) => sort === "newest" ? b.updatedAt.localeCompare(a.updatedAt) : sort === "top-rated" ? b.rating - a.rating : sort === "price-low" ? a.price - b.price : sort === "price-high" ? b.price - a.price : sort === "trending" ? b.rating * b.reviewCount - a.rating * a.reviewCount : b.reviewCount - a.reviewCount); }, [collectionAssets, params]);
  const page = Math.max(Number(params.get("page") ?? "1"), 1); const pageCount = Math.max(Math.ceil(filtered.length / pageSize), 1); const currentPage = Math.min(page, pageCount); const visible = filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize); const activeFilters = [...params.entries()].filter(([key, value]) => value && !["q", "sort", "page"].includes(key));
  const save = () => { if (!isAuthenticated || !user) openLoginModal(); else { setSaved((value) => !value); setNotice(saved ? "Collection removed from saved preview" : "Collection saved for this preview"); } };
  const share = async () => { try { if (navigator.share) await navigator.share({ title: config.title, url: window.location.href }); else { await navigator.clipboard.writeText(window.location.href); setNotice("Collection link copied"); } } catch { setNotice("Sharing cancelled"); } };
  return <div className={`${typography.scope} min-h-screen overflow-x-clip bg-slate-50 text-slate-950`}><CreatorMarketplaceHeader onStudio={studio} userName={user?.fullName ?? user?.email ?? "Account"} /><main><CreatorCollectionHero config={config} query={params.get("q") ?? ""} saved={saved} notice={notice} onSearch={(q) => update({ q: q || null })} onTag={(tag) => update({ q: tag })} onSave={save} onShare={share} /><div className="mx-auto grid max-w-[1440px] gap-6 px-4 py-8 sm:px-6 lg:grid-cols-[240px_minmax(0,1fr)] lg:px-10"><CreatorSearchFilters categories={categories} params={params} onUpdate={update} onClear={clear} /><section className="min-w-0"><CreatorSearchToolbar query={config.title} count={filtered.length} activeFilters={activeFilters} sort={params.get("sort") ?? "popular"} view={view} onRemove={(key) => update({ [key]: null })} onClear={clear} onSort={(sort) => update({ sort: sort === "popular" ? null : sort }, false)} onView={setView} /><CreatorSearchResults assets={visible} view={view} onClear={clear} onPopular={(tag) => update({ q: tag })} /><CreatorSearchPagination page={currentPage} pageCount={pageCount} onPage={(value) => update({ page: String(value) }, false)} /></section></div><CreatorCollectionInfo config={config} /><CreatorSearchBanner /></main><CreatorMarketplaceFooter onStudio={studio} /></div>;
}
