"use client";

import { forwardRef } from "react";
import Link from "next/link";
import Image from "next/image";
import { BadgeCheck, Clock3, Heart, Play, Star } from "lucide-react";
import type { MarketplaceDiscoveryFilter, MarketplaceHomeAsset } from "@/app/lib/creators/creatorMarketplaceHomeTypes";

type Props = { assets: MarketplaceHomeAsset[]; discovery: MarketplaceDiscoveryFilter; discoveryFilters: Array<{ id: MarketplaceDiscoveryFilter; label: string }>; sort: string; wishlist: Set<string>; onDiscoveryChange: (value: MarketplaceDiscoveryFilter) => void; onSortChange: (value: string) => void; onWishlist: (slug: string) => void; onClear: () => void };

const labelFor = (asset: MarketplaceHomeAsset) => asset.assetType === "template" && asset.tags.includes("reels") ? "Reel" : asset.assetType === "photo" && asset.tags.includes("wildlife") ? "Wildlife" : asset.assetType;

const CreatorTrendingAssets = forwardRef<HTMLElement, Props>(function CreatorTrendingAssets({ assets, discovery, discoveryFilters, sort, wishlist, onDiscoveryChange, onSortChange, onWishlist, onClear }, ref) {
  return <section ref={ref} id="trending-assets" className="scroll-mt-24 py-10 sm:py-12"><div className="mx-auto max-w-[1440px] px-4 sm:px-6 lg:px-10">
    <div className="flex items-end justify-between gap-4"><div><h2 className="text-2xl font-black tracking-tight">Trending Assets</h2><p className="mt-1 text-sm font-medium text-slate-500">Fresh picks from top creators around the world</p></div><Link href="/creators/search" className="hidden text-xs font-black text-blue-700 hover:text-blue-900 sm:block">View all assets →</Link></div>
    <div className="mt-5 flex gap-2 overflow-x-auto pb-1">{discoveryFilters.map((filter) => <button type="button" key={filter.id} onClick={() => onDiscoveryChange(filter.id)} className={`shrink-0 rounded-full border px-3 py-1.5 text-[11px] font-bold ${filter.id === discovery ? "border-[#071831] bg-[#071831] text-white" : "border-slate-200 bg-white text-slate-600 hover:border-slate-400"}`}>{filter.label}</button>)}<select aria-label="Sort assets" value={sort} onChange={(event) => onSortChange(event.target.value)} className="ml-auto shrink-0 rounded-full border border-slate-200 bg-white px-3 text-[11px] font-bold"><option value="popular">Popular</option><option value="newest">Newest</option><option value="rating">Best rated</option><option value="price-low">Price: low</option><option value="price-high">Price: high</option></select></div>
    {assets.length ? <div className="mt-6 grid grid-cols-1 gap-4 min-[480px]:grid-cols-2 md:grid-cols-3 xl:grid-cols-6">{assets.slice(0, 12).map((asset) => <article key={asset.id} className="group min-w-0 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl">
      <div className="relative aspect-[4/3] overflow-hidden bg-slate-100"><Image src={asset.previewImage} alt={asset.title} fill loading="eager" sizes="(min-width:1280px) 16vw, (min-width:768px) 33vw, 50vw" className="object-cover transition duration-500 group-hover:scale-105" /><span className="absolute left-2.5 top-2.5 rounded bg-[#071831]/85 px-2 py-1 text-[9px] font-black uppercase tracking-wide text-white">{labelFor(asset)}</span><button type="button" onClick={() => onWishlist(asset.slug)} aria-label={`${wishlist.has(asset.slug) ? "Remove" : "Add"} ${asset.title} ${wishlist.has(asset.slug) ? "from" : "to"} wishlist`} className={`absolute right-2.5 top-2.5 grid h-7 w-7 place-items-center rounded-full shadow ${wishlist.has(asset.slug) ? "bg-rose-600 text-white" : "bg-white text-slate-700"}`}><Heart className={`h-3.5 w-3.5 ${wishlist.has(asset.slug) ? "fill-current" : ""}`} /></button>{asset.duration && <span className="absolute bottom-2.5 right-2.5 inline-flex items-center gap-1 rounded bg-black/70 px-1.5 py-1 text-[9px] font-bold text-white">{asset.assetType === "video" || asset.assetType === "drone" ? <Play className="h-2.5 w-2.5 fill-current" /> : <Clock3 className="h-2.5 w-2.5" />}{asset.duration}</span>}<Link href={`/creators/assets/${asset.slug}`} aria-label={`View ${asset.title}`} className="absolute inset-0" /></div>
      <div className="p-3"><Link href={`/creators/assets/${asset.slug}`} className="line-clamp-2 min-h-9 text-xs font-black leading-[18px] hover:text-blue-700">{asset.title}</Link><div className="mt-2 flex items-center gap-1.5"><Image src={asset.creatorAvatar} alt="" width={20} height={20} className="h-5 w-5 rounded-full object-cover" /><Link href={`/creators/authors/${asset.creatorSlug}`} className="min-w-0 truncate text-[10px] font-bold text-slate-500 hover:text-blue-700">{asset.creator}</Link><BadgeCheck className="h-3 w-3 shrink-0 text-blue-600" /></div><div className="mt-2 flex items-center gap-1 text-[10px] font-bold text-slate-500"><Star className="h-3 w-3 fill-amber-400 text-amber-400" /><span className="text-slate-800">{asset.rating}</span><span>({asset.reviewCount})</span></div><div className="mt-3 border-t border-slate-100 pt-2.5"><p className="text-[11px] font-black text-blue-700">Included with Creator Plan</p><p className="mt-1 text-[10px] font-semibold text-slate-500">License from ₹{asset.price.toLocaleString("en-IN")}</p></div></div>
    </article>)}</div> : <div className="mt-6 rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-6 py-14 text-center"><p className="text-sm font-black">No assets match these filters.</p><button type="button" onClick={onClear} className="mt-3 text-xs font-black text-blue-700">Clear all filters</button></div>}
  </div></section>;
});

export default CreatorTrendingAssets;
