"use client";
import Link from "next/link";
import {useState,useEffect,useRef} from "react";
import {getAdminApiBaseUrl,readAdminSession} from "@/app/lib/admin/adminApiClient";
import {usePartnerPublishedRead} from "../../_components/usePartnerPublishedRead";
import {validWorkspace,type PartnerWorkspace} from "@/app/lib/partner/partnerWorkspace";
import PartnerHomeView from "@/app/components/partner/PartnerHomeView";
const permissions=["partner_verification.read"];
export default function PartnerDetail({organizationId}:{organizationId:string}){const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);const path="/api/v1/admin/partners/workspaces/"+encodeURIComponent(organizationId);const {data,state,retry}=usePartnerPublishedRead<PartnerWorkspace>(path,permissions,validWorkspace);const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
 async function download(format:string){const session=readAdminSession();if(!session)return;setBusy(true);try{const response=await fetch(getAdminApiBaseUrl()+path+"/export?format="+format,{headers:{Authorization:`Bearer ${session.session.token}`},cache:"no-store"});if(!response.ok)throw Error();const blob=await response.blob();if(!mounted.current||readAdminSession()?.session.token!==session.session.token)throw Error();const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="partner-workspace."+format;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setNotice("The export could not be prepared. Refresh and try again.");}finally{setBusy(false);}}
 return <div className="space-y-5"><div className="flex flex-wrap gap-3 text-sm text-slate-200 print:hidden"><Link href="/admin/partners/organizations">All Partners</Link><button onClick={retry}>Refresh</button>{data?["pdf","xlsx","csv"].map(f=><button disabled={busy} key={f} onClick={()=>void download(f)}>{f.toUpperCase()}</button>):null}{data?<button onClick={()=>window.print()}>Print</button>:null}</div>{notice?<p role="alert">{notice}</p>:null}{state==="forbidden"?<p role="alert">You do not have access to this Partner.</p>:state==="error"?<p role="alert">Partner details could not be refreshed.</p>:data?<><PartnerHomeView data={data} admin/><nav className="flex flex-wrap gap-4 text-sm text-sky-300 print:hidden"><Link href="/admin/partners/documents-compliance">Document reviews</Link><Link href="/admin/partners/agreements">Agreement reviews</Link><Link href="/admin/partners/payout-tax">Payout and tax reviews</Link></nav></>:<p role="status">Loading Partner…</p>}</div>;
}
