import type { FlightTrackingResult } from "./flightTrackingTypes";

export const flightTrackingDummyResults: FlightTrackingResult[] = [
  {
    airline: "IndiGo",
    flightNumber: "6E 204",
    from: "Delhi",
    to: "Mumbai",
    date: "Today",
    departureTime: "10:45 AM",
    arrivalTime: "12:55 PM",
    terminal: "T2",
    gate: "A12",
    status: "On Time",
    aircraft: "Airbus A320",
  },
  {
    airline: "Air India",
    flightNumber: "AI 865",
    from: "Delhi",
    to: "Bengaluru",
    date: "Today",
    departureTime: "02:20 PM",
    arrivalTime: "05:05 PM",
    terminal: "T3",
    gate: "B08",
    status: "Delayed",
    delayMinutes: 35,
    aircraft: "Airbus A321",
  },
  {
    airline: "Vistara",
    flightNumber: "UK 981",
    from: "Mumbai",
    to: "Delhi",
    date: "Today",
    departureTime: "06:30 PM",
    arrivalTime: "08:40 PM",
    terminal: "T2",
    gate: "C04",
    status: "Boarding",
    aircraft: "Boeing 737",
  },
];