export type InsurancePlan = {
  id: string;
  provider: string;
  logoText: string;
  planName: string;
  insuranceType: string;
  destinationType: "Domestic" | "International" | "Schengen" | "Student" | "Senior";
  coverageAmount: number;
  premium: number;
  claimSettlementRatio: number;
  medicalCovered: boolean;
  adventureSportsCovered: boolean;
  cashlessHospitals: boolean;
  covidCover: boolean;
  visaCompliant: boolean;
  schengenCompliant: boolean;
  seniorFriendly: boolean;
  studentFriendly: boolean;
  familyFriendly: boolean;
  features: string[];
  exclusions: string[];
  helpline: string;
};

export const insurancePlans: InsurancePlan[] = [
  {
    id: "TPL-INS-001",
    provider: "Tata AIG",
    logoText: "TA",
    planName: "Travel Guard Plus",
    insuranceType: "International Travel",
    destinationType: "International",
    coverageAmount: 50000,
    premium: 899,
    claimSettlementRatio: 96,
    medicalCovered: true,
    adventureSportsCovered: false,
    cashlessHospitals: true,
    covidCover: true,
    visaCompliant: true,
    schengenCompliant: false,
    seniorFriendly: true,
    studentFriendly: false,
    familyFriendly: true,
    features: [
      "Emergency medical cover",
      "Trip delay cover",
      "Baggage loss cover",
      "Cashless hospital network",
    ],
    exclusions: [
      "Pre-existing disease unless declared",
      "Adventure sports not included",
    ],
    helpline: "1800-266-7780",
  },
  {
    id: "TPL-INS-002",
    provider: "ICICI Lombard",
    logoText: "IL",
    planName: "Globe Safe Premium",
    insuranceType: "International Travel",
    destinationType: "International",
    coverageAmount: 100000,
    premium: 1299,
    claimSettlementRatio: 95,
    medicalCovered: true,
    adventureSportsCovered: true,
    cashlessHospitals: true,
    covidCover: true,
    visaCompliant: true,
    schengenCompliant: false,
    seniorFriendly: true,
    studentFriendly: false,
    familyFriendly: true,
    features: [
      "High medical coverage",
      "Adventure sports add-on",
      "Passport loss cover",
      "Trip cancellation cover",
    ],
    exclusions: [
      "Undeclared illness",
      "War and civil unrest",
    ],
    helpline: "1800-2666",
  },
  {
    id: "TPL-INS-003",
    provider: "Care Health",
    logoText: "CH",
    planName: "Schengen Secure",
    insuranceType: "Visa Insurance",
    destinationType: "Schengen",
    coverageAmount: 30000,
    premium: 749,
    claimSettlementRatio: 94,
    medicalCovered: true,
    adventureSportsCovered: false,
    cashlessHospitals: true,
    covidCover: true,
    visaCompliant: true,
    schengenCompliant: true,
    seniorFriendly: true,
    studentFriendly: false,
    familyFriendly: true,
    features: [
      "Schengen compliant cover",
      "Emergency medical cover",
      "Repatriation cover",
      "Visa-friendly policy document",
    ],
    exclusions: [
      "Adventure sports",
      "Non-declared medical condition",
    ],
    helpline: "1800-102-4488",
  },
  {
    id: "TPL-INS-004",
    provider: "Niva Bupa",
    logoText: "NB",
    planName: "Senior Travel Shield",
    insuranceType: "Senior Citizen",
    destinationType: "Senior",
    coverageAmount: 50000,
    premium: 1599,
    claimSettlementRatio: 97,
    medicalCovered: true,
    adventureSportsCovered: false,
    cashlessHospitals: true,
    covidCover: true,
    visaCompliant: true,
    schengenCompliant: false,
    seniorFriendly: true,
    studentFriendly: false,
    familyFriendly: false,
    features: [
      "Senior citizen friendly",
      "Emergency hospitalization",
      "Medical evacuation",
      "24x7 emergency support",
    ],
    exclusions: [
      "High-risk adventure activity",
      "Undeclared illness",
    ],
    helpline: "1860-500-8888",
  },
  {
    id: "TPL-INS-005",
    provider: "Aditya Birla Health",
    logoText: "AB",
    planName: "Student Global Protect",
    insuranceType: "Student Travel",
    destinationType: "Student",
    coverageAmount: 100000,
    premium: 2199,
    claimSettlementRatio: 93,
    medicalCovered: true,
    adventureSportsCovered: true,
    cashlessHospitals: true,
    covidCover: true,
    visaCompliant: true,
    schengenCompliant: false,
    seniorFriendly: false,
    studentFriendly: true,
    familyFriendly: false,
    features: [
      "Student medical cover",
      "Sponsor protection",
      "Study interruption cover",
      "Laptop/gadget cover option",
    ],
    exclusions: [
      "Non-academic travel extension",
      "Undeclared medical condition",
    ],
    helpline: "1800-270-7000",
  },
  {
    id: "TPL-INS-006",
    provider: "Reliance General",
    logoText: "RG",
    planName: "Domestic Trip Care",
    insuranceType: "Domestic Travel",
    destinationType: "Domestic",
    coverageAmount: 1000000,
    premium: 299,
    claimSettlementRatio: 92,
    medicalCovered: true,
    adventureSportsCovered: false,
    cashlessHospitals: true,
    covidCover: true,
    visaCompliant: false,
    schengenCompliant: false,
    seniorFriendly: true,
    studentFriendly: true,
    familyFriendly: true,
    features: [
      "Domestic medical cover",
      "Trip delay assistance",
      "Accidental cover",
      "Emergency support",
    ],
    exclusions: [
      "International travel",
      "Adventure sports",
    ],
    helpline: "1800-3009",
  },
  {
    id: "TPL-INS-007",
    provider: "Bajaj Allianz",
    logoText: "BA",
    planName: "Family Travel Prime",
    insuranceType: "Family Trip",
    destinationType: "International",
    coverageAmount: 75000,
    premium: 1899,
    claimSettlementRatio: 96,
    medicalCovered: true,
    adventureSportsCovered: true,
    cashlessHospitals: true,
    covidCover: true,
    visaCompliant: true,
    schengenCompliant: false,
    seniorFriendly: true,
    studentFriendly: true,
    familyFriendly: true,
    features: [
      "Family floater cover",
      "Medical emergency cover",
      "Baggage delay cover",
      "Adventure activity add-on",
    ],
    exclusions: [
      "Undeclared illness",
      "Extreme sports",
    ],
    helpline: "1800-209-5858",
  },
  {
    id: "TPL-INS-008",
    provider: "TrawellTag",
    logoText: "TT",
    planName: "Visa Assist Secure",
    insuranceType: "Visa Insurance",
    destinationType: "Schengen",
    coverageAmount: 50000,
    premium: 999,
    claimSettlementRatio: 94,
    medicalCovered: true,
    adventureSportsCovered: false,
    cashlessHospitals: true,
    covidCover: true,
    visaCompliant: true,
    schengenCompliant: true,
    seniorFriendly: true,
    studentFriendly: true,
    familyFriendly: true,
    features: [
      "Visa compliant certificate",
      "Schengen-ready coverage",
      "Emergency medical support",
      "Fast policy issuance",
    ],
    exclusions: [
      "Adventure sports",
      "Undeclared health condition",
    ],
    helpline: "1800-123-456",
  },
];