"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle,CheckCircle2,CreditCard,LockKeyhole,ShieldCheck } from "lucide-react";
import { useAuth } from "@/app/hooks/useAuth";
import { creatorCommerceFlags } from "@/app/lib/creators/creatorCommerceFlags";
import type { CreatorCommerceCheckoutDTO,CreatorCommerceOrderDTO,CreatorCommerceSelection } from "@/app/lib/creators/creatorCommerceTypes";
import { confirmCreatorTestingPayment,createCreatorTestingCheckout,readCreatorCommerceSelection,readStoredCreatorCheckout,readStoredCreatorOrder,startCreatorTestingPayment } from "@/app/lib/creators/creatorCommerceCheckoutAdapter";
import CreatorMarketplaceHeader from "../CreatorMarketplaceHeader";
import CreatorMarketplaceFooter from "../CreatorMarketplaceFooter";
import typography from "../CreatorTypography.module.css";

const money=(minor:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(minor/100);
export default function CreatorCheckoutFlow({stage}:{stage:"review"|"payment"|"confirmation"}){const router=useRouter();const {user,isAuthenticated,openLoginModal}=useAuth();const [selection,setSelection]=useState<CreatorCommerceSelection|null>(null);const [checkout,setCheckout]=useState<CreatorCommerceCheckoutDTO|null>(null);const [order,setOrder]=useState<CreatorCommerceOrderDTO|null>(null);const [terms,setTerms]=useState(false);const [method,setMethod]=useState("upi");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{const timer=window.setTimeout(()=>{setSelection(readCreatorCommerceSelection());setCheckout(readStoredCreatorCheckout());setOrder(readStoredCreatorOrder());},0);return()=>window.clearTimeout(timer);},[]);
  const studio=()=>isAuthenticated&&user?router.push("/creator-studio"):openLoginModal();
  const create=async()=>{if(!isAuthenticated||!user)return openLoginModal({redirectAfterLogin:"/creators/checkout/review"});if(!selection)return setNotice("Your testing checkout selection is missing. Return to Plans or an asset page.");setBusy(true);const result=await createCreatorTestingCheckout(selection,user.id);setBusy(false);if(!result.ok)return setNotice(result.error.message);setCheckout(result.data);router.push("/creators/checkout/payment");};
  const pay=async(outcome:"success"|"failure")=>{if(!checkout)return setNotice("Testing checkout was not found. Return to checkout review.");setBusy(true);const started=await startCreatorTestingPayment(checkout.checkoutId);if(!started.ok){setBusy(false);return setNotice(started.error.message);}const result=await confirmCreatorTestingPayment(checkout.checkoutId,outcome);setBusy(false);if(!result.ok)return setNotice(result.error.message);setOrder(result.data);if(outcome==="failure")setNotice("Test payment failed safely. No funds were charged. You can retry with the same checkout.");else router.push("/creators/checkout/confirmation");};
  const commerceOn=creatorCommerceFlags.commerceEnabled()&&creatorCommerceFlags.testCommerceEnabled();const missing=stage==="review"?!selection:stage==="payment"?!checkout:!order;
  return <div className={`${typography.scope} min-h-screen overflow-x-clip bg-slate-50 text-slate-950`}><CreatorMarketplaceHeader onStudio={studio} userName={user?.fullName??user?.email??"Account"}/><main className="mx-auto max-w-[1120px] px-4 py-10 sm:px-6 lg:px-10"><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-950"><strong className="block">Testing commerce only</strong>No real payment, subscription, license, entitlement, certificate or download is created.</div>{!commerceOn&&<State title="Creator testing commerce is disabled" copy="The marketplace preview remains available. Enable the B20 testing flags to certify checkout."/>}{commerceOn&&missing&&<State title="Checkout information is unavailable" copy="Return to Plans or an asset detail page and begin a new testing checkout."/>}{commerceOn&&!missing&&stage==="review"&&selection&&<Review selection={selection} checkout={checkout} terms={terms} setTerms={setTerms} busy={busy} onContinue={create}/>} {commerceOn&&!missing&&stage==="payment"&&checkout&&<Payment checkout={checkout} method={method} setMethod={setMethod} busy={busy} notice={notice} onPay={pay}/>} {commerceOn&&!missing&&stage==="confirmation"&&order&&<Confirmation order={order}/>} {notice&&stage!=="payment"&&<p role="status" className="mt-5 rounded-lg bg-rose-50 p-4 text-sm font-semibold text-rose-800">{notice}</p>}</main><CreatorMarketplaceFooter onStudio={studio}/></div>;}
function State({title,copy}:{title:string;copy:string}){return <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-sm"><AlertTriangle className="mx-auto h-8 w-8 text-amber-600"/><h1 className="mt-4 text-2xl font-extrabold">{title}</h1><p className="mx-auto mt-3 max-w-xl text-sm font-medium text-slate-600">{copy}</p><div className="mt-6 flex justify-center gap-3"><Link href="/creators/plans" className="rounded-lg bg-blue-600 px-5 py-3 text-sm font-bold text-white">View Plans</Link><Link href="/creators/search" className="rounded-lg border px-5 py-3 text-sm font-bold">Explore Assets</Link></div></section>}
function Review({selection,checkout,terms,setTerms,busy,onContinue}:{selection:CreatorCommerceSelection;checkout:CreatorCommerceCheckoutDTO|null;terms:boolean;setTerms:(v:boolean)=>void;busy:boolean;onContinue:()=>void}){return <section className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="rounded-2xl border bg-white p-6"><p className="text-xs font-bold uppercase tracking-wide text-blue-700">Creator checkout review</p><h1 className="mt-2 text-3xl font-extrabold">Review your testing purchase</h1><h2 className="mt-7 text-lg font-bold">{checkout?.items[0]?.title??selection.planId??selection.assetSlug}</h2><p className="mt-2 text-sm font-medium text-slate-600">{selection.productType.replaceAll("_"," ")} · {selection.billingCycle??"one-time license"}</p><div className="mt-6 rounded-xl bg-slate-50 p-4"><h3 className="font-bold">Rights and activation</h3><p className="mt-2 text-sm text-slate-600">Rights are a testing snapshot only. Entitlement remains pending and downloads stay unavailable.</p></div><label className="mt-6 flex gap-3 text-sm font-semibold"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)} className="mt-1 h-4 w-4"/>I understand this is a test flow and no subscription or license will be activated.</label></div><aside className="h-fit rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Order summary</h2><p className="mt-5 flex justify-between text-sm"><span>Authoritative total</span><strong>{checkout?money(checkout.totalAmount):"Calculated securely next"}</strong></p><p className="mt-3 text-xs leading-5 text-slate-500">Taxes and totals are recalculated server-side from testing configuration. Travel credits and offers do not apply.</p><button disabled={!terms||busy} onClick={onContinue} className="mt-6 min-h-11 w-full rounded-lg bg-blue-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-40">{busy?"Creating testing checkout…":"Proceed to Test Payment"}</button></aside></section>}
function Payment({checkout,method,setMethod,busy,notice,onPay}:{checkout:CreatorCommerceCheckoutDTO;method:string;setMethod:(v:string)=>void;busy:boolean;notice:string;onPay:(v:"success"|"failure")=>void}){return <section className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="rounded-2xl border bg-white p-6"><CreditCard className="h-8 w-8 text-blue-700"/><h1 className="mt-4 text-3xl font-extrabold">Test payment</h1><p className="mt-2 text-sm font-medium text-slate-600">Choose a placeholder method. No provider SDK or gateway is called.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{["upi","card","netbanking"].map(item=><button key={item} onClick={()=>setMethod(item)} className={`min-h-12 rounded-lg border px-4 text-sm font-bold capitalize ${method===item?"border-blue-600 bg-blue-50 text-blue-800":"border-slate-200"}`}>{item}</button>)}</div>{notice&&<p role="status" className="mt-5 rounded-lg bg-rose-50 p-4 text-sm font-semibold text-rose-800">{notice}</p>}<div className="mt-6 flex flex-col gap-3 sm:flex-row"><button disabled={busy} onClick={()=>onPay("success")} className="min-h-11 rounded-lg bg-blue-600 px-5 py-3 text-sm font-bold text-white">Run Test Success</button><button disabled={busy} onClick={()=>onPay("failure")} className="min-h-11 rounded-lg border border-rose-300 px-5 py-3 text-sm font-bold text-rose-700">Simulate Failure</button></div></div><aside className="h-fit rounded-2xl bg-[#071831] p-6 text-white"><LockKeyhole className="h-6 w-6 text-blue-300"/><h2 className="mt-4 text-xl font-bold text-white">{money(checkout.totalAmount)}</h2><p className="mt-2 text-sm text-slate-200">Testing amount · INR</p><p className="mt-5 text-xs leading-5 text-slate-300">Gateway calls, wallet mutation and payment persistence are disabled.</p></aside></section>}
function Confirmation({order}:{order:CreatorCommerceOrderDTO}){return <section className="mx-auto mt-8 max-w-3xl rounded-2xl border bg-white p-8 text-center shadow-sm"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-600"/><p className="mt-5 text-xs font-bold uppercase tracking-wide text-emerald-700">Testing payment successful</p><h1 className="mt-2 text-3xl font-extrabold">Your test order is confirmed</h1><p className="mt-3 text-sm font-medium text-slate-600">No real funds were charged. Entitlement, certificate, invoice and download remain unavailable.</p><dl className="mt-7 grid gap-3 rounded-xl bg-slate-50 p-5 text-left sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Order ID</dt><dd className="mt-1 break-all text-sm font-bold">{order.orderId}</dd></div><div><dt className="text-xs text-slate-500">Amount</dt><dd className="mt-1 text-sm font-bold">{money(order.amounts.totalAmount)}</dd></div><div><dt className="text-xs text-slate-500">Payment</dt><dd className="mt-1 text-sm font-bold">Testing succeeded</dd></div><div><dt className="text-xs text-slate-500">Entitlement</dt><dd className="mt-1 text-sm font-bold text-amber-700">Pending testing</dd></div></dl><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href={`/creators/orders/${order.orderId}`} className="rounded-lg bg-blue-600 px-5 py-3 text-sm font-bold text-white">View Order</Link><Link href="/creators/library" className="rounded-lg border px-5 py-3 text-sm font-bold">View Library</Link><Link href="/creators/search" className="rounded-lg border px-5 py-3 text-sm font-bold">Explore Assets</Link></div><p className="mt-6 inline-flex items-center gap-2 text-xs font-semibold text-slate-500"><ShieldCheck className="h-4 w-4"/>Secure downloads will be addressed only in a later phase.</p></section>}
