import { Check, X } from "lucide-react";
import { allowedUses, restrictedUses, rightsOverview } from "@/app/lib/creators/creatorLicensingData";

export default function CreatorRightsGrid() {
  return <>
    <section className="mx-auto max-w-[1440px] px-4 py-14 sm:px-6 lg:px-10"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-700">Licensing made understandable</p><h2 className="mt-2">Understanding your rights</h2><p className="mt-3 font-medium text-slate-600">Six practical concepts help you evaluate an asset before it enters a campaign or client workflow.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rightsOverview.map(({ title, description, icon: Icon, tone }) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className={`grid h-11 w-11 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></span><h3 className="mt-4 text-lg font-bold">{title}</h3><p className="mt-2 text-sm font-medium text-slate-600">{description}</p></article>)}</div></section>
    <section className="border-y border-slate-200 bg-white py-14"><div className="mx-auto grid max-w-[1440px] gap-8 px-4 sm:px-6 lg:grid-cols-2 lg:px-10"><div><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><Check className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-wide text-emerald-700">Commonly permitted</p><h2 className="mt-1">Allowed uses</h2></div></div><p className="mt-3 font-medium text-slate-600">Standard digital use cases when the asset and release status support commercial licensing.</p><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3">{allowedUses.map(({ label, icon: Icon }) => <div key={label} className="flex min-h-20 flex-col justify-center rounded-xl border border-emerald-100 bg-emerald-50/60 p-3"><Icon className="h-5 w-5 text-emerald-700" /><span className="mt-2 text-sm font-semibold text-slate-800">{label}</span></div>)}</div></div>
      <div><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-rose-100 text-rose-700"><X className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-wide text-rose-700">Always review</p><h2 className="mt-1">Restricted uses</h2></div></div><p className="mt-3 font-medium text-slate-600">Uses that undermine creator ownership, safety, authenticity or applicable law remain prohibited.</p><div className="mt-6 grid grid-cols-2 gap-3">{restrictedUses.map((label) => <div key={label} className="flex min-h-14 items-center gap-2 rounded-xl border border-rose-100 bg-rose-50/60 px-3 py-2"><X className="h-4 w-4 shrink-0 text-rose-700" /><span className="text-sm font-semibold text-slate-800">{label}</span></div>)}</div></div></div></section>
  </>;
}
