import { ArrowRight, Building2, Landmark, Radio, Tv2 } from "lucide-react";

const customUses = [{ label: "Tourism campaigns", icon: Landmark }, { label: "TV & broadcast", icon: Tv2 }, { label: "Hotel groups", icon: Building2 }, { label: "Government & exclusive rights", icon: Radio }];

export default function CreatorLicensingCTA({ notice, onContact, onPlans, onExplore }: { notice: string; onContact: () => void; onPlans: () => void; onExplore: () => void }) {
  return <>
    <section className="mx-auto max-w-[1440px] px-4 py-14 sm:px-6 lg:px-10"><div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-violet-700 via-purple-700 to-[#071831] p-6 text-white shadow-2xl sm:p-9 lg:p-12"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-white/10 blur-3xl" /><div className="relative grid gap-8 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-violet-200">Enterprise licensing</p><h2 className="mt-2 text-white">Need a Custom License?</h2><p className="mt-4 max-w-2xl font-medium text-violet-100">Build a tailored rights package for large tourism campaigns, television, broadcast, hotel groups, government programs and exclusive usage.</p><button type="button" onClick={onContact} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-lg bg-white px-6 py-3 font-bold text-violet-800 hover:bg-violet-50">Contact Licensing Team <ArrowRight className="h-4 w-4" /></button>{notice && <p role="status" className="mt-3 text-sm font-semibold text-white">{notice}</p>}</div><div className="grid grid-cols-2 gap-3">{customUses.map(({ label, icon: Icon }) => <div key={label} className="rounded-xl border border-white/15 bg-white/10 p-4 backdrop-blur"><Icon className="h-5 w-5 text-violet-200" /><span className="mt-3 block text-sm font-semibold text-white">{label}</span></div>)}</div></div></div></section>
    <section className="bg-blue-600 py-10 text-white"><div className="mx-auto flex max-w-[1320px] flex-col gap-6 px-4 text-center sm:px-6 lg:flex-row lg:items-center lg:justify-between lg:px-10 lg:text-left"><div><h2 className="text-white">Ready to get started?</h2><p className="mt-2 font-medium text-blue-100">Choose a plan or explore premium Creator assets with transparent licensing.</p></div><div className="flex flex-col gap-3 sm:flex-row sm:justify-center"><button type="button" onClick={onPlans} className="min-h-11 rounded-lg bg-white px-6 py-3 font-bold text-blue-700 hover:bg-blue-50">View Plans</button><button type="button" onClick={onExplore} className="min-h-11 rounded-lg border border-white/40 bg-blue-700 px-6 py-3 font-bold text-white hover:bg-blue-800">Explore Assets</button></div></div></section>
  </>;
}
