import { ChevronDown, RotateCcw } from "lucide-react";
import type { ReadonlyURLSearchParams } from "next/navigation";
import type { CreatorCategory } from "@/app/lib/creators/creatorCatalogTypes";

const types = [["", "All"], ["photo", "Photos"], ["video", "Videos"], ["reel", "Reels"], ["drone", "Drone"], ["template", "Templates"], ["presets", "Presets"], ["graphics", "Graphics"], ["guides", "Destination Guides"]];
const colors = ["white", "black", "blue", "green", "red", "orange", "purple"];
export default function CreatorSearchFilters({ categories, params, onUpdate, onClear }: { categories: CreatorCategory[]; params: ReadonlyURLSearchParams; onUpdate: (patch: Record<string, string | null>) => void; onClear: () => void }) {
  const select = (key: string, value: string) => onUpdate({ [key]: value || null });
  const content = <div className="mt-3 divide-y divide-slate-100">
    <Filter title="Asset Type" count={types.length - 1}><RadioList name="type" value={params.get("type") ?? ""} options={types} onChange={(value) => select("type", value)} /></Filter>
    <Filter title="Orientation" count={3}><RadioList name="orientation" value={params.get("orientation") ?? ""} options={[["", "Any"], ["landscape", "Landscape"], ["portrait", "Portrait"], ["square", "Square"]]} onChange={(value) => select("orientation", value)} /></Filter>
    <Filter title="Color" count={7}><div className="flex flex-wrap gap-2">{colors.map((color) => <button key={color} type="button" aria-label={`Filter ${color}`} onClick={() => select("color", params.get("color") === color ? "" : color)} className={`h-6 w-6 rounded-full border-2 shadow-inner ${params.get("color") === color ? "ring-2 ring-blue-500 ring-offset-2" : ""}`} style={{ backgroundColor: color }} />)}</div></Filter>
    <Filter title="Location" count={4}><select value={params.get("location") ?? ""} onChange={(event) => select("location", event.target.value)} className="h-9 w-full rounded-md border border-slate-200 px-2 text-[10px] font-bold"><option value="">Anywhere</option><option>India</option><option>Himalaya</option><option>Jaipur</option><option>City</option></select></Filter>
    <Filter title="Category" count={categories.length}><select value={params.get("category") ?? ""} onChange={(event) => select("category", event.target.value)} className="h-9 w-full rounded-md border border-slate-200 px-2 text-[10px] font-bold"><option value="">All categories</option>{categories.map((category) => <option key={category.slug} value={category.slug}>{category.title}</option>)}</select></Filter>
    <Filter title="Resolution" count={3}><RadioList name="resolution" value={params.get("resolution") ?? ""} options={[["", "Any"], ["1080", "HD"], ["4k", "4K"], ["8k", "8K"]]} onChange={(value) => select("resolution", value)} /></Filter>
    <Filter title="Duration" count={2}><RadioList name="duration" value={params.get("duration") ?? ""} options={[["", "Any"], ["short", "Under 1 min"], ["long", "1 min+"]]} onChange={(value) => select("duration", value)} /></Filter>
    <Filter title="License Type" count={4}><RadioList name="license" value={params.get("license") ?? ""} options={[["", "Any"], ["commercial", "Standard"], ["extended", "Extended"], ["commercial", "Commercial"], ["editorial", "Editorial"]]} onChange={(value) => select("license", value)} /></Filter>
    <Filter title="Price" count={3}><RadioList name="price" value={params.get("price") ?? ""} options={[["", "Any price"], ["under-499", "Under ₹499"], ["under-999", "Under ₹999"]]} onChange={(value) => select("price", value)} /></Filter>
    <div className="pt-4"><label className="flex items-center justify-between gap-3 text-[10px] font-black">Included with Creator Plan<button type="button" role="switch" aria-checked={params.get("plan") === "included"} onClick={() => select("plan", params.get("plan") === "included" ? "" : "included")} className={`relative h-5 w-9 rounded-full ${params.get("plan") === "included" ? "bg-blue-600" : "bg-slate-300"}`}><span className={`absolute top-0.5 h-4 w-4 rounded-full bg-white ${params.get("plan") === "included" ? "left-[18px]" : "left-0.5"}`} /></button></label></div>
  </div>;
  return <><details className="rounded-xl border border-slate-200 bg-white p-4 lg:hidden"><summary className="flex cursor-pointer list-none items-center justify-between text-sm font-black">Filters <span className="text-[9px] text-blue-700">Open filters</span></summary>{content}<button type="button" onClick={onClear} className="mt-4 inline-flex items-center gap-1 text-[9px] font-black text-blue-700"><RotateCcw className="h-3 w-3" />Clear all</button></details><aside className="hidden h-fit rounded-xl border border-slate-200 bg-white p-4 lg:sticky lg:top-20 lg:block"><div className="flex items-center justify-between"><h2 className="text-sm font-black">Filters</h2><button type="button" onClick={onClear} className="inline-flex items-center gap-1 text-[9px] font-black text-blue-700"><RotateCcw className="h-3 w-3" />Clear all</button></div>{content}</aside></>;
}
function Filter({ title, count, children }: { title: string; count: number; children: React.ReactNode }) { return <details open className="group py-3"><summary className="flex cursor-pointer list-none items-center justify-between text-[11px] font-black">{title}<span className="flex items-center gap-2 text-[9px] text-slate-400">{count}<ChevronDown className="h-3 w-3 group-open:rotate-180" /></span></summary><div className="mt-3">{children}</div></details>; }
function RadioList({ name, value, options, onChange }: { name: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <div className="space-y-2">{options.map(([option, label]) => <button type="button" role="radio" aria-checked={value === option} key={`${name}-${option}-${label}`} onClick={() => onChange(option!)} className="flex w-full items-center gap-2 text-left text-[10px] font-semibold text-slate-600"><span className={`grid h-3.5 w-3.5 place-items-center rounded-full border ${value === option ? "border-blue-600" : "border-slate-300"}`}>{value === option && <span className="h-1.5 w-1.5 rounded-full bg-blue-600" />}</span>{label}</button>)}</div>; }
