"use client";

import Image from "next/image";
import Link from "next/link";
import { BadgeCheck, Eye, Heart, SearchX, Star } from "lucide-react";
import { useState } from "react";
import type { CreatorAsset } from "@/app/lib/creators/creatorCatalogTypes";
import { marketplaceHomeAssets } from "@/app/lib/creators/creatorMarketplaceHomeData";

export default function CreatorSearchResults({ assets, view, onClear, onPopular }: { assets: CreatorAsset[]; view: "grid" | "list"; onClear: () => void; onPopular: (value: string) => void }) {
  const [wishlist, setWishlist] = useState<Set<string>>(new Set());
  if (!assets.length) return <div className="mt-6 rounded-xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-blue-50 text-blue-700"><SearchX className="h-6 w-6" /></span><h2 className="mt-4 text-lg font-black">No matching assets</h2><p className="mt-2 text-xs font-medium text-slate-500">Try fewer filters or explore a popular marketplace search.</p><div className="mt-5 flex flex-wrap justify-center gap-2"><button type="button" onClick={onClear} className="rounded-md bg-blue-600 px-4 py-2 text-[10px] font-black text-white">Clear Filters</button>{["India", "Aerial", "City"].map((item) => <button type="button" key={item} onClick={() => onPopular(item)} className="rounded-md border border-slate-300 px-4 py-2 text-[10px] font-black">{item}</button>)}<Link href="/creators/categories/photos" className="rounded-md border border-slate-300 px-4 py-2 text-[10px] font-black">Browse Categories</Link></div></div>;
  return <div className={`mt-6 grid gap-4 ${view === "grid" ? "grid-cols-1 min-[480px]:grid-cols-2 xl:grid-cols-3" : "grid-cols-1"}`}>{assets.map((asset) => { const home = marketplaceHomeAssets.find((item) => item.slug === asset.slug); const image = home?.previewImage ?? "/themes/banners/culture-1.jpg"; return <article key={asset.slug} className={`group overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg ${view === "list" ? "sm:grid sm:grid-cols-[220px_1fr]" : ""}`}><div className={`relative overflow-hidden bg-slate-100 ${view === "list" ? "aspect-[4/3] sm:aspect-auto" : "aspect-[4/3]"}`}><Image src={image} alt={asset.title} fill sizes="(min-width:1280px) 25vw, 50vw" className="object-cover transition duration-500 group-hover:scale-105" /><span className="absolute left-3 top-3 rounded bg-[#071831]/85 px-2 py-1 text-[9px] font-black uppercase text-white">{asset.mediaType}</span><button type="button" onClick={() => setWishlist((current) => { const next = new Set(current); if (next.has(asset.slug)) next.delete(asset.slug); else next.add(asset.slug); return next; })} aria-label="Toggle wishlist" className="absolute right-3 top-3 grid h-8 w-8 place-items-center rounded-full bg-white shadow"><Heart className={`h-4 w-4 ${wishlist.has(asset.slug) ? "fill-rose-600 text-rose-600" : ""}`} /></button><Link href={`/creators/assets/${asset.slug}`} className="absolute inset-0" aria-label={`Open ${asset.title}`} /><Link href={`/creators/assets/${asset.slug}`} className="absolute bottom-3 right-3 inline-flex items-center gap-1 rounded-md bg-white px-2.5 py-1.5 text-[9px] font-black opacity-0 shadow transition group-hover:opacity-100"><Eye className="h-3 w-3" />Quick Preview</Link></div><div className="p-4"><Link href={`/creators/assets/${asset.slug}`} className="line-clamp-2 text-sm font-black hover:text-blue-700">{asset.title}</Link><Link href={`/creators/authors/${asset.creatorSlug}`} className="mt-2 flex items-center gap-1 text-[10px] font-bold text-slate-500 hover:text-blue-700">{asset.creatorName}<BadgeCheck className="h-3 w-3 text-blue-600" /></Link><div className="mt-3 flex items-center gap-2 text-[10px] font-bold text-slate-500"><span className="inline-flex items-center gap-1 text-amber-700"><Star className="h-3 w-3 fill-current" />{asset.rating}</span><span>({asset.reviewCount})</span><span>{asset.resolution}</span></div><div className="mt-4 border-t border-slate-100 pt-3"><p className="text-[10px] font-black text-blue-700">Included with Creator Plan</p><p className="mt-1 text-[9px] font-semibold text-slate-500">License from ₹{asset.price.toLocaleString("en-IN")}</p></div></div></article>; })}</div>;
}
