"use client";
import {useCallback,useEffect,useState} from 'react';
import {CalendarDays,CheckCircle2,Clock3,Hotel,RefreshCcw,Users} from 'lucide-react';
import {getAdminApiBaseUrl,readAdminSession} from '@/app/lib/admin/adminApiClient';
import {getStoredAuthToken,getTplApiBaseUrl,tplApiRequest} from '@/app/lib/api/tplApiClient';
import {validHotelBookingSnapshot,type HotelBookingRecord,type HotelBookingSnapshot,type HotelStayAction} from '@/app/lib/partner/partnerHotelBookings';
import {requestChangeSummary,validHotelBookingRequestSnapshot,type HotelBookingEligibility,type HotelBookingRequest,type HotelBookingRequestSnapshot} from '@/app/lib/partner/partnerHotelBookingRequests';
import styles from './PartnerCommandCenter.module.css';

type Form={type:'MODIFICATION'|'CANCELLATION';stayStart:string;stayEnd:string;adults:string;children:string;guestDisplayName:string;specialRequest:string;reasonCode:string;note:string};
const emptyForm=(b?:HotelBookingRecord|null):Form=>({type:'MODIFICATION',stayStart:b?.stayStart??'',stayEnd:b?.stayEnd??'',adults:String(b?.guestCount.adults??1),children:String(b?.guestCount.children??0),guestDisplayName:b?.guestDisplayName??'',specialRequest:'',reasonCode:'GUEST_REQUEST',note:''});

export default function PartnerHotelBookingWorkspace({organizationId,admin=false}:{organizationId:string;admin?:boolean}){
 const [data,setData]=useState<HotelBookingSnapshot|null>(null),[requests,setRequests]=useState<HotelBookingRequestSnapshot|null>(null),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[status,setStatus]=useState('ALL'),[search,setSearch]=useState(''),[requestStatus,setRequestStatus]=useState('ALL'),[form,setForm]=useState<Form>(emptyForm()),[decisionReason,setDecisionReason]=useState('');
 const base=`/api/v1/${admin?'admin/partners/workspaces':'partner/organizations'}/${encodeURIComponent(organizationId)}/hotel-bookings`,requestBase=`/api/v1/${admin?'admin/partners/workspaces':'partner/organizations'}/${encodeURIComponent(organizationId)}/hotel-booking-requests`;
 const request=useCallback(async<T,>(path:string,method='GET',body?:unknown):Promise<T>=>{if(admin){const token=readAdminSession()?.session.token;if(!token)throw Error('Admin session required.');const response=await fetch(getAdminApiBaseUrl()+path,{method,headers:{Accept:'application/json',Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'}),json=await response.json();if(!response.ok||!json.ok)throw Error(json.error?.message??'Request failed.');return json.data as T;}const result=await tplApiRequest<T>(path,{method:method as 'GET'|'POST',body,headers:method==='POST'?{'X-TPL-Client-Surface':'website'}:undefined});if(!result.ok)throw Error(result.error.message);return result.data;},[admin]);
 const load=useCallback(async()=>{setBusy(true);try{const params=new URLSearchParams({status,search,limit:'25'}),[next,nextRequests]=await Promise.all([request<HotelBookingSnapshot>(base+'?'+params),request<HotelBookingRequestSnapshot>(requestBase)]);if(!validHotelBookingSnapshot(next)||next.organizationId!==organizationId||!validHotelBookingRequestSnapshot(nextRequests)||nextRequests.organizationId!==organizationId)throw Error('Booking response could not be verified.');setData(next);setRequests(nextRequests);setSelected(current=>current&&next.bookings.some(v=>v.id===current)?current:next.bookings[0]?.id??null);setMessage('');}catch(error){setMessage(error instanceof Error?error.message:'Hotel bookings could not be loaded.');}finally{setBusy(false);}},[base,organizationId,request,requestBase,search,status]);
 useEffect(()=>{void load();},[load]);
 const booking=data?.bookings.find(v=>v.id===selected)??null;
 const bookingEligibility=requests?.bookingEligibility.find(v=>v.bookingId===booking?.id)??null;
 const hasOpenRequest=Boolean(booking&&requests?.requests.some(v=>v.bookingId===booking.id&&['DRAFT','SUBMITTED','UNDER_REVIEW'].includes(v.state)));
 useEffect(()=>{setForm(emptyForm(booking));},[booking?.id]);
 async function act(booking:HotelBookingRecord,code:HotelStayAction,label:string){if(!confirm(`${label} for ${booking.bookingRef}? This records an immutable operational event.`))return;await mutate(`${base}/${encodeURIComponent(booking.id)}/actions`,{action:code,version:booking.version,idempotencyKey:`website:${booking.id}:${booking.version}:${code}`},`${label} saved.`);}
 async function mutate(path:string,body:unknown,success:string){setBusy(true);try{await request(path,'POST',body);await load();setMessage(success);}catch(error){setMessage(error instanceof Error?error.message:'The request changed. Refresh and try again.');}finally{setBusy(false);}}
 async function createRequest(){if(!booking)return;const change=form.type==='CANCELLATION'?{}:{stayStart:form.stayStart,stayEnd:form.stayEnd,adults:Number(form.adults),children:Number(form.children),guestDisplayName:form.guestDisplayName,specialRequest:form.specialRequest};if(!confirm(`Submit ${form.type.toLowerCase()} request for ${booking.bookingRef}? The booking remains unchanged until an authorized decision.`))return;await mutate(`${base}/${encodeURIComponent(booking.id)}/requests`,{requestType:form.type,reasonCode:form.reasonCode,note:form.note,requestedChanges:change,submit:true,idempotencyKey:`website:${booking.id}:${Date.now()}:${form.type}`},'Request submitted for review. The confirmed booking is unchanged until approval.');}
 async function acknowledge(item:HotelBookingRequest){if(!confirm(`Acknowledge ${item.requestRef}?`))return;await mutate(`${requestBase}/${item.id}/acknowledge`,{version:item.version,recommendation:'ACKNOWLEDGED',idempotencyKey:`website:${item.id}:${item.version}:ack`},'Request acknowledged and moved to authorized review.');}
 async function decide(item:HotelBookingRequest,decision:'approve'|'reject'){if(decisionReason.trim().length<3){setMessage('Enter a decision reason before approving or rejecting.');return;}if(!confirm(`${decision==='approve'?'Approve and apply':'Reject'} ${item.requestRef}?`))return;await mutate(`${requestBase}/${item.id}/decision`,{version:item.version,decision,reason:decisionReason.trim(),idempotencyKey:`admin:${item.id}:${item.version}:${decision}`},decision==='approve'?'Request approved and canonical booking update applied.':'Request rejected; canonical booking remains unchanged.');setDecisionReason('');}
 async function download(format:'pdf'|'xlsx'|'csv',kind:'booking'|'request'){const token=admin?readAdminSession()?.session.token:getStoredAuthToken(),origin=admin?getAdminApiBaseUrl():getTplApiBaseUrl();if(!token)return;const target=(kind==='booking'?base:requestBase)+'/export?format='+format,response=await fetch(origin+target,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!response.ok){setMessage('The bounded report could not be prepared.');return;}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`hotel-${kind==='booking'?'bookings':'booking-requests'}.${format}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const visibleRequests=requests?.requests.filter(r=>requestStatus==='ALL'||r.state===requestStatus)??[];
 return <div className={`${styles.bookingWorkspace} hotel-m3b-print`}>
  <section className={styles.panel}><div className={styles.panelHead}><div><p className={styles.eyebrow}>HOTEL-M3A + HOTEL-M3B · canonical booking operations</p><h2>Hotel booking inbox</h2><p className={styles.muted}>Requests never imply immediate confirmation. Payment, refund, settlement and provider actions remain outside this flow.</p></div><button className={styles.button} disabled={busy} onClick={()=>void load()}><RefreshCcw size={15}/> Refresh</button></div>{message?<p role="status" className={styles.readyNote}>{message}</p>:null}<div className={styles.bookingMetrics}>{[['Action required',data?.counts.actionRequired??0],['Upcoming',data?.counts.upcoming??0],['In house',data?.counts.inHouse??0],['Completed',data?.counts.completed??0]].map(([label,value])=><div key={String(label)}><strong>{value}</strong><span>{label}</span></div>)}</div><div className={styles.bookingFilters}><label>Stay status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All bookings</option><option value="CONFIRMED">New / action required</option><option value="PARTNER_ACKNOWLEDGED">Acknowledged</option><option value="READY_FOR_CHECK_IN">Check-in ready</option><option value="CHECKED_IN">In house</option><option value="CHECKED_OUT">Completed</option><option value="NO_SHOW">No-show</option><option value="CANCELLED">Cancelled</option></select></label><label>Booking, guest or room<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search bounded Hotel bookings"/></label></div></section>
  <div className={styles.bookingColumns}><section className={styles.panel} aria-label="Booking list"><h2>Bookings</h2>{data?.bookings.map(item=><button type="button" key={item.id} className={`${styles.bookingRow} ${selected===item.id?styles.bookingSelected:''}`} onClick={()=>setSelected(item.id)}><span><strong>{item.bookingRef}</strong><small>{item.guestDisplayName} · {item.room}</small></span><span><b>{item.status.replaceAll('_',' ')}</b><small>{item.stayStart} → {item.stayEnd}</small></span></button>)}{!data?.bookings.length?<p className={styles.empty}>No Hotel bookings match this authorized view.</p>:null}</section>{booking?<BookingDetail booking={booking} admin={admin} busy={busy} act={act} hasOpenRequest={hasOpenRequest}/>:<section className={styles.panel}><p className={styles.empty}>Choose a booking to view its safe operational detail.</p></section>}</div>
  {!admin&&requests?.canSubmit&&booking?<RequestComposer booking={booking} eligibility={bookingEligibility} form={form} setForm={setForm} busy={busy} submit={createRequest}/>:null}
  <section className={styles.panel}><div className={styles.panelHead}><div><p className={styles.eyebrow}>HOTEL-M3B · REQUEST ORCHESTRATION</p><h2>Modification &amp; cancellation requests</h2><p className={styles.muted}>{requests?.paymentBoundary}</p></div><label className={styles.compactFilter}>Status<select value={requestStatus} onChange={e=>setRequestStatus(e.target.value)}><option value="ALL">All requests</option>{['DRAFT','SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','WITHDRAWN','EXPIRED'].map(s=><option key={s}>{s}</option>)}</select></label></div>{admin&&requests?.canReview?<label className={styles.decisionField}>Required decision reason<input value={decisionReason} maxLength={500} onChange={e=>setDecisionReason(e.target.value)} placeholder="Explain the authorized decision"/></label>:null}<div className={styles.requestGrid}>{visibleRequests.map(item=><RequestCard key={item.id} item={item} admin={admin} busy={busy} acknowledge={acknowledge} decide={decide}/>)}</div>{!visibleRequests.length?<p className={styles.empty}>No requests match this authorized view.</p>:null}</section>
  <section className={`${styles.panel} ${styles.bookingReport}`}><div className={styles.reportHead}><div><h2>Bounded operations reports</h2><p className={styles.muted}>Role-safe fields only · clean PDF standard</p></div><aside className={styles.exportPanel}><strong>Bookings</strong><div>{(['pdf','xlsx','csv'] as const).map(f=><button key={f} onClick={()=>void download(f,'booking')}>{f.toUpperCase()}</button>)}</div><strong>Requests</strong><div>{(['pdf','xlsx','csv'] as const).map(f=><button key={f} onClick={()=>void download(f,'request')}>{f.toUpperCase()}</button>)}<button onClick={()=>window.print()}>Print</button></div></aside></div></section>
 </div>;
}
function RequestComposer({booking,eligibility,form,setForm,busy,submit}:{booking:HotelBookingRecord;eligibility:HotelBookingEligibility|null;form:Form;setForm:(v:Form)=>void;busy:boolean;submit:()=>void}){const selected=form.type==='MODIFICATION'?eligibility?.modificationEligibility:eligibility?.cancellationEligibility,eligible=Boolean(selected?.allowed);return <section className={[styles.panel,styles.requestComposer].join(' ')}><div><p className={styles.eyebrow}>REQUEST FOR {booking.bookingRef}</p><h2>Modification &amp; cancellation</h2><p className={styles.muted}>{selected?.explanation??'Checking current booking eligibility…'}</p></div><div className={styles.requestForm}><label>Request type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value as Form['type']})}><option value="MODIFICATION">Modification</option><option value="CANCELLATION">Full cancellation</option></select></label>{form.type==='MODIFICATION'?<><label>Requested check-in<input type="date" value={form.stayStart} onChange={e=>setForm({...form,stayStart:e.target.value})}/></label><label>Requested check-out<input type="date" value={form.stayEnd} onChange={e=>setForm({...form,stayEnd:e.target.value})}/></label><label>Adults<input type="number" min="1" max="8" value={form.adults} onChange={e=>setForm({...form,adults:e.target.value})}/></label><label>Children<input type="number" min="0" max="7" value={form.children} onChange={e=>setForm({...form,children:e.target.value})}/></label><label>Guest name correction<input value={form.guestDisplayName} maxLength={120} onChange={e=>setForm({...form,guestDisplayName:e.target.value})}/></label><label className={styles.wideField}>Special request (not guaranteed)<input value={form.specialRequest} maxLength={500} onChange={e=>setForm({...form,specialRequest:e.target.value})}/></label></>:null}<label>Reason code<select value={form.reasonCode} onChange={e=>setForm({...form,reasonCode:e.target.value})}><option value="GUEST_REQUEST">Guest request</option><option value="DATE_CHANGE">Date change</option><option value="PLAN_CHANGED">Plans changed</option><option value="CORRECTION">Correction</option></select></label><label className={styles.wideField}>Safe note<input value={form.note} maxLength={500} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><button className={styles.primaryAction} disabled={busy||!eligible} onClick={submit}>Submit request for review</button></section>}
function RequestCard({item,admin,busy,acknowledge,decide}:{item:HotelBookingRequest;admin:boolean;busy:boolean;acknowledge:(r:HotelBookingRequest)=>void;decide:(r:HotelBookingRequest,d:'approve'|'reject')=>void}){return <article className={styles.requestCard}><div className={styles.panelHead}><div><strong>{item.requestRef}</strong><small>{item.bookingRef} · {item.requestType}</small></div><span className={styles.bookingStatus}>{item.state.replaceAll('_',' ')}</span></div><p className={styles.muted}>{item.eligibility.explanation}</p><div className={styles.compare}><div><b>Before</b>{requestChangeSummary(item.before).slice(0,6).map(v=><span key={v}>{v}</span>)}</div><div><b>Requested</b>{requestChangeSummary(item.requestedChanges).map(v=><span key={v}>{v}</span>)}</div></div><p className={styles.boundaryNote}>{item.financialImpactState.replaceAll('_',' ')} · payment {item.paymentDisclosure.replaceAll('_',' ')} · v{item.version}</p>{!admin&&item.canAcknowledge?<button disabled={busy} onClick={()=>acknowledge(item)}>Acknowledge request</button>:null}{admin&&item.canDecide?<div className={styles.bookingActions}><button disabled={busy} onClick={()=>decide(item,'approve')}>Approve &amp; apply</button><button disabled={busy} onClick={()=>decide(item,'reject')}>Reject</button></div>:null}<details><summary>Immutable request timeline</summary>{item.timeline.map(e=><p key={e.id}>{e.toState.replaceAll('_',' ')} · v{e.version} · {e.clientSurface} · {new Date(e.at).toLocaleString('en-GB',{timeZone:'UTC'})} UTC</p>)}</details></article>}
function BookingDetail({booking,admin,busy,act,hasOpenRequest}:{booking:HotelBookingRecord;admin:boolean;busy:boolean;act:(b:HotelBookingRecord,c:HotelStayAction,l:string)=>void;hasOpenRequest:boolean}){return <section className={styles.panel} aria-label="Booking detail"><div className={styles.panelHead}><div><p className={styles.eyebrow}>{booking.syntheticFixture?'SYNTHETIC STAGING BOOKING':'HOTEL BOOKING'}</p><h2>{booking.bookingRef}</h2></div><span className={styles.bookingStatus}>{booking.status.replaceAll('_',' ')}</span></div><div className={styles.bookingFacts}><span><Hotel size={16}/><strong>{booking.room}</strong><small>{booking.hotel} · {booking.service}</small></span><span><CalendarDays size={16}/><strong>{booking.stayStart} → {booking.stayEnd}</strong><small>{booking.nights} nights · {booking.roomCount} room</small></span><span><Users size={16}/><strong>{booking.guestDisplayName}</strong><small>{booking.guestCount.adults} adult · {booking.guestCount.children} children</small></span><span><CheckCircle2 size={16}/><strong>{booking.allocationState}</strong><small>Payment: {booking.paymentDisclosure.replaceAll('_',' ')}</small></span></div><p className={styles.muted}>Version {booking.version} · latest source {booking.lastClientSurface}. Sensitive customer and payment data are excluded.</p>{hasOpenRequest&&!admin?<p className={styles.boundaryNote}>An open modification/cancellation request exists. “Acknowledge request” below advances that request; the separate stay-lifecycle action does not approve it.</p>:null}{!admin&&booking.allowedActions.length?<div className={styles.bookingActions}>{booking.allowedActions.map(item=><button key={item.code} disabled={busy} onClick={()=>act(booking,item.code,item.label)}>{item.code==='ACKNOWLEDGE'?'Acknowledge confirmed booking · stay lifecycle':item.label}</button>)}</div>:admin?<p className={styles.empty}>Admin stay view is read-only. Request decisions use separate narrow authority.</p>:<p className={styles.empty}>No further stay action is available.</p>}<h3 className={styles.bookingTimelineTitle}><Clock3 size={16}/> Immutable stay timeline</h3><ol className={styles.bookingTimeline}>{booking.timeline.map(e=><li key={e.id}><strong>{e.toStatus.replaceAll('_',' ')}</strong><span>{e.eventType.replaceAll('.',' · ')} · version {e.version} · {e.clientSurface}</span><time>{new Date(e.at).toLocaleString('en-GB',{timeZone:'UTC'})} UTC</time></li>)}</ol></section>}
