"use client";
import {useEffect,useState} from 'react';
import {emptyPartnerAvailabilityDraft,validatePartnerAvailabilityDraft,type PartnerAvailabilityDraft} from '@/app/lib/partner/partnerAvailabilityDraft';
import type {PartnerSupply} from '@/app/lib/partner/partnerSupply';
import styles from './PartnerCommandCenter.module.css';

type Props={data:PartnerSupply;admin:boolean;busy:boolean;save:(body:Record<string,unknown>)=>Promise<void>;refresh:()=>Promise<void>;onDirtyChange?:(dirty:boolean)=>void};
export default function PartnerAvailabilityEditor({data,admin,busy,save,refresh,onDirtyChange}:Props){
 const [draft,setDraft]=useState<PartnerAvailabilityDraft>(emptyPartnerAvailabilityDraft),[editing,setEditing]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const writable=data.canWriteSupply&&!admin&&data.items.length>0,selected=data.items.find(item=>item.id===draft.supplyItemId),dirty=editing&&(Boolean(draft.id)||Boolean(draft.supplyItemId)||Boolean(draft.startDate)||Boolean(draft.endDate)||Boolean(draft.availableCapacity));
 useEffect(()=>onDirtyChange?.(dirty),[dirty,onDirtyChange]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>()=>onDirtyChange?.(false),[onDirtyChange]);
 const change=(next:Partial<PartnerAvailabilityDraft>)=>{setDraft(current=>({...current,...next}));setError('');setNotice('');};
 const beginCreate=()=>{setDraft({...emptyPartnerAvailabilityDraft(),supplyItemId:data.items[0]?.id??''});setEditing(true);setError('');setNotice('');};
 const beginEdit=(record:PartnerSupply['availability'][number])=>{setDraft({id:record.id,version:record.version,supplyItemId:record.supplyItemId,startDate:record.startDate,endDate:record.endDate,availableCapacity:String(record.availableCapacity),status:record.status==='closed'?'closed':'open'});setEditing(true);setError('');setNotice('');};
 const cancel=()=>{setDraft(emptyPartnerAvailabilityDraft());setEditing(false);setError('');};
 async function submit(){const checked=validatePartnerAvailabilityDraft(draft,selected?.capacityTotal);if(!checked.ok){setError(checked.message);return;}try{await save(checked.body);setNotice(draft.id?'Availability updated.':'Availability added.');setDraft(emptyPartnerAvailabilityDraft());setEditing(false);}catch(e){setError(e instanceof Error?e.message:'Availability could not be saved. Your entries are still here.');}}
 return <section className={styles.panel} aria-labelledby="partner-availability-title"><div className={styles.panelHead}><div><h2 id="partner-availability-title">Availability</h2><span className={styles.muted}>Set date-only availability against the saved total capacity.</span></div>{writable&&!editing?<button type="button" className={styles.primaryAction} onClick={beginCreate}>Add availability</button>:null}</div>
  {notice?<p role="status" className={styles.readyNote}>{notice}</p>:null}
  {data.availability.map(record=>{const item=data.items.find(value=>value.id===record.supplyItemId);return <div key={record.id} className={styles.record}><strong>{item?.label??'Historical inventory'}</strong><span>{record.startDate} – {record.endDate}</span><span>{record.status==='closed'?'Closed':`${record.availableCapacity} of ${item?.capacityTotal??'—'} available`}</span><small>version {record.version}</small>{writable?<button type="button" onClick={()=>beginEdit(record)} disabled={busy||editing}>Edit</button>:null}</div>;})}
  {!data.availability.length&&!editing?<div className={styles.empty}>No availability ranges yet. Add a date range for the inventory item.</div>:null}
  {editing?<form className={styles.editor} onSubmit={event=>{event.preventDefault();void submit();}}><h3>{draft.id?'Edit availability':'Add availability'}</h3><label><span>Inventory item <b>Required</b></span><select aria-label="Inventory item" required disabled={Boolean(draft.id)} value={draft.supplyItemId} onChange={event=>change({supplyItemId:event.target.value})}><option value="">Choose inventory</option>{data.items.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><div className={styles.fieldHint}>Total capacity: <strong>{selected?.capacityTotal??'Choose an item'}</strong></div><label><span>Available from <b>Required</b></span><input aria-label="Available from" type="date" required value={draft.startDate} onChange={event=>change({startDate:event.target.value})}/></label><label><span>Available to <b>Required</b></span><input aria-label="Available to" type="date" required value={draft.endDate} onChange={event=>change({endDate:event.target.value})}/></label><label><span>Available capacity <b>Required</b></span><input aria-label="Available capacity" inputMode="numeric" pattern="[0-9]+" type="number" min="0" max={selected?.capacityTotal} step="1" required value={draft.availableCapacity} onChange={event=>change({availableCapacity:event.target.value})}/></label><label><span>Availability status <b>Required</b></span><select aria-label="Availability status" value={draft.status} onChange={event=>change({status:event.target.value as 'open'|'closed'})}><option value="open">Open</option><option value="closed">Closed / unavailable</option></select></label>{error?<p role="alert" className={styles.empty}>{error}{error.includes('changed')?<button type="button" onClick={()=>void refresh()}>Refresh availability</button>:null}</p>:null}<div className={styles.tools}><button type="submit" className={styles.primaryAction} disabled={busy}>{busy?'Saving…':draft.id?'Save availability':'Add availability'}</button><button type="button" onClick={cancel} disabled={busy}>Cancel</button></div></form>:null}
  {!writable?<div className={styles.empty}>{admin||!data.canWriteSupply?'Availability is read-only for this account.':'Create inventory before adding availability.'}</div>:null}
 </section>;
}
