"use client";
import {useMemo,useState} from 'react';
import type {PartnerSupply} from '@/app/lib/partner/partnerSupply';
import styles from './PartnerCommandCenter.module.css';

type Draft={id?:string;version?:number;serviceScopeId:string;supplyItemId?:string;scope:'PROPERTY'|'ROOM';shortDescription:string;detailedDescription:string;amenityCodes:string[];structuredValues:Record<string,string>};
const blank=(scope:'PROPERTY'|'ROOM',serviceScopeId:string,supplyItemId?:string):Draft=>({scope,serviceScopeId,supplyItemId,shortDescription:'',detailedDescription:'',amenityCodes:[],structuredValues:{}});
export default function PartnerHotelContentEditor({data,admin,busy,save,review,refresh,onDirtyChange}:{data:PartnerSupply;admin:boolean;busy:boolean;save:(value:Record<string,unknown>)=>Promise<void>;review:(id:string,version:number,decision:'approve'|'reject',reason:string)=>Promise<void>;refresh:()=>Promise<void>;onDirtyChange?:(dirty:boolean)=>void}){
 const hotel=data.profiles.find(profile=>profile.profileCode==='HOTEL_CONTENT_PROFILE_V1'),serviceScope=data.serviceScopes.find(value=>value.serviceCode===hotel?.serviceCode),[selected,setSelected]=useState<'PROPERTY'|string>('PROPERTY'),[draft,setDraft]=useState<Draft|null>(null),[message,setMessage]=useState('');
 const record=useMemo(()=>data.contentRecords.find(value=>selected==='PROPERTY'?value.scope==='PROPERTY'&&value.serviceScopeId===serviceScope?.id:value.supplyItemId===selected),[data.contentRecords,serviceScope?.id,selected]),item=selected==='PROPERTY'?null:data.items.find(value=>value.id===selected),targetScope=selected==='PROPERTY'?'PROPERTY':'ROOM',catalogue=data.amenityCatalogue.filter(value=>value.profileCode===hotel?.profileCode&&value.profileVersion===hotel?.profileVersion&&value.scope===targetScope),groups=Array.from(new Set(catalogue.map(value=>value.category)));
 if(!hotel||!serviceScope)return <section className={styles.panel}><h2>Hotel content & amenities</h2><div className={styles.empty}>Content and amenities are not configured for this service.</div></section>;
 const start=()=>{const next=record?{id:record.id,version:record.version,serviceScopeId:record.serviceScopeId,supplyItemId:record.supplyItemId??undefined,scope:record.scope,shortDescription:record.shortDescription,detailedDescription:record.detailedDescription??'',amenityCodes:record.amenities.map(value=>value.code),structuredValues:{...record.structuredValues}}:blank(targetScope,serviceScope.id,item?.id);setDraft(next);setMessage('');};
 const change=(next:Draft)=>{setDraft(next);onDirtyChange?.(true);};
 const choose=(value:'PROPERTY'|string)=>{setSelected(value);setDraft(null);setMessage('');onDirtyChange?.(false);};
 const toggle=(code:string,valueKind:'BOOLEAN'|'ENUM',allowedValues:string[])=>{if(!draft)return;const chosen=draft.amenityCodes.includes(code),amenityCodes=chosen?draft.amenityCodes.filter(value=>value!==code):[...draft.amenityCodes,code],structuredValues={...draft.structuredValues};if(chosen)delete structuredValues[code];else if(valueKind==='ENUM')structuredValues[code]=allowedValues[0]??'';change({...draft,amenityCodes,structuredValues});};
 async function submit(){if(!draft)return;if(draft.shortDescription.trim().length<10){setMessage('Enter at least 10 characters for the customer-facing description.');return;}try{await save({...draft,shortDescription:draft.shortDescription.trim(),detailedDescription:draft.detailedDescription.trim()||undefined});setDraft(null);onDirtyChange?.(false);setMessage('Saved for TPL content review.');}catch(error){setMessage(error instanceof Error?error.message:'The content could not be saved. Your entries are still here.');}}
 async function decide(decision:'approve'|'reject'){if(!record)return;const reason=prompt(decision==='approve'?'Enter a short approval reason.':'Explain what needs to change.');if(!reason)return;try{await review(record.id,record.version,decision,reason);setMessage(decision==='approve'?'Content approved for the staging Hotel detail.':'Content returned for changes.');}catch(error){setMessage(error instanceof Error?error.message:'The review decision could not be saved.');}}
 return <section className={styles.panel} aria-label="Hotel content and amenities"><div className={styles.panelHead}><div><h2>Hotel content & amenities</h2><p className={styles.muted}>Standard selections and descriptions use {hotel.profileCode} · version {hotel.profileVersion}.</p></div><button type="button" onClick={()=>void refresh()} disabled={busy}>Refresh</button></div>
  <div className={styles.actions}><button type="button" className={selected==='PROPERTY'?styles.primaryAction:undefined} onClick={()=>choose('PROPERTY')}>Property details</button>{data.items.filter(value=>value.serviceScopeId===serviceScope.id).map(value=><button type="button" key={value.id} className={selected===value.id?styles.primaryAction:undefined} onClick={()=>choose(value.id)}>{value.label}</button>)}</div>
  <div className={styles.record}><strong>{targetScope==='PROPERTY'?'Property details':'Room details · '+(item?.label??'Selected room')}</strong>{record?<><span>{record.shortDescription}</span><span>{record.amenities.length} amenities · {record.reviewStatus.replace('_',' ')} · version {record.version}</span>{record.reviewReason?<span>Review note: {record.reviewReason}</span>:null}</>:<span>No saved content yet.</span>}
   {!admin&&data.canWriteContent&&!draft?<button type="button" onClick={start}>{record?'Edit details':'Add details'}</button>:null}
   {admin&&record?.reviewStatus==='pending_review'&&data.canReviewContent?<div className={styles.actions}><button type="button" disabled={busy} onClick={()=>void decide('approve')}>Approve</button><button type="button" disabled={busy} onClick={()=>void decide('reject')}>Needs changes</button></div>:null}
  </div>
  {draft?<div className={styles.record}><label>Customer-facing {targetScope==='PROPERTY'?'Hotel':'room'} description required<textarea value={draft.shortDescription} maxLength={500} onChange={event=>change({...draft,shortDescription:event.target.value})}/><span className={styles.muted}>{draft.shortDescription.length}/500</span></label><label>Additional description optional<textarea value={draft.detailedDescription} maxLength={2000} onChange={event=>change({...draft,detailedDescription:event.target.value})}/><span className={styles.muted}>{draft.detailedDescription.length}/2000</span></label>
   <h3>Standard amenities</h3>{groups.map(group=><details key={group} open><summary>{group.replaceAll('_',' ').toLowerCase()}</summary><div className={styles.actions}>{catalogue.filter(value=>value.category===group).map(amenity=><label key={amenity.code}><input type="checkbox" checked={draft.amenityCodes.includes(amenity.code)} onChange={()=>toggle(amenity.code,amenity.valueKind,amenity.allowedValues)}/> {amenity.label}{amenity.valueKind==='ENUM'&&draft.amenityCodes.includes(amenity.code)?<select aria-label={amenity.label+' value'} value={draft.structuredValues[amenity.code]??amenity.allowedValues[0]} onChange={event=>change({...draft,structuredValues:{...draft.structuredValues,[amenity.code]:event.target.value}})}>{amenity.allowedValues.map(value=><option key={value} value={value}>{value}</option>)}</select>:null}</label>)}</div></details>)}
   {message?<p role="alert">{message}</p>:null}<div className={styles.actions}><button type="button" className={styles.primaryAction} disabled={busy} onClick={()=>void submit()}>{busy?'Saving…':'Save and send for review'}</button><button type="button" disabled={busy} onClick={()=>{setDraft(null);onDirtyChange?.(false);}}>Cancel</button></div>
  </div>:message?<p role="status">{message}</p>:null}
 </section>;
}
