"use client";
import Link from "next/link";
import {partnerApplicationPreviewHref} from "@/app/lib/partner/partnerSubmittedDestination";
import type { PartnerWorkspace } from "@/app/lib/partner/partnerWorkspace";

export default function PartnerHomeView({data,admin=false}:{data:PartnerWorkspace;admin?:boolean}) {
 const restricted=data.destination==="RESTRICTED";
 return <article className="partner-workspace min-w-0 space-y-6 text-slate-200">
  <header className="border-b border-white/10 pb-5"><p className="text-sm text-slate-400">{admin?"Partner overview":"Partner Home"}</p><h1 className="mt-2 break-words text-2xl font-semibold tracking-tight sm:text-3xl">{data.organization.name}</h1><p className="mt-2 text-sm text-slate-400">{data.organization.type} · {data.organization.location}</p><dl className="mt-5 flex flex-wrap gap-x-8 gap-y-3 text-sm"><div><dt className="text-slate-400">Organization</dt><dd className="mt-1 capitalize">{data.organization.status}</dd></div><div><dt className="text-slate-400">Application</dt><dd className="mt-1 capitalize">{data.application?.status.toLowerCase().replaceAll("_"," ")??"Existing Partner account"}</dd></div>{data.application?<div><dt className="text-slate-400">Reviewed record</dt><dd className="mt-1">Revision {data.application.revision}</dd></div>:null}</dl></header>
  <section><h2 className="font-semibold">Action required</h2>{data.activation.blockers.length?<ul className="mt-3 space-y-2 text-sm text-slate-300">{data.activation.blockers.map(b=><li key={b.code} className="border-l-2 border-amber-400/60 pl-3">{b.label}</li>)}</ul>:<p className="mt-3 text-sm text-slate-400">Your existing organization access is available. Each service has its own setup and permissions.</p>}
   {data.application?<Link className="mt-4 inline-block text-sm text-sky-300 underline print:hidden" href={admin?`/admin/partners/applications/${encodeURIComponent(data.application.id)}`:partnerApplicationPreviewHref(data.organization.id)}>{admin?"Open application review":"View application"}</Link>:null}
  </section>
  {!restricted?<section className="border-t border-white/10 pt-5"><h2 className="font-semibold">Services</h2>{!data.catalogue.available?<p role="status" className="mt-2 text-sm text-amber-200">Current service details are unavailable. Previously saved selections are shown.</p>:null}<div className="mt-3 divide-y divide-white/10">{data.services.map(s=><div key={s.code} className="flex flex-wrap items-start justify-between gap-3 py-4"><div className="min-w-0 flex-1"><h3 className="break-words text-sm font-medium">{s.label}</h3><p className="mt-1 text-xs text-slate-400">{s.domain}</p><details className="mt-2 text-xs text-slate-400"><summary className="cursor-pointer">Service details</summary><p className="mt-2">Application: {s.applicationApproved?"Approved":"Awaiting approval"} · Service: {s.status}</p><p className="mt-1">{s.published?"Available in the published catalogue":"Historical selection; availability needs review"}</p>{s.capabilities.length?<p className="mt-1">Supported features: {s.capabilities.map(c=>c.replaceAll("_"," ")).join(", ")}. Access depends on separate setup.</p>:null}</details></div><span className="rounded-md border border-slate-600 px-2 py-1 text-xs">{s.setupLabel}</span></div>)}{!data.services.length?<p className="py-3 text-sm text-slate-400">No services are selected for this organization.</p>:null}</div></section>:null}
  <section className="border-t border-white/10 pt-5"><h2 className="font-semibold">Operations</h2><p className="mt-3 text-sm text-slate-400">Operational reports will appear as the relevant services become available.</p><p className="mt-2 text-sm text-slate-400">{data.payout.state}</p></section>
  <section className="border-t border-white/10 pt-5"><h2 className="font-semibold">Recent activity</h2>{data.activity.length?<ol className="mt-3 space-y-3 text-sm">{data.activity.map((a,i)=><li key={a.at+":"+i}><span>{a.label}</span><time className="ml-3 text-xs text-slate-400">{new Date(a.at).toLocaleDateString("en-GB",{timeZone:"UTC"})}</time></li>)}</ol>:<p className="mt-3 text-sm text-slate-400">No recent updates to show.</p>}</section>
  {!admin?<Link className="inline-block text-sm text-sky-300 underline print:hidden" href="/customer-support">Contact Partner Support</Link>:null}
  <style>{`@media print{body *:not(:has(.partner-workspace)):not(.partner-workspace):not(.partner-workspace *){display:none!important}body,body *:has(.partner-workspace){display:block!important;height:auto!important;min-height:0!important;margin:0!important;padding:0!important;overflow:visible!important}.partner-workspace{position:static;background:white;padding:0;width:100%;}@page{size:A4;margin:12mm}.partner-workspace{color:#172536!important;font-size:11pt}.partner-workspace *{color:#172536!important}.partner-workspace section{break-inside:avoid}.partner-workspace header{break-after:avoid}}`}</style>
 </article>;
}
