"use client";
import Link from 'next/link';
import {useState} from 'react';
import {Activity,ArrowRight,Bell,Building2,ChevronDown,ChevronRight,CircleHelp,FileText,Grid2X2,Layers,LayoutDashboard,LogOut,Menu,Settings,ShieldCheck,Users,Wallet} from 'lucide-react';
import type {CommandAction,CommandFilters,CommandSection,PartnerCommand} from '@/app/lib/partner/partnerCommand';
import {partnerApplicationPreviewHref} from '@/app/lib/partner/partnerSubmittedDestination';
import PartnerSupplyWorkspace from './PartnerSupplyWorkspace';
import styles from './PartnerCommandCenter.module.css';

type Props={data:PartnerCommand;admin?:boolean;busy?:boolean;onNavigate:(section:CommandSection)=>void;onFilters:(filters:CommandFilters)=>void;onBack?:()=>void;onLogout?:()=>void;onRefresh:()=>void;onExport:(format:'pdf'|'csv'|'xlsx')=>void};
const icon=(section:string)=>section==='home'?LayoutDashboard:section==='business'?Building2:section==='finance'||section==='settlements'?Wallet:section==='services'?Layers:section==='team'?Users:section==='settings'?Settings:section==='compliance'?ShieldCheck:Grid2X2;
export default function PartnerCommandCenterView({data,admin=false,busy=false,onNavigate,onFilters,onBack,onLogout,onRefresh,onExport}:Props){
 const [menu,setMenu]=useState(false),[draft,setDraft]=useState(data.filters);
 const {workspace}=data,section=data.filters.section,nav=data.navigation,has=(id:CommandSection)=>nav.some(n=>n.id===id);
 const navigate=(id:CommandSection)=>{setMenu(false);onNavigate(id);};
 const applicationHref=workspace.application?(admin?`/admin/partners/applications/${encodeURIComponent(workspace.application.id)}`:partnerApplicationPreviewHref(workspace.organization.id)):null;
 function action(a:CommandAction){if(a.target.kind==='section')navigate(a.target.section);else if(a.target.kind==='application'&&applicationHref)window.location.assign(applicationHref);else if(a.target.kind==='support')navigate('support');}
 const panel=(title:string,children:React.ReactNode,destination?:CommandSection)=> <section className={styles.panel}><div className={styles.panelHead}><h2>{title}</h2>{destination?<button className={styles.link} onClick={()=>navigate(destination)}>View <ArrowRight size={13}/></button>:null}</div>{children}</section>;
 const serviceCards=<div className={styles.services}>{workspace.services.map(s=><div className={styles.service} key={s.code}><Layers size={22} color="#327eac"/><strong>{s.label}</strong><small>{s.domain}</small><span className={`${styles.badge} ${!s.operational?styles.pending:''}`}>{s.operational?'Active':s.setupLabel}</span><small style={{marginTop:7}}>Application: {s.applicationApproved?'Approved':'Awaiting approval'}</small>{!s.published?<small>Historical selection</small>:null}</div>)}{!workspace.services.length?<p className={styles.muted}>No selected services match this view.</p>:null}</div>;
 const partnerActions=data.actions.filter(a=>a.owner==='partner'||a.owner==='system'),tplActions=data.actions.filter(a=>a.owner==='tpl');
 const actions=<section className={`${styles.panel} ${styles.actions}`}><div className={styles.panelHead}><h2>Action Required{partnerActions.length?` (${partnerActions.length})`:''}</h2></div>{partnerActions.map(a=><button className={styles.action} key={a.id} onClick={()=>action(a)}><FileText size={16}/><span>{a.label}</span><ChevronRight size={14}/></button>)}{!partnerActions.length?<p className={styles.muted}>No action is required from you.</p>:null}{tplActions.length?<div className={styles.tplQueue}><strong>TPL review</strong>{tplActions.map(a=><span key={a.id}>{a.label}</span>)}</div>:null}</section>;
 const updates=<>{workspace.activity.map((a,i)=><div className={styles.activity} key={a.at+i}><Activity size={16} color="#3980ac"/><p>{a.label}</p><time>{new Date(a.at).toLocaleDateString('en-GB',{timeZone:'UTC'})}</time></div>)}{!workspace.activity.length?<p className={styles.muted}>No updates in this date range.</p>:null}</>;
 const exports=<div className={styles.tools}>{(['pdf','xlsx','csv'] as const).map(f=><button key={f} disabled={busy} onClick={()=>onExport(f)} className={styles.button}>{f.toUpperCase()}</button>)}<button className={styles.button} onClick={()=>window.print()}>Print</button></div>;
 const group=section==='home'?'overview':['services','inventory','rates','media','bookings','orders','leads','appointments','care','fleet','routes','activity-slots','quotes','crm'].includes(section)?'services':['finance','settlements'].includes(section)?'finance':['compliance','integrations'].includes(section)?'compliance':'reports';
 const tabs=[{id:'overview',label:'Overview',section:'home'},{id:'services',label:'Services & Operations',section:'services'},...(has('finance')?[{id:'finance',label:'Finance',section:'finance'}]:[]),{id:'compliance',label:'Compliance & Integrations',section:'compliance'},{id:'reports',label:'Activity & Reports',section:'reports'}];
 const adminNavigation=<nav className={styles.adminDeskNavigation} aria-label="Partner Desk sections"><div className={styles.panelHead}><h2>Partner Desk sections</h2><span className={styles.muted}>Read-only account view</span></div><div className={styles.adminDeskLinks}>{nav.map(n=><button key={n.id} type="button" aria-current={section===n.id?'page':undefined} onClick={()=>navigate(n.id)} title={n.reason}><strong>{n.label}</strong><small>{n.availability==='ready_authorized'?'Ready':n.reason}</small></button>)}</div></nav>;
 return <div className={`${styles.root} ${admin?styles.admin:''}`}>
  {!admin?<aside className={`${styles.sidebar} ${menu?styles.open:''}`} aria-label="Partner navigation"><div className={styles.brand}>TPL<small>PARTNER WORKSPACE</small></div><nav className={styles.nav}>{nav.filter(n=>n.group==='main').map(n=>{const Icon=icon(n.id);return <button key={n.id} aria-current={section===n.id?'page':undefined} aria-description={n.reason} title={n.reason} onClick={()=>navigate(n.id)}><Icon size={17}/><span>{n.label}<small>{n.availability==='ready_authorized'?'Ready':n.reason}</small></span></button>;})}</nav><nav className={`${styles.nav} ${styles.bottom}`}>{nav.filter(n=>n.group==='bottom').map(n=>{const Icon=icon(n.id);return <button key={n.id} aria-current={section===n.id?'page':undefined} aria-description={n.reason} title={n.reason} onClick={()=>navigate(n.id)}><Icon size={17}/><span>{n.label}<small>{n.availability==='ready_authorized'?'Ready':n.reason}</small></span></button>;})}</nav></aside>:null}
  <div className={styles.main}><header className={styles.header}>{!admin?<button className={styles.mobileMenu} aria-label="Toggle Partner navigation" aria-expanded={menu} onClick={()=>setMenu(x=>!x)}><Menu size={21}/></button>:null}<span className={styles.headerTitle}>{admin?'Partner overview':'Partner Command Center'}</span><button onClick={()=>navigate('activity')} aria-label="View account updates"><Bell size={18}/></button><button onClick={()=>navigate('support')} aria-label="Partner help"><CircleHelp size={18}/></button><button onClick={()=>navigate('business')} aria-label="View business profile"><span className={styles.avatar}>{workspace.organization.name.slice(0,1).toUpperCase()}</span></button>{onLogout?<button onClick={onLogout} aria-label="Log out"><LogOut size={17}/></button>:null}</header>
  <div className={styles.body}>{admin?<><nav className={styles.tabs} aria-label="Partner detail views">{tabs.map(t=><button key={t.id} aria-current={group===t.id?'page':undefined} onClick={()=>navigate(t.section as CommandSection)}>{t.label}</button>)}</nav>{adminNavigation}</>:null}
  <div className={styles.context}><button className={styles.business} onClick={()=>onBack?onBack():navigate('business')} aria-label={onBack?'Choose Partner account':'View business profile'}><span className={styles.businessIcon}><Building2 size={24}/></span><span style={{flex:1,minWidth:0}}><strong>{workspace.organization.name}</strong><small>{workspace.organization.type} · {workspace.organization.location}</small></span>{onBack?<ChevronDown size={17}/>:null}</button><section className={styles.health}><div><h2>Account Health</h2><div className={styles.healthItems}><span><i className={`${styles.dot} ${workspace.organization.status==='active'?styles.activeDot:''}`}/>{workspace.organization.status==='active'?'Organization active':workspace.organization.status==='suspended'?'Access restricted':'Setup pending'}</span><span><ShieldCheck size={13}/>{workspace.application?`Application ${workspace.application.status.toLowerCase().replaceAll('_',' ')}`:'Existing Partner account'}</span><span>{workspace.services.filter(s=>s.operational).length} active services</span></div></div><div className={styles.fresh}>Last checked<br/>{new Date(data.freshness.asOf).toLocaleTimeString('en-GB',{timeZone:'UTC',hour:'2-digit',minute:'2-digit'})} UTC</div></section></div>
  <form className={styles.filters} onSubmit={e=>{e.preventDefault();onFilters({...draft,section});}}><label>From<input aria-label="From date" type="date" value={draft.from} onChange={e=>setDraft(x=>({...x,from:e.target.value}))}/></label><label>To<input aria-label="To date" type="date" value={draft.to} onChange={e=>setDraft(x=>({...x,to:e.target.value}))}/></label><label>Domain<select aria-label="Domain" value={draft.domain} onChange={e=>setDraft(x=>({...x,domain:e.target.value,service:''}))}><option value="">All selected domains</option>{data.context.domains.map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select></label><label>Service<select aria-label="Service" value={draft.service} onChange={e=>setDraft(x=>({...x,service:e.target.value}))}><option value="">All selected services</option>{data.context.services.filter(s=>!draft.domain||s.domainId===draft.domain).map(s=><option key={s.code} value={s.code}>{s.label}</option>)}</select></label><label>Location<select aria-label="Business location" value="organization" onChange={()=>{}}>{data.context.branchOptions.map(b=><option key={b.id} value={b.id}>{b.label}</option>)}</select></label><button type="submit">Apply</button><button type="button" onClick={onRefresh}>Refresh</button></form>
  {section==='home'?<><div className={styles.row}><div className={styles.kpis}>{data.metrics.map(m=><button key={m.id} className={styles.kpi} onClick={()=>m.action&&action(m.action)} disabled={!m.action}><div className={styles.kpiLabel}>{m.label}</div><div className={styles.value}>{m.value===null?'—':m.value.toLocaleString('en-IN')}</div><small>{m.state==='ready'?'Current account records':'Not available'}</small></button>)}</div>{actions}</div><div className={styles.row}>{panel('My Domains & Services',serviceCards,'services')}{data.widgets.some(w=>w.id==='integration-health')?panel('Integration status',<div className={styles.empty}>No verified connection is available for this view.</div>,'integrations'):null}</div>{data.widgets.some(w=>w.id==='performance')?<div className={`${styles.row} ${styles.equalRow}`}>{panel('Business Performance',<div className={styles.empty}>Performance reporting is not available yet.</div>,'reports')}{panel('Recent Work',<div className={styles.empty}>A connected work reader is not available for this view.</div>,'reports')}</div>:null}<div className={`${styles.row} ${styles.equalRow}`}>{has('finance')?panel('Money & Settlement',<><p className={styles.muted}>Financial reporting is not available yet. Service activation and payout eligibility are assessed separately.</p><div className={styles.tools}><button className={styles.link} onClick={()=>navigate('finance')}>Finance <ArrowRight size={13}/></button><button className={styles.link} onClick={()=>navigate('settlements')}>Settlements <ArrowRight size={13}/></button></div></>):null}{panel('Messages & Updates',updates,'activity')}</div></>:null}
  {section==='business'?panel('My Business',<><dl className={styles.details}>{[['Legal name',workspace.organization.legalName],['Business type',workspace.organization.type],['Location',workspace.organization.location],['Organization status',workspace.organization.status]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Not provided'}</dd></div>)}</dl>{applicationHref?<Link className={styles.link} style={{marginTop:20}} href={applicationHref}>View application <ArrowRight size={13}/></Link>:null}</>):null}
  {section==='services'?<>{panel('My Domains & Services',serviceCards)}{admin?<PartnerSupplyWorkspace organizationId={workspace.organization.id} admin mode="overview"/>:null}</>:null}
  {section==='compliance'?panel('Compliance',<>{actions}{applicationHref?<Link className={styles.link} style={{marginTop:15}} href={applicationHref}>{admin?'Open application review':'View submitted evidence'} <ArrowRight size={13}/></Link>:null}{admin?<div className={styles.tools}><Link className={styles.link} href="/admin/partners/documents-compliance">Document reviews</Link><Link className={styles.link} href="/admin/partners/agreements">Agreement reviews</Link></div>:null}{has('integrations')?<button className={styles.link} style={{marginTop:15}} onClick={()=>navigate('integrations')}>Integrations <ArrowRight size={13}/></button>:null}</>):null}
  {section==='reports'?<><PartnerSupplyWorkspace organizationId={workspace.organization.id} admin={admin} mode="reports"/>{panel('Activity & Reports',<>{updates}<p className={styles.muted} style={{marginTop:16}}>Export the permitted business, selected services and readiness summary for these filters.</p>{exports}</>)}</>:section==='activity'?panel('Messages & Updates',updates):null}
  {section==='finance'||section==='settlements'?panel(admin?'Finance':section==='finance'?'Finance':'Settlements',<>{admin?<nav className={styles.tabs} aria-label="Finance views"><button aria-current={section==='finance'?'page':undefined} onClick={()=>navigate('finance')}>Transactions</button><button aria-current={section==='settlements'?'page':undefined} onClick={()=>navigate('settlements')}>Settlements</button></nav>:null}<div className={styles.empty}>{section==='finance'?'Transaction reporting is not available for this account.':'Settlement reporting is not available for this account. Bill submission does not confirm payment or settlement.'}</div></>):null}
  {section==='support'?panel('Partner Support',<Link className={styles.button} href="/customer-support">Contact support</Link>):null}
  {section==='inventory'||section==='rates'?<PartnerSupplyWorkspace organizationId={workspace.organization.id} admin={admin} mode="inventory"/>:null}
  {section==='media'?<PartnerSupplyWorkspace organizationId={workspace.organization.id} admin={admin} mode="media"/>:null}
  {!['home','business','services','inventory','rates','media','compliance','reports','activity','finance','settlements','support'].includes(section)?panel(nav.find(n=>n.id===section)?.label??'Partner workspace',<div className={styles.empty}>{section==='care'&&data.careSummary?`${data.careSummary.count} open care cases in the selected creation-date range. ${data.careSummary.finalBillsPending??0} final bills await review. Detailed case operations require separately authorized workflows.`:<><strong>{data.section.message??'This workspace is awaiting its operational connection.'}</strong>{data.section.nextAction?<span className={styles.nextAction}>{data.section.nextAction}</span>:null}</>}</div>):null}
  {admin&&data.configurationIssues.length?<div className={styles.empty} style={{marginTop:16}}>Some configured capabilities are not supported. Review the published service configuration before enabling operations.</div>:null}
  </div></div>
 </div>;
}
