"use client";
import {useEffect,useState} from 'react';
import {emptyPartnerRateDraft,formatPartnerRateAmount,minorToRateAmount,validatePartnerRateDraft,type PartnerRateDraft} from '@/app/lib/partner/partnerRateDraft';
import type {PartnerSupply} from '@/app/lib/partner/partnerSupply';
import styles from './PartnerCommandCenter.module.css';

type Props={data:PartnerSupply;admin:boolean;busy:boolean;save:(body:Record<string,unknown>)=>Promise<void>;refresh:()=>Promise<void>;onDirtyChange?:(dirty:boolean)=>void};
export default function PartnerRateEditor({data,admin,busy,save,refresh,onDirtyChange}:Props){
 const [draft,setDraft]=useState<PartnerRateDraft>(emptyPartnerRateDraft),[editing,setEditing]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const writable=data.canWriteSupply&&!admin&&data.items.length>0,selected=data.items.find(item=>item.id===draft.supplyItemId),availability=data.availability.filter(item=>item.supplyItemId===draft.supplyItemId),dirty=editing&&(Boolean(draft.id)||Boolean(draft.supplyItemId)||Boolean(draft.name)||Boolean(draft.amount)||Boolean(draft.validFrom)||Boolean(draft.validTo));
 useEffect(()=>onDirtyChange?.(dirty),[dirty,onDirtyChange]);useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);useEffect(()=>()=>onDirtyChange?.(false),[onDirtyChange]);
 const change=(next:Partial<PartnerRateDraft>)=>{setDraft(current=>({...current,...next}));setError('');setNotice('');};
 const beginCreate=()=>{setDraft({...emptyPartnerRateDraft(),supplyItemId:data.items[0]?.id??'',name:'Synthetic Base Rate — QA Only'});setEditing(true);setError('');setNotice('');};
 const beginEdit=(rate:PartnerSupply['rates'][number])=>{setDraft({id:rate.id,version:rate.version,supplyItemId:rate.supplyItemId,name:rate.name,amount:minorToRateAmount(rate.baseAmountMinor),validFrom:rate.validFrom,validTo:rate.validTo,status:rate.status as PartnerRateDraft['status']});setEditing(true);setError('');setNotice('');};
 const cancel=()=>{setDraft(emptyPartnerRateDraft());setEditing(false);setError('');};
 async function submit(){const checked=validatePartnerRateDraft(draft,data.ratePolicy.currency,data.ratePolicy.maxAmountMinor);if(!checked.ok){setError(checked.message);return;}try{await save(checked.body);setNotice(draft.id?'Base rate updated.':'Base rate added.');setDraft(emptyPartnerRateDraft());setEditing(false);}catch(e){setError(e instanceof Error?e.message:'The base rate could not be saved. Your entries are still here.');}}
 return <section className={styles.panel} aria-labelledby="partner-rates-title"><div className={styles.panelHead}><div><h2 id="partner-rates-title">Base rates</h2><span className={styles.muted}>Operational base amounts only. Taxes, commission, discounts and final customer pricing are separate.</span></div>{writable&&!editing?<button type="button" className={styles.primaryAction} onClick={beginCreate}>Add base rate</button>:null}</div>
  {notice?<p role="status" className={styles.readyNote}>{notice}</p>:null}
  {data.rates.map(rate=>{const item=data.items.find(value=>value.id===rate.supplyItemId);return <div key={rate.id} className={styles.record}><strong>{rate.name}</strong><span>{item?.label??'Historical inventory'}</span><span>{formatPartnerRateAmount(rate.baseAmountMinor,rate.currency)} · {rate.validFrom} – {rate.validTo}</span><small>{rate.status} · version {rate.version}</small>{writable?<button type="button" onClick={()=>beginEdit(rate)} disabled={busy||editing}>Edit</button>:null}</div>;})}
  {!data.rates.length&&!editing?<div className={styles.empty}>No base rates yet. Add the first supported base amount for this inventory item.</div>:null}
  {editing?<form className={styles.editor} onSubmit={event=>{event.preventDefault();void submit();}}><h3>{draft.id?'Edit base rate':'Add base rate'}</h3><label><span>Inventory item <b>Required</b></span><select aria-label="Rate inventory item" required disabled={Boolean(draft.id)} value={draft.supplyItemId} onChange={event=>change({supplyItemId:event.target.value})}><option value="">Choose inventory</option>{data.items.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><div className={styles.fieldHint}>Total capacity: <strong>{selected?.capacityTotal??'Choose an item'}</strong> · Current availability: <strong>{availability.length?availability.map(value=>`${value.availableCapacity} (${value.startDate} to ${value.endDate})`).join(', '):'No saved range'}</strong></div><label><span>Rate name <b>Required</b></span><input aria-label="Rate name" maxLength={100} required value={draft.name} onChange={event=>change({name:event.target.value})}/></label><label><span>Account currency</span><input aria-label="Account currency" readOnly value={data.ratePolicy.currency}/></label><label><span>Base amount ({data.ratePolicy.currency}) <b>Required</b></span><input aria-label={`Base amount in ${data.ratePolicy.currency}`} inputMode="decimal" placeholder="0.00" required value={draft.amount} onChange={event=>change({amount:event.target.value})}/></label><label><span>Valid from <b>Required</b></span><input aria-label="Rate valid from" type="date" required value={draft.validFrom} onChange={event=>change({validFrom:event.target.value})}/></label><label><span>Valid to <b>Required</b></span><input aria-label="Rate valid to" type="date" required value={draft.validTo} onChange={event=>change({validTo:event.target.value})}/></label><label><span>Rate status <b>Required</b></span><select aria-label="Rate status" value={draft.status} onChange={event=>change({status:event.target.value as PartnerRateDraft['status']})}><option value="draft">Draft</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><p className={styles.fieldHint}>This is a base amount in minor-unit storage. It is not a final customer price and does not include tax, commission, discount or settlement.</p>{error?<p role="alert" className={styles.empty}>{error}{error.includes('changed')?<button type="button" onClick={()=>void refresh()}>Refresh rates</button>:null}</p>:null}<div className={styles.tools}><button type="submit" className={styles.primaryAction} disabled={busy}>{busy?'Saving…':draft.id?'Save base rate':'Add base rate'}</button><button type="button" onClick={cancel} disabled={busy}>Cancel</button></div></form>:null}
  {!writable?<div className={styles.empty}>{admin||!data.canWriteSupply?'Rates are read-only for this account.':'Create inventory before adding a base rate.'}</div>:null}
 </section>;
}
