"use client";
import {useMemo,useState,type FormEvent,type ReactNode} from "react";
import type {PartnerHotelPolicyConfiguration,PartnerSupply} from "@/app/lib/partner/partnerSupply";
import styles from "./PartnerCommandCenter.module.css";

type Draft={id?:string;version?:number;serviceScopeId:string;configuration:PartnerHotelPolicyConfiguration;policyValues:Record<string,boolean|string>;inclusionCodes:string[];exclusionCodes:string[]};
const defaults:PartnerHotelPolicyConfiguration={checkInStart:"14:00",checkInEnd:null,earlyCheckIn:"on_request",checkOutTime:"11:00",lateCheckOut:"on_request",governmentIdRequired:true,acceptedIdCategories:["government_photo_id","passport"],minimumLeadGuestAge:18,localIdAcceptance:"accepted",foreignGuestRequirement:"passport_and_valid_visa",children:"allowed",existingBed:"on_request",extraBed:"on_request",extraGuests:"on_request",maximumGuestsPerRoom:2,pets:"not_allowed",smoking:"non_smoking_property",parties:"not_allowed",visitors:"restricted",visitorStart:"08:00",visitorEnd:"22:00",quietHoursEnabled:true,quietHoursStart:"22:00",quietHoursEnd:"07:00",damageDeposit:"not_required",accessibilityAssistance:"available_on_request",otherRules:"Synthetic staging Hotel rules for QA review only.",additionalPolicyValues:{}};
const corePolicyCodes=new Set(["HOTEL_POLICY_ARRIVAL_DEPARTURE","HOTEL_POLICY_GUEST_ID","HOTEL_POLICY_CHILD_EXTRA_GUEST","HOTEL_POLICY_PETS","HOTEL_POLICY_SMOKING","HOTEL_POLICY_PARTY_VISITOR","HOTEL_POLICY_QUIET_HOURS","HOTEL_POLICY_ACCESSIBILITY_ASSISTANCE","HOTEL_POLICY_DAMAGE_DEPOSIT_DISCLOSURE","HOTEL_POLICY_OTHER_RULES"]);
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());

export default function PartnerHotelPolicyEditor({data,admin,busy,save,review,refresh,onDirtyChange}:{data:PartnerSupply;admin:boolean;busy:boolean;save:(value:Record<string,unknown>)=>Promise<void>;review:(id:string,version:number,decision:"approve"|"reject",reason:string)=>Promise<void>;refresh:()=>Promise<void>;onDirtyChange?:(dirty:boolean)=>void}){
 const profile=data.policyProfiles.find(v=>v.profileCode==="HOTEL_POLICY_PROFILE_V1"),service=data.serviceScopes.find(v=>v.serviceCode===profile?.serviceCode),record=data.policyRecords.find(v=>v.serviceScopeId===service?.id),[draft,setDraft]=useState<Draft|null>(null),[message,setMessage]=useState("");
 const inclusions=useMemo(()=>data.policyCatalogue.filter(v=>v.entityType==="INCLUSION"),[data.policyCatalogue]),exclusions=useMemo(()=>data.policyCatalogue.filter(v=>v.entityType==="EXCLUSION"),[data.policyCatalogue]),additionalPolicies=useMemo(()=>data.policyCatalogue.filter(v=>v.entityType==="POLICY_TEMPLATE"&&!corePolicyCodes.has(v.code)),[data.policyCatalogue]);
 if(!profile||!service)return <section className={styles.panel}><h2>Hotel policies &amp; inclusions</h2><p className={styles.muted}>Policies are not configured for this service.</p></section>;
 const change=(next:Draft)=>{setDraft(next);onDirtyChange?.(true);};
 const config=<K extends keyof PartnerHotelPolicyConfiguration>(key:K,value:PartnerHotelPolicyConfiguration[K])=>draft&&change({...draft,configuration:{...draft.configuration,[key]:value}});
 const begin=()=>change(record?{id:record.id,version:record.version,serviceScopeId:record.serviceScopeId,configuration:{...record.configuration,additionalPolicyValues:record.configuration.additionalPolicyValues??{}},policyValues:{...(record.configuration.additionalPolicyValues??{})},inclusionCodes:record.inclusions.map(v=>v.code),exclusionCodes:record.exclusions.map(v=>v.code)}:{serviceScopeId:service.id,configuration:{...defaults,additionalPolicyValues:{}},policyValues:{},inclusionCodes:[],exclusionCodes:[]});
 const toggle=(kind:"inclusionCodes"|"exclusionCodes",code:string)=>{if(!draft)return;const values=draft[kind],next=values.includes(code)?values.filter(v=>v!==code):[...values,code];change({...draft,[kind]:next});};
 async function submit(event:FormEvent){event.preventDefault();if(!draft)return;if(draft.configuration.quietHoursEnabled&&draft.configuration.quietHoursStart===draft.configuration.quietHoursEnd){setMessage("Quiet-hours start and end must differ.");return;}setMessage("");try{await save(draft);setDraft(null);onDirtyChange?.(false);setMessage("Saved and sent for TPL content review.");}catch(error){setMessage(error instanceof Error?error.message:"Policies could not be saved. Your entries are still here.");}}
 async function decide(decision:"approve"|"reject"){if(!record)return;const reason=prompt(decision==="approve"?"Enter a short approval reason.":"Explain what needs to change.");if(!reason)return;if(!confirm(decision==="approve"?"Approve these exact policies, inclusions and exclusions for the staging Hotel detail?":"Return this exact configuration for changes?"))return;try{await review(record.id,record.version,decision,reason);setMessage(decision==="approve"?"Hotel policies approved for the staging customer detail.":"Hotel policies returned for changes.");}catch(error){setMessage(error instanceof Error?error.message:"The review decision could not be saved.");}}
 return <section className={`${styles.panel} ${styles.contentPanel}`} aria-label="Hotel policies, inclusions and exclusions">
  <div className={styles.panelHead}><div><h2>Hotel policies &amp; what is included</h2><p className={styles.muted}>Structured Hotel rules · {profile.profileCode} · published catalogue v{data.policyCatalogueVersion}. No prices or final payable amount are calculated here.</p></div><button type="button" onClick={()=>void refresh()} disabled={busy}>Refresh</button></div>
  <section className={styles.contentSummary}><div><span className={styles.contentEyebrow}>HOTEL POLICY</span><h3>{service.label}</h3>{record?<p>Check-in {record.configuration.checkInStart} · check-out {record.configuration.checkOutTime} · {record.inclusions.length} included · {record.exclusions.length} not included</p>:<p>No Hotel policies have been saved.</p>}</div><div className={styles.contentStatus}>{record?<><strong>{record.reviewStatus.replaceAll("_"," ")}</strong><span>version {record.version} · catalogue v{record.catalogueVersion}</span></>:<strong>Not started</strong>}</div>{!admin&&data.canWritePolicies&&!draft?<button type="button" className={styles.primaryAction} onClick={begin}>{record?"Edit policies":"Add policies"}</button>:null}{admin&&record?.reviewStatus==="pending_review"&&data.canReviewPolicies?<div className={styles.contentReviewActions}><button type="button" disabled={busy} onClick={()=>void decide("approve")}>Approve</button><button type="button" disabled={busy} onClick={()=>void decide("reject")}>Needs changes</button></div>:null}{record?.reviewReason?<p className={styles.contentReviewNote}>Review note: {record.reviewReason}</p>:null}
   {record?<details className={styles.contentReviewPreview} open={admin&&record.reviewStatus==="pending_review"}><summary>{record.reviewStatus==="approved"?"View approved policies":"View submitted policies"}</summary><PolicyPreview configuration={record.configuration} inclusions={record.inclusions.map(v=>inclusions.find(o=>o.code===v.code)?.label??v.code)} exclusions={record.exclusions.map(v=>exclusions.find(o=>o.code===v.code)?.label??v.code)}/><footer><span>Property scope · version {record.version}</span>{record.reviewStatus==="approved"?<a href={`/hotels/partner-media-preview?organizationId=${encodeURIComponent(data.organizationId)}&serviceScopeId=${encodeURIComponent(service.id)}`} target="_blank" rel="noreferrer">Open customer staging preview</a>:<span>Customer preview remains private until approval.</span>}</footer></details>:null}
  </section>
  {draft?<form className={`${styles.contentEditor} ${styles.policyEditor}`} onSubmit={submit}>
   <div className={styles.contentEditorHeading}><div><span className={styles.contentEyebrow}>EDITING</span><h3>Hotel policies</h3></div><span>{draft.inclusionCodes.length+draft.exclusionCodes.length} structured selections</span></div>
   <PolicyGroup title="Arrival & Departure"><div className={styles.amenityOptions}><TimeField label="Check-in starts" value={draft.configuration.checkInStart} set={v=>config("checkInStart",v)}/><TimeField label="Check-in ends (optional)" value={draft.configuration.checkInEnd??""} set={v=>config("checkInEnd",v||null)}/><SelectField label="Early check-in" value={draft.configuration.earlyCheckIn} values={["not_available","on_request"]} set={v=>config("earlyCheckIn",v as PartnerHotelPolicyConfiguration["earlyCheckIn"])}/><TimeField label="Check-out time" value={draft.configuration.checkOutTime} set={v=>config("checkOutTime",v)}/><SelectField label="Late check-out" value={draft.configuration.lateCheckOut} values={["not_available","on_request"]} set={v=>config("lateCheckOut",v as PartnerHotelPolicyConfiguration["lateCheckOut"])}/></div></PolicyGroup>
   <PolicyGroup title="Guest & ID Rules"><div className={styles.amenityOptions}><Check label="Government ID required" value={draft.configuration.governmentIdRequired} set={v=>config("governmentIdRequired",v)}/><label className={styles.contentField}><span>Minimum lead guest age</span><input type="number" min={18} max={99} value={draft.configuration.minimumLeadGuestAge??""} onChange={e=>config("minimumLeadGuestAge",e.target.value?Number(e.target.value):null)}/></label><SelectField label="Local ID" value={draft.configuration.localIdAcceptance} values={["accepted","on_request","not_configured"]} set={v=>config("localIdAcceptance",v as PartnerHotelPolicyConfiguration["localIdAcceptance"])}/><SelectField label="Foreign guest requirement" value={draft.configuration.foreignGuestRequirement} values={["passport_and_valid_visa","passport","not_configured"]} set={v=>config("foreignGuestRequirement",v as PartnerHotelPolicyConfiguration["foreignGuestRequirement"])}/></div></PolicyGroup>
   <PolicyGroup title="Children & Extra Guests"><div className={styles.amenityOptions}><SelectField label="Children" value={draft.configuration.children} values={["allowed","not_allowed"]} set={v=>config("children",v as PartnerHotelPolicyConfiguration["children"])}/><SelectField label="Existing bed" value={draft.configuration.existingBed} values={["allowed","not_allowed","on_request"]} set={v=>config("existingBed",v as PartnerHotelPolicyConfiguration["existingBed"])}/><SelectField label="Extra bed" value={draft.configuration.extraBed} values={["not_available","on_request"]} set={v=>config("extraBed",v as PartnerHotelPolicyConfiguration["extraBed"])}/><SelectField label="Extra guests" value={draft.configuration.extraGuests} values={["not_allowed","on_request"]} set={v=>config("extraGuests",v as PartnerHotelPolicyConfiguration["extraGuests"])}/><label className={styles.contentField}><span>Maximum guests per room</span><input type="number" min={1} max={Math.max(...data.items.map(v=>v.capacityTotal),1)} value={draft.configuration.maximumGuestsPerRoom} onChange={e=>config("maximumGuestsPerRoom",Number(e.target.value))}/><small>Cannot exceed canonical room capacity.</small></label></div></PolicyGroup>
   <PolicyGroup title="Pets, Smoking, Parties & Visitors"><div className={styles.amenityOptions}><SelectField label="Pets" value={draft.configuration.pets} values={["allowed","not_allowed","on_request"]} set={v=>config("pets",v as PartnerHotelPolicyConfiguration["pets"])}/><SelectField label="Smoking" value={draft.configuration.smoking} values={["non_smoking_property","designated_areas"]} set={v=>config("smoking",v as PartnerHotelPolicyConfiguration["smoking"])}/><SelectField label="Parties" value={draft.configuration.parties} values={["allowed","not_allowed","prior_approval"]} set={v=>config("parties",v as PartnerHotelPolicyConfiguration["parties"])}/><SelectField label="Visitors" value={draft.configuration.visitors} values={["allowed","restricted","not_allowed"]} set={v=>config("visitors",v as PartnerHotelPolicyConfiguration["visitors"])}/>{draft.configuration.visitors==="restricted"?<><TimeField label="Visitor hours start" value={draft.configuration.visitorStart??""} set={v=>config("visitorStart",v||null)}/><TimeField label="Visitor hours end" value={draft.configuration.visitorEnd??""} set={v=>config("visitorEnd",v||null)}/></>:null}</div></PolicyGroup>
   <PolicyGroup title="Quiet Hours & Other Property Rules"><div className={styles.amenityOptions}><Check label="Quiet hours enabled" value={draft.configuration.quietHoursEnabled} set={v=>config("quietHoursEnabled",v)}/>{draft.configuration.quietHoursEnabled?<><TimeField label="Quiet hours start" value={draft.configuration.quietHoursStart??""} set={v=>config("quietHoursStart",v||null)}/><TimeField label="Quiet hours end" value={draft.configuration.quietHoursEnd??""} set={v=>config("quietHoursEnd",v||null)}/></>:null}<SelectField label="Damage deposit disclosure" value={draft.configuration.damageDeposit} values={["not_required","required_disclosure","on_request"]} set={v=>config("damageDeposit",v as PartnerHotelPolicyConfiguration["damageDeposit"])}/><SelectField label="Accessibility assistance" value={draft.configuration.accessibilityAssistance} values={["available_on_request","not_configured"]} set={v=>config("accessibilityAssistance",v as PartnerHotelPolicyConfiguration["accessibilityAssistance"])}/></div><label className={styles.contentField}><span>Other property rules <em>Optional</em></span><textarea rows={4} maxLength={500} value={draft.configuration.otherRules??""} onChange={e=>config("otherRules",e.target.value||null)}/><small>{draft.configuration.otherRules?.length??0}/500 · no HTML or links</small></label></PolicyGroup>
   {additionalPolicies.length?<PolicyGroup title="Additional Published Policies"><div className={styles.amenityOptions}>{additionalPolicies.map(option=><DynamicPolicyField key={option.code} option={option} value={draft.policyValues[option.code]} set={value=>{const next={...draft.policyValues};if(value===undefined)delete next[option.code];else next[option.code]=value;change({...draft,policyValues:next,configuration:{...draft.configuration,additionalPolicyValues:next}});}}/>)}</div><p className={styles.muted}>Published options remain unselected until you configure and submit them for TPL review.</p></PolicyGroup>:null}
   <PolicyGroup title="What’s Included"><OptionList options={inclusions} selected={draft.inclusionCodes} toggle={code=>toggle("inclusionCodes",code)}/></PolicyGroup>
   <PolicyGroup title="What’s Not Included"><OptionList options={exclusions} selected={draft.exclusionCodes} toggle={code=>toggle("exclusionCodes",code)}/></PolicyGroup>
   {message?<p className={styles.contentMessage} role="alert">{message}</p>:null}<div className={styles.contentSubmitBar}><div><strong>Ready to submit?</strong><span>TPL reviews the exact values before customers can see them.</span></div><button type="button" onClick={()=>{setDraft(null);onDirtyChange?.(false);}}>Cancel</button><button type="submit" className={styles.primaryAction} disabled={busy}>{busy?"Saving…":"Save and send for review"}</button></div>
  </form>:message?<p className={styles.readyNote} role="status">{message}</p>:null}
 </section>;
}
function PolicyGroup({title,children}:{title:string;children:ReactNode}){return <details className={styles.amenityGroup} open><summary><span>{title}</span></summary><div className={styles.amenityGroups}>{children}</div></details>}
function TimeField({label:caption,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className={styles.contentField}><span>{caption}</span><input type="time" value={value} onChange={e=>set(e.target.value)}/></label>}
function SelectField({label:caption,value,values,set}:{label:string;value:string;values:string[];set:(v:string)=>void}){return <label className={styles.contentField}><span>{caption}</span><select value={value} onChange={e=>set(e.target.value)}>{values.map(v=><option value={v} key={v}>{label(v)}</option>)}</select></label>}
function Check({label:caption,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <label className={styles.amenityOption}><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/><span>{caption}</span></label>}
function OptionList({options,selected,toggle}:{options:PartnerSupply["policyCatalogue"];selected:string[];toggle:(code:string)=>void}){return <div className={styles.amenityOptions}>{options.map(option=><label className={`${styles.amenityOption} ${selected.includes(option.code)?styles.amenityOptionSelected:""}`} key={option.code}><input type="checkbox" checked={selected.includes(option.code)} onChange={()=>toggle(option.code)}/><span>{option.label}</span></label>)}</div>}
function DynamicPolicyField({option,value,set}:{option:PartnerSupply["policyCatalogue"][number];value:boolean|string|undefined;set:(value:boolean|string|undefined)=>void}){const choices=option.valueType==="BOOLEAN"?["yes","no"]:option.allowedValues;return <label className={styles.contentField}><span>{option.label}</span><select value={value===undefined?"":typeof value==="boolean"?(value?"yes":"no"):value} onChange={event=>{const next=event.target.value;set(!next?undefined:option.valueType==="BOOLEAN"?next==="yes":next)}}><option value="">Not configured</option>{choices.map(choice=><option key={choice} value={choice}>{label(choice)}</option>)}</select>{option.helpText?<small>{option.helpText}</small>:null}</label>}
function PolicyPreview({configuration:c,inclusions,exclusions}:{configuration:PartnerHotelPolicyConfiguration;inclusions:string[];exclusions:string[]}){return <div><strong>Arrival &amp; departure</strong><p>Check-in {c.checkInStart}{c.checkInEnd?`–${c.checkInEnd}`:""}; check-out {c.checkOutTime}. Early check-in: {label(c.earlyCheckIn)}. Late check-out: {label(c.lateCheckOut)}.</p><strong>Guest and property rules</strong><p>Pets: {label(c.pets)} · Smoking: {label(c.smoking)} · Parties: {label(c.parties)} · Visitors: {label(c.visitors)} · Maximum guests per room: {c.maximumGuestsPerRoom}.</p>{c.quietHoursEnabled?<p>Quiet hours: {c.quietHoursStart}–{c.quietHoursEnd}.</p>:null}{c.otherRules?<p>{c.otherRules}</p>:null}{Object.keys(c.additionalPolicyValues??{}).length?<><strong>Additional policies</strong><p>{Object.entries(c.additionalPolicyValues??{}).map(([code,value])=>`${code}: ${String(value)}`).join(", ")}</p></>:null}<strong>What’s included</strong><p>{inclusions.join(", ")||"No structured inclusions selected."}</p><strong>What’s not included</strong><p>{exclusions.join(", ")||"No structured exclusions selected."}</p></div>}
