"use client";
import {useCallback,useEffect,useState} from 'react';
import {CalendarDays,CheckCircle2,Clock3,Hotel,RefreshCcw,Users} from 'lucide-react';
import {getAdminApiBaseUrl,readAdminSession} from '@/app/lib/admin/adminApiClient';
import {getStoredAuthToken,getTplApiBaseUrl,tplApiRequest} from '@/app/lib/api/tplApiClient';
import {validHotelBookingSnapshot,type HotelBookingRecord,type HotelBookingSnapshot,type HotelStayAction} from '@/app/lib/partner/partnerHotelBookings';
import styles from './PartnerCommandCenter.module.css';

export default function PartnerHotelBookingWorkspace({organizationId,admin=false}:{organizationId:string;admin?:boolean}){
 const [data,setData]=useState<HotelBookingSnapshot|null>(null),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[status,setStatus]=useState('ALL'),[search,setSearch]=useState('');
 const base=`/api/v1/${admin?'admin/partners/workspaces':'partner/organizations'}/${encodeURIComponent(organizationId)}/hotel-bookings`;
 const request=useCallback(async<T,>(path:string,method='GET',body?:unknown):Promise<T>=>{if(admin){const token=readAdminSession()?.session.token;if(!token)throw Error('Admin session required.');const response=await fetch(getAdminApiBaseUrl()+path,{method,headers:{Accept:'application/json',Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'}),json=await response.json();if(!response.ok||!json.ok)throw Error(json.error?.message??'Request failed.');return json.data as T;}const result=await tplApiRequest<T>(path,{method:method as 'GET'|'POST',body,headers:method==='POST'?{'X-TPL-Client-Surface':'website'}:undefined});if(!result.ok)throw Error(result.error.message);return result.data;},[admin]);
 const load=useCallback(async()=>{setBusy(true);try{const params=new URLSearchParams({status,search,limit:'25'}),next=await request<HotelBookingSnapshot>(base+'?'+params);if(!validHotelBookingSnapshot(next)||next.organizationId!==organizationId)throw Error('Booking response could not be verified.');setData(next);setSelected(current=>current&&next.bookings.some(v=>v.id===current)?current:next.bookings[0]?.id??null);setMessage('');}catch(error){setMessage(error instanceof Error?error.message:'Hotel bookings could not be loaded.');}finally{setBusy(false);}},[base,organizationId,request,search,status]);
 useEffect(()=>{void load();},[load]);
 async function act(booking:HotelBookingRecord,code:HotelStayAction,label:string){if(!confirm(`${label} for ${booking.bookingRef}? This records an immutable operational event.`))return;setBusy(true);try{await request(`${base}/${encodeURIComponent(booking.id)}/actions`,'POST',{action:code,version:booking.version,idempotencyKey:`website:${booking.id}:${booking.version}:${code}`});await load();setMessage(`${label} saved. All authorized surfaces now read the same canonical state.`);}catch(error){setMessage(error instanceof Error?error.message:'The booking changed. Refresh and try again.');}finally{setBusy(false);}}
 async function download(format:'pdf'|'xlsx'|'csv'){const token=admin?readAdminSession()?.session.token:getStoredAuthToken(),origin=admin?getAdminApiBaseUrl():getTplApiBaseUrl();if(!token)return;const response=await fetch(origin+base+'/export?format='+format,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!response.ok){setMessage('The bounded booking report could not be prepared.');return;}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`hotel-bookings.${format}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const booking=data?.bookings.find(v=>v.id===selected)??null;
 return <div className={`${styles.bookingWorkspace} hotel-m3a-print`}><section className={styles.panel}><div className={styles.panelHead}><div><p className={styles.eyebrow}>HOTEL-M3A · canonical booking operations</p><h2>Hotel booking inbox</h2><p className={styles.muted}>Stay actions never change payment, refund or settlement state.</p></div><button className={styles.button} disabled={busy} onClick={()=>void load()}><RefreshCcw size={15}/> Refresh</button></div>{message?<p role="status" className={styles.readyNote}>{message}</p>:null}<div className={styles.bookingMetrics}>{[['Action required',data?.counts.actionRequired??0],['Upcoming',data?.counts.upcoming??0],['In house',data?.counts.inHouse??0],['Completed',data?.counts.completed??0]].map(([label,value])=><div key={String(label)}><strong>{value}</strong><span>{label}</span></div>)}</div><div className={styles.bookingFilters}><label>Stay status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All bookings</option><option value="CONFIRMED">New / action required</option><option value="PARTNER_ACKNOWLEDGED">Acknowledged</option><option value="READY_FOR_CHECK_IN">Check-in ready</option><option value="CHECKED_IN">In house</option><option value="CHECKED_OUT">Completed</option><option value="NO_SHOW">No-show</option></select></label><label>Booking, guest or room<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search bounded Hotel bookings"/></label></div></section><div className={styles.bookingColumns}><section className={styles.panel} aria-label="Booking list"><h2>Bookings</h2>{data?.bookings.map(item=><button type="button" key={item.id} className={`${styles.bookingRow} ${selected===item.id?styles.bookingSelected:''}`} onClick={()=>setSelected(item.id)}><span><strong>{item.bookingRef}</strong><small>{item.guestDisplayName} · {item.room}</small></span><span><b>{item.status.replaceAll('_',' ')}</b><small>{item.stayStart} → {item.stayEnd}</small></span></button>)}{!data?.bookings.length?<p className={styles.empty}>No Hotel bookings match this authorized view.</p>:null}</section>{booking?<BookingDetail booking={booking} admin={admin} busy={busy} act={act}/>:<section className={styles.panel}><p className={styles.empty}>Choose a booking to view its safe operational detail.</p></section>}</div><section className={`${styles.panel} ${styles.bookingReport}`}><div className={styles.reportHead}><div><h2>Booking operations report</h2><p className={styles.muted}>Safe fields only · {data?.bookings.length??0} bounded record(s)</p></div><aside className={styles.exportPanel}><strong>Download &amp; print</strong><div>{(['pdf','xlsx','csv'] as const).map(format=><button key={format} onClick={()=>void download(format)}>{format.toUpperCase()}</button>)}<button onClick={()=>window.print()}>Print</button></div></aside></div></section></div>;
}
function BookingDetail({booking,admin,busy,act}:{booking:HotelBookingRecord;admin:boolean;busy:boolean;act:(booking:HotelBookingRecord,code:HotelStayAction,label:string)=>void}){return <section className={styles.panel} aria-label="Booking detail"><div className={styles.panelHead}><div><p className={styles.eyebrow}>{booking.syntheticFixture?'SYNTHETIC STAGING BOOKING':'HOTEL BOOKING'}</p><h2>{booking.bookingRef}</h2></div><span className={styles.bookingStatus}>{booking.status.replaceAll('_',' ')}</span></div><div className={styles.bookingFacts}><span><Hotel size={16}/><strong>{booking.room}</strong><small>{booking.hotel} · {booking.service}</small></span><span><CalendarDays size={16}/><strong>{booking.stayStart} → {booking.stayEnd}</strong><small>{booking.nights} nights · {booking.roomCount} room</small></span><span><Users size={16}/><strong>{booking.guestDisplayName}</strong><small>{booking.guestCount.adults} adult · {booking.guestCount.children} children</small></span><span><CheckCircle2 size={16}/><strong>{booking.allocationState}</strong><small>Payment: {booking.paymentDisclosure.replaceAll('_',' ')}</small></span></div><p className={styles.muted}>Version {booking.version} · latest source {booking.lastClientSurface}. Identity documents, payment instruments and private notes are excluded.</p>{!admin&&booking.allowedActions.length?<div className={styles.bookingActions}>{booking.allowedActions.map(item=><button key={item.code} disabled={busy} onClick={()=>act(booking,item.code,item.label)}>{item.label}</button>)}</div>:admin?<p className={styles.empty}>Admin view is read-only. Partner stay actions remain server-authorized.</p>:<p className={styles.empty}>No further stay action is available.</p>}<h3 className={styles.bookingTimelineTitle}><Clock3 size={16}/> Immutable timeline</h3><ol className={styles.bookingTimeline}>{booking.timeline.map(event=><li key={event.id}><strong>{event.toStatus.replaceAll('_',' ')}</strong><span>{event.eventType.replaceAll('.',' · ')} · version {event.version} · {event.clientSurface}</span><time>{new Date(event.at).toLocaleString('en-GB',{timeZone:'UTC'})} UTC</time></li>)}</ol></section>}
