"use client";
import {useEffect,useState,useRef} from 'react';
import {getStoredAuthToken,getTplApiBaseUrl,tplApiRequest} from '@/app/lib/api/tplApiClient';
import {watchVisiblePublication} from '@/app/lib/partner/publishedRefresh';
import {validCommand,type PartnerCommand,type CommandFilters,type CommandSection} from '@/app/lib/partner/partnerCommand';
import PartnerCommandCenterView from './PartnerCommandCenterView';
export default function PartnerHome({organizationId,onBack,onLogout}:{organizationId:string;onBack:()=>void;onLogout?:()=>void}){
 const scope=useRef(organizationId);scope.current=organizationId;
 const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const [record,setRecord]=useState<{key:string;data:PartnerCommand}|null>(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[busy,setBusy]=useState(false);
 const key=organizationId+'?'+query,data=record?.key===key?record.data:null;
 useEffect(()=>{let live=true,pending=false,version=-1;const token=getStoredAuthToken();async function load(){if(!live||pending)return;if(!token||getStoredAuthToken()!==token){setRecord(null);return;}pending=true;try{const result=await tplApiRequest<PartnerCommand>(`/api/v1/partner/organizations/${encodeURIComponent(organizationId)}/command-center?${query}`);if(!live||token!==getStoredAuthToken())return;if(result.ok&&validCommand(result.data)&&result.data.workspace.organization.id===organizationId&&(result.data.freshness.catalogueVersion??version)>=version){version=result.data.freshness.catalogueVersion??version;setRecord({key,data:result.data});setError('');}else{setRecord(null);setError('Your Partner workspace could not be refreshed. Please try again.');}}catch{if(live){setRecord(null);setError('Your Partner workspace could not be refreshed. Please try again.');}}finally{pending=false;}}const stop=watchVisiblePublication(load);const timer=setInterval(()=>{if(token!==getStoredAuthToken()){live=false;setRecord(null);}},1000);return()=>{live=false;stop();clearInterval(timer);};},[organizationId,query,key,refresh]);
 function filters(value:CommandFilters){setQuery(new URLSearchParams(value).toString());}
 function navigate(section:CommandSection){if(data)filters({...data.filters,section});}
 async function download(format:'pdf'|'csv'|'xlsx'){const token=getStoredAuthToken(),org=organizationId;if(!token)return;setBusy(true);try{const response=await fetch(getTplApiBaseUrl()+`/api/v1/partner/organizations/${encodeURIComponent(org)}/command-center/export?${query}&format=${format}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!response.ok)throw Error();const blob=await response.blob();if(!mounted.current||scope.current!==org||token!==getStoredAuthToken())throw Error();const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`partner-workspace.${format}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setError('The export could not be prepared. Refresh and try again.');}finally{setBusy(false);}}
 return <>{error?<p role="alert" className="bg-white p-4 text-slate-800">{error} <button onClick={()=>setRefresh(x=>x+1)}>Refresh</button> <button onClick={onBack}>Back to accounts</button></p>:null}{data?<PartnerCommandCenterView key={key} data={data} busy={busy} onNavigate={navigate} onFilters={filters} onBack={onBack} onLogout={onLogout} onRefresh={()=>setRefresh(x=>x+1)} onExport={f=>void download(f)}/>:!error?<p role="status" className="min-h-screen bg-slate-50 p-8 text-slate-700">Loading Partner Home…</p>:null}</>;
}
