"use client";
import { useEffect,useState,useRef } from "react";
import { getStoredAuthToken,getTplApiBaseUrl,tplApiRequest } from "@/app/lib/api/tplApiClient";
import { watchVisiblePublication } from "@/app/lib/partner/publishedRefresh";
import { validWorkspace,type PartnerWorkspace } from "@/app/lib/partner/partnerWorkspace";
import PartnerHomeView from "./PartnerHomeView";

export default function PartnerHome({organizationId,onBack}:{organizationId:string;onBack:()=>void}) {
 const mounted=useRef(true); useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const [data,setData]=useState<PartnerWorkspace|null>(null),[error,setError]=useState(""),[refresh,setRefresh]=useState(0),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true,pending=false;const token=getStoredAuthToken();setData(null);const load=async()=>{if(pending||!live)return;if(!token||getStoredAuthToken()!==token){setData(null);return;}pending=true;const result=await tplApiRequest<PartnerWorkspace>(`/api/v1/partner/organizations/${encodeURIComponent(organizationId)}/workspace`);pending=false;if(!live||token!==getStoredAuthToken())return;if(result.ok&&validWorkspace(result.data)&&result.data.organization.id===organizationId){setData(result.data);setError("");}else{setData(null);setError("Your Partner workspace could not be loaded. Please refresh or sign in again.");}};const stop=watchVisiblePublication(load);const timer=setInterval(()=>{if(getStoredAuthToken()!==token){live=false;setData(null);}},1000);return()=>{live=false;stop();clearInterval(timer);};},[organizationId,refresh]);
 async function download(format:"pdf"|"csv"|"xlsx"){const token=getStoredAuthToken();if(!token)return;setBusy(true);try{const response=await fetch(getTplApiBaseUrl()+`/api/v1/partner/organizations/${encodeURIComponent(organizationId)}/workspace/export?format=${format}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!response.ok)throw Error();const blob=await response.blob();if(!mounted.current||token!==getStoredAuthToken())throw Error();const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`partner-workspace.${format}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setError("The export could not be prepared. Refresh and try again.");}finally{setBusy(false);}}
 return <div className="mx-auto max-w-5xl space-y-5"><div className="flex flex-wrap gap-3 text-sm print:hidden"><button onClick={onBack} className="rounded border border-slate-600 px-3 py-2">Back to accounts</button><button onClick={()=>setRefresh(x=>x+1)} className="rounded border border-slate-600 px-3 py-2">Refresh</button>{data?["pdf","xlsx","csv"].map(f=><button key={f} disabled={busy} onClick={()=>void download(f as "pdf"|"csv"|"xlsx")} className="rounded border border-slate-600 px-3 py-2 disabled:opacity-50">{f.toUpperCase()}</button>):null}{data?<button onClick={()=>window.print()} className="rounded border border-slate-600 px-3 py-2">Print</button>:null}</div>{error?<p role="alert" className="text-sm text-amber-200">{error}</p>:null}{data?<PartnerHomeView data={data}/>:!error?<p role="status">Loading Partner Home…</p>:null}</div>;
}
