"use client";
import { createTplRequestId,getStoredAuthToken } from "@/app/lib/api/tplApiClient";
import type { CreatorTestingCommerceRecord } from "./creatorEntitlementV1Types";
import type { CreatorDownloadAuthorizationResponse,CreatorDownloadEvent } from "./creatorDownloadTypes";
export type CreatorLibraryTestingPayload={source:"testing_api";testingOnly:true;overview:{orders:number;activeTestingEntitlements:number;licensedAssets:number;activeTestingPlans:number};orders:CreatorTestingCommerceRecord["order"][];entitlements:CreatorTestingCommerceRecord["entitlement"][];certificates:NonNullable<CreatorTestingCommerceRecord["certificate"]>[];downloadHistory:CreatorDownloadEvent[]};
type Payload<T>={ok:boolean;data?:T;error?:{code:string;message:string};meta?:{requestId?:string}};
function headers(body=false,idempotencyKey?:string){const token=getStoredAuthToken();return {Accept:"application/json","X-Request-Id":createTplRequestId("creator_buyer"),...(body?{"Content-Type":"application/json"}:{}),...(token?{Authorization:`Bearer ${token}`} :{}),...(idempotencyKey?{"Idempotency-Key":idempotencyKey}:{})};}
async function get<T>(path:string){const requestId=createTplRequestId("creator_buyer");try{const response=await fetch(path,{cache:"no-store",headers:headers()});const payload=await response.json() as Payload<T>;return payload.ok&&payload.data?{ok:true as const,data:payload.data,requestId:payload.meta?.requestId??requestId}:{ok:false as const,error:payload.error??{code:"INCOMPATIBLE_DTO",message:"Testing data is unavailable."},requestId};}catch{return {ok:false as const,error:{code:"TESTING_API_UNAVAILABLE",message:"Testing data is temporarily unavailable."},requestId};}}
async function post<T>(path:string,body:unknown,idempotencyKey:string){try{const response=await fetch(path,{method:"POST",cache:"no-store",headers:headers(true,idempotencyKey),body:JSON.stringify(body)});const payload=await response.json() as Payload<T>;return payload.ok&&payload.data?{ok:true as const,data:payload.data}:{ok:false as const,error:payload.error??{code:"INCOMPATIBLE_DTO",message:"Testing request failed."}};}catch{return {ok:false as const,error:{code:"TESTING_API_UNAVAILABLE",message:"Testing delivery is temporarily unavailable."}};}}
export const creatorBuyerCommerceClient={
  orders:()=>get<Array<{order:CreatorTestingCommerceRecord["order"];entitlementStatus:string;certificateStatus:string}>>("/api/v1/creator-commerce/orders"),
  order:(id:string)=>get<CreatorTestingCommerceRecord>(`/api/v1/creator-commerce/orders/${encodeURIComponent(id)}`),
  library:()=>get<CreatorLibraryTestingPayload>("/api/v1/creator-commerce/library"),
  entitlement:(id:string)=>get<CreatorTestingCommerceRecord["entitlement"]>(`/api/v1/creator-commerce/entitlements/${encodeURIComponent(id)}`),
  authorizeDownload:(entitlementId:string,assetSlug:string,idempotencyKey:string)=>post<CreatorDownloadAuthorizationResponse>("/api/v1/creator-commerce/downloads/authorize",{entitlementId,assetSlug,fileVariant:"image"},idempotencyKey),
  history:()=>get<{source:"testing_api";testingOnly:true;events:CreatorDownloadEvent[]}>("/api/v1/creator-commerce/downloads/history"),
  async consumeDownload(token:string){const response=await fetch(`/api/v1/creator-commerce/downloads/${encodeURIComponent(token)}`,{cache:"no-store",headers:headers()});if(!response.ok){const payload=await response.json() as Payload<never>;throw new Error(payload.error?.message??"Testing delivery failed.");}const blob=await response.blob();const disposition=response.headers.get("content-disposition")??"";const name=disposition.match(/filename="([^"]+)"/)?.[1]??"tpl-creator-testing-file.txt";const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);},
};
