export type CreatorRouteRecord={key:string;label:string;href:string;routeType:"page"|"category"|"query"|"placeholder";scope:"public"|"studio";authRequired:boolean;creatorStatusRequired:boolean;featureFlag?:string;fallbackHref:string;currentAvailability:"available"|"preview"|"gated";description:string};
const category=(key:string,label:string):CreatorRouteRecord=>({key,label,href:`/creators/categories/${key}`,routeType:"category",scope:"public",authRequired:false,creatorStatusRequired:false,fallbackHref:"/creators/search",currentAvailability:"available",description:`Browse ${label.toLowerCase()} with a meaningful empty state.`});
export const creatorRoutes:CreatorRouteRecord[]=[
 {key:"explore",label:"Explore",href:"/creators",routeType:"page",scope:"public",authRequired:false,creatorStatusRequired:false,fallbackHref:"/creators",currentAvailability:"available",description:"Creator marketplace"},
 ...[["photos","Photos"],["videos","Videos"],["reels","Reels"],["drone","Drone Footage"],["templates","Templates"],["presets","Presets"],["graphics","Graphics"],["destination-guides","Destination Guides"]].map(([k,l])=>category(k,l)),
 {key:"collections",label:"Collections",href:"/creators/collections",routeType:"page",scope:"public",authRequired:false,creatorStatusRequired:false,fallbackHref:"/creators",currentAvailability:"available",description:"Curated collections"},
 {key:"creators",label:"Creators",href:"/creators/authors",routeType:"page",scope:"public",authRequired:false,creatorStatusRequired:false,fallbackHref:"/creators",currentAvailability:"available",description:"Creator directory"},
 {key:"licensing",label:"Licensing",href:"/creators/licensing",routeType:"page",scope:"public",authRequired:false,creatorStatusRequired:false,fallbackHref:"/creators",currentAvailability:"preview",description:"Licensing guidance"},
 {key:"plans",label:"Plans",href:"/creators/plans",routeType:"page",scope:"public",authRequired:false,creatorStatusRequired:false,fallbackHref:"/creators",currentAvailability:"preview",description:"Plan preview"},
 {key:"library",label:"Library",href:"/creators/library",routeType:"page",scope:"public",authRequired:true,creatorStatusRequired:false,fallbackHref:"/creators",currentAvailability:"preview",description:"Buyer library preview"},
 {key:"become",label:"Become a Creator",href:"/creators/become-a-creator",routeType:"page",scope:"public",authRequired:true,creatorStatusRequired:false,fallbackHref:"/creators",currentAvailability:"gated",description:"Creator activation"},
 ...["dashboard","assets","uploads","collections","analytics","revenue","licenses","messages","moderation","payouts","settings"].map(key=>({key:`studio-${key}`,label:key[0].toUpperCase()+key.slice(1),href:key==="dashboard"?"/creator-studio":`/creator-studio/${key}`,routeType:["collections","licenses","payouts"].includes(key)?"placeholder":"page",scope:"studio",authRequired:true,creatorStatusRequired:true,fallbackHref:"/creators/become-a-creator",currentAvailability:["collections","licenses","payouts"].includes(key)?"preview":"available",description:`Creator Studio ${key}`} as CreatorRouteRecord)),
];
export function creatorRoute(key:string){return creatorRoutes.find(item=>item.key===key);}
export function creatorCategoryRoutes(){return creatorRoutes.filter(item=>item.routeType==="category");}
export function creatorStudioRoutes(){return creatorRoutes.filter(item=>item.scope==="studio");}
