import type { CreatorAsset, CreatorCategory, CreatorCollection, CreatorProfile } from "./creatorCatalogTypes";

export const creatorCategories: CreatorCategory[] = [
  {
    slug: "photos",
    title: "Editorial Photos",
    description: "Commercial-ready photography for stories, campaigns and city brands.",
    imageQuery: "premium travel stock photography creator marketplace",
  },
  {
    slug: "videos",
    title: "Stock Footage",
    description: "Cinematic clips, drone shots, reels and b-roll packs.",
    imageQuery: "cinematic travel stock video drone footage",
  },
  {
    slug: "templates",
    title: "Templates",
    description: "Reel, social, presentation, UI and campaign templates.",
    imageQuery: "creative digital templates marketplace design",
  },
  {
    slug: "presets-luts",
    title: "Presets & LUTs",
    description: "Color grades and editing presets for creator workflows.",
    imageQuery: "photo editing presets cinematic LUTs creator",
  },
  {
    slug: "guides",
    title: "Guides & E-books",
    description: "Digital guidebooks, city notes and expert playbooks.",
    imageQuery: "digital travel guide ebook map creator",
  },
  {
    slug: "maps-routes",
    title: "Maps & Route Packs",
    description: "Digital maps, route intelligence and planning assets.",
    imageQuery: "digital route map itinerary creator marketplace",
  },
  {
    slug: "audio",
    title: "Music & Audio",
    description: "Soundtracks, ambient beds and sound effects.",
    imageQuery: "creator music audio waveform marketplace",
  },
  {
    slug: "ai-assets",
    title: "AI Assets",
    description: "Prompt packs, creative systems and AI-ready workflows.",
    imageQuery: "ai prompt pack digital creative asset",
  },
  {
    slug: "bundles",
    title: "Bundles",
    description: "Curated asset packs for launches and campaigns.",
    imageQuery: "digital creator asset bundle marketplace",
  },
];

export const creatorProfiles: CreatorProfile[] = [
  {
    slug: "aira-studio",
    name: "Aira Studio",
    handle: "@aira.studio",
    role: "Cinematic travel studio",
    location: "Mumbai, India",
    bio: "A compact creative studio building destination visuals, cinematic LUTs and campaign-ready motion packs.",
    avatarQuery: "cinematic creator portrait camera studio",
    verified: true,
    rating: 4.9,
    assetCount: 42,
    followersLabel: "18.4k",
    specialties: ["Cinematic video", "LUTs", "Travel campaigns"],
  },
  {
    slug: "routecraft-labs",
    name: "RouteCraft Labs",
    handle: "@routecraft",
    role: "Digital itinerary publisher",
    location: "Bengaluru, India",
    bio: "Route maps, planning kits and digital guides for explorers, creators and destination brands.",
    avatarQuery: "map designer creator desk",
    verified: true,
    rating: 4.8,
    assetCount: 31,
    followersLabel: "11.2k",
    specialties: ["Route packs", "Guides", "Maps"],
  },
  {
    slug: "noor-visuals",
    name: "Noor Visuals",
    handle: "@noorvisuals",
    role: "Editorial photo creator",
    location: "Jaipur, India",
    bio: "Editorial-grade culture, architecture and lifestyle photography with clear usage guidance.",
    avatarQuery: "editorial photographer creator portrait india",
    verified: true,
    rating: 4.7,
    assetCount: 58,
    followersLabel: "24.7k",
    specialties: ["Photos", "Editorial", "Culture"],
  },
  {
    slug: "northlight-motion",
    name: "Northlight Motion",
    handle: "@northlight.motion",
    role: "Aerial and motion studio",
    location: "Manali, India",
    bio: "Mountain aerials, adventure footage and polished vertical edits for modern campaigns.",
    avatarQuery: "outdoor filmmaker portrait mountains camera",
    verified: true,
    rating: 4.9,
    assetCount: 67,
    followersLabel: "29.1k",
    specialties: ["Drone", "4K footage", "Adventure"],
  },
];

const baseCreatorAssets: CreatorAsset[] = [
  {
    id: "asset-001",
    slug: "cinematic-ladakh-drone-pack",
    title: "Cinematic Ladakh Drone Pack",
    subtitle: "12 aerial clips for destination films, reels and launch campaigns.",
    description: "High-altitude roads, blue lakes and mountain passes captured for premium travel edits. Includes graded previews, raw clips and social cutdown guidance.",
    category: "videos",
    subcategory: "Drone footage",
    mediaType: "video",
    creatorSlug: "aira-studio",
    creatorName: "Aira Studio",
    creatorRole: "Cinematic travel studio",
    previewQuery: "ladakh drone footage mountains lake cinematic",
    previewMedia: [
      { id: "ladakh-main", type: "video", title: "Aerial reel preview", previewQuery: "ladakh drone footage mountains lake cinematic" },
      { id: "ladakh-lake", type: "image", title: "Lake still", previewQuery: "pangong lake ladakh cinematic still" },
      { id: "ladakh-road", type: "image", title: "Road still", previewQuery: "ladakh mountain road drone still" },
    ],
    tags: ["Ladakh", "Drone", "Mountains", "Reels"],
    formats: ["MP4", "MOV"],
    orientation: "landscape",
    resolution: "4K",
    dimensions: "4K UHD",
    duration: "4m 30s",
    frameRate: "24 fps",
    fileSize: "2.8 GB",
    software: ["Premiere Pro", "DaVinci Resolve"],
    version: "1.2",
    rating: 4.9,
    reviewCount: 128,
    salesLabel: "2.1k licenses",
    price: 2499,
    currency: "INR",
    licenses: ["personal", "commercial", "extended"],
    licenseOptions: [
      {
        type: "personal",
        price: 2499,
        allowedUse: ["Personal edits", "Portfolio projects", "Non-paid social posts"],
        prohibitedUse: ["Client advertising", "Resale", "Raw file redistribution"],
        seats: "1 user",
        projects: "Personal projects only",
        distribution: "Organic channels",
      },
      {
        type: "commercial",
        price: 5999,
        allowedUse: ["Client campaigns", "Brand social", "Website and presentation use"],
        prohibitedUse: ["Stock resale", "Template bundling", "Broadcast buyout"],
        seats: "3 users",
        projects: "Up to 5 end projects",
        distribution: "Paid and owned digital",
      },
      {
        type: "extended",
        price: 14999,
        allowedUse: ["Large campaigns", "Paid media", "Regional brand launches"],
        prohibitedUse: ["Raw file resale", "Trademark/logo use without clearance"],
        seats: "10 users",
        projects: "Extended campaign use",
        distribution: "High-scale digital and offline",
      },
    ],
    includedFiles: ["12 drone clips", "Edit notes", "Commercial license guide"],
    updatedAt: "2026-06-18",
    copyrightDeclaration: "Creator declares original capture and edit ownership.",
    releaseMetadata: "No private property or model release included; landscape footage only.",
    supportSummary: "Basic file support and replacement download readiness for future entitlement phase.",
    changelog: ["v1.2 added social-safe preview notes", "v1.1 refreshed grade references"],
    collectionSlugs: ["cinematic-india", "creator-launch-kits"],
  },
  {
    id: "asset-002",
    slug: "jaipur-editorial-photo-set",
    title: "Jaipur Editorial Photo Set",
    subtitle: "Royal architecture, bazaars and street textures for editorial use.",
    description: "A warm, high-resolution Jaipur collection built for magazines, blogs, guides and destination storytelling.",
    category: "photos",
    subcategory: "Editorial city photography",
    mediaType: "image",
    creatorSlug: "noor-visuals",
    creatorName: "Noor Visuals",
    creatorRole: "Editorial photo creator",
    previewQuery: "jaipur architecture bazaar editorial photography",
    previewMedia: [
      { id: "jaipur-main", type: "image", title: "Architecture preview", previewQuery: "jaipur palace architecture editorial photography" },
      { id: "jaipur-market", type: "image", title: "Bazaar preview", previewQuery: "jaipur bazaar editorial street photography" },
      { id: "jaipur-texture", type: "image", title: "Texture preview", previewQuery: "jaipur pink city texture editorial photography" },
    ],
    tags: ["Jaipur", "Editorial", "Architecture", "Culture"],
    formats: ["JPG", "TIFF"],
    orientation: "mixed",
    resolution: "24 MP",
    dimensions: "6000 x 4000",
    fileSize: "940 MB",
    version: "1.0",
    rating: 4.7,
    reviewCount: 84,
    salesLabel: "980 licenses",
    price: 1499,
    currency: "INR",
    licenses: ["editorial", "commercial", "extended"],
    licenseOptions: [
      {
        type: "editorial",
        price: 1499,
        allowedUse: ["Editorial articles", "Blogs", "Travel guides"],
        prohibitedUse: ["Product endorsement", "Paid ads", "Merchandise"],
        seats: "1 editorial team",
        projects: "Single editorial project",
        distribution: "Editorial channels",
      },
      {
        type: "commercial",
        price: 3999,
        allowedUse: ["Brand websites", "Social campaigns", "Presentation decks"],
        prohibitedUse: ["Sensitive use", "Resale", "Model endorsement"],
        seats: "3 users",
        projects: "Up to 3 brand projects",
        distribution: "Digital commercial",
      },
      {
        type: "extended",
        price: 9999,
        allowedUse: ["Large campaign use", "Print collateral", "Paid media"],
        prohibitedUse: ["Raw redistribution", "False endorsement"],
        seats: "8 users",
        projects: "Extended campaign use",
        distribution: "Digital and print",
      },
    ],
    includedFiles: ["64 photos", "Caption sheet", "Release notes"],
    updatedAt: "2026-05-27",
    isEditorial: true,
    copyrightDeclaration: "Creator declares original photography ownership.",
    releaseMetadata: "Editorial-first set; commercial use requires buyer review of release needs.",
    supportSummary: "Metadata and caption support readiness.",
    changelog: ["v1.0 initial editorial release"],
    collectionSlugs: ["editorial-city-stories"],
  },
  {
    id: "asset-003",
    slug: "creator-reel-template-kit",
    title: "Creator Reel Template Kit",
    subtitle: "Fast social edits for hotels, experiences and destination drops.",
    description: "A motion template kit with title cards, transitions, lower thirds and export presets for short-form destination storytelling.",
    category: "templates",
    subcategory: "Social video templates",
    mediaType: "template",
    creatorSlug: "aira-studio",
    creatorName: "Aira Studio",
    creatorRole: "Cinematic travel studio",
    previewQuery: "social media reel video template creator kit",
    previewMedia: [
      { id: "reel-main", type: "video", title: "Template motion preview", previewQuery: "social media reel video template creator kit" },
      { id: "reel-title", type: "image", title: "Title card preview", previewQuery: "travel reel title card template" },
      { id: "reel-export", type: "document", title: "Export guide preview", previewQuery: "video template export guide document" },
    ],
    tags: ["Reels", "Templates", "Motion", "Social"],
    formats: ["MOGRT", "AEP", "MP4"],
    orientation: "portrait",
    resolution: "1080p",
    dimensions: "1080 x 1920",
    fileSize: "410 MB",
    software: ["After Effects", "Premiere Pro"],
    version: "2.0",
    rating: 4.8,
    reviewCount: 211,
    salesLabel: "4.6k licenses",
    price: 1999,
    currency: "INR",
    licenses: ["personal", "commercial", "extended"],
    licenseOptions: [
      {
        type: "personal",
        price: 1999,
        allowedUse: ["Personal channels", "Portfolio reels"],
        prohibitedUse: ["Client delivery", "Template resale"],
        seats: "1 user",
        projects: "Personal projects",
        distribution: "Organic social",
      },
      {
        type: "commercial",
        price: 4999,
        allowedUse: ["Client reels", "Brand campaigns", "Agency use"],
        prohibitedUse: ["Template resale", "SaaS embedding"],
        seats: "5 users",
        projects: "Up to 10 projects",
        distribution: "Owned and paid social",
      },
      {
        type: "extended",
        price: 11999,
        allowedUse: ["Agency library", "High-volume campaign use"],
        prohibitedUse: ["Marketplace resale", "Raw template redistribution"],
        seats: "15 users",
        projects: "Extended campaign use",
        distribution: "High-volume digital",
      },
    ],
    includedFiles: ["24 templates", "Font links", "Export presets"],
    updatedAt: "2026-06-02",
    copyrightDeclaration: "Creator declares original template design ownership.",
    releaseMetadata: "No third-party footage included in source template files.",
    supportSummary: "Install and export support readiness.",
    changelog: ["v2.0 added vertical title pack", "v1.5 improved export presets"],
    collectionSlugs: ["creator-launch-kits"],
  },
  {
    id: "asset-004",
    slug: "monsoon-route-map-pack",
    title: "Monsoon Route Map Pack",
    subtitle: "Digital route sheets, safety notes and day-by-day planning maps.",
    description: "Route intelligence for monsoon road trips with map files, printable PDFs and recommended stop sequencing.",
    category: "maps-routes",
    subcategory: "Digital route packs",
    mediaType: "document",
    creatorSlug: "routecraft-labs",
    creatorName: "RouteCraft Labs",
    creatorRole: "Digital itinerary publisher",
    previewQuery: "monsoon travel route map digital itinerary",
    previewMedia: [
      { id: "monsoon-main", type: "document", title: "Route PDF preview", previewQuery: "monsoon travel route map digital itinerary" },
      { id: "monsoon-map", type: "image", title: "Map sheet preview", previewQuery: "digital route map itinerary preview" },
      { id: "monsoon-safety", type: "document", title: "Safety notes preview", previewQuery: "travel safety route notes document" },
    ],
    tags: ["Routes", "Maps", "Monsoon", "Planner"],
    formats: ["PDF", "GPX", "CSV"],
    orientation: "mixed",
    resolution: "Print-ready PDF",
    fileSize: "180 MB",
    version: "1.4",
    rating: 4.8,
    reviewCount: 66,
    salesLabel: "740 licenses",
    price: 999,
    currency: "INR",
    licenses: ["personal", "commercial"],
    licenseOptions: [
      {
        type: "personal",
        price: 999,
        allowedUse: ["Personal trip planning", "Private group use"],
        prohibitedUse: ["Commercial resale", "Public redistribution"],
        seats: "1 user",
        projects: "Personal trips",
        distribution: "Private use",
      },
      {
        type: "commercial",
        price: 2999,
        allowedUse: ["Planner decks", "Creator route planning", "Client itinerary support"],
        prohibitedUse: ["Standalone resale", "Public database replication"],
        seats: "3 users",
        projects: "Up to 5 client plans",
        distribution: "Client deliverables",
      },
    ],
    includedFiles: ["8 map PDFs", "GPX tracks", "Stop database"],
    updatedAt: "2026-06-12",
    copyrightDeclaration: "Creator declares compilation and route-note authorship.",
    releaseMetadata: "Map data is preview-ready; provider-backed live maps are future scope.",
    supportSummary: "Route update support readiness.",
    changelog: ["v1.4 added safety notes", "v1.3 refreshed stop database"],
    collectionSlugs: ["route-packs"],
  },
  {
    id: "asset-005",
    slug: "cinematic-travel-lut-pack",
    title: "Cinematic Travel LUT Pack",
    subtitle: "12 color grades for mountain, desert, beach and city edits.",
    description: "A professional LUT pack tuned for creator travel footage and social campaigns.",
    category: "presets-luts",
    subcategory: "Color grading presets",
    mediaType: "template",
    creatorSlug: "aira-studio",
    creatorName: "Aira Studio",
    creatorRole: "Cinematic travel studio",
    previewQuery: "cinematic color grading LUT travel video",
    previewMedia: [
      { id: "lut-main", type: "image", title: "Grade comparison preview", previewQuery: "cinematic travel LUT before after color grade" },
      { id: "lut-mountain", type: "image", title: "Mountain grade preview", previewQuery: "mountain travel video color grade LUT" },
      { id: "lut-city", type: "image", title: "City grade preview", previewQuery: "city travel video cinematic LUT" },
    ],
    tags: ["LUT", "Color", "Video", "Presets"],
    formats: ["CUBE", "XMP", "PDF"],
    orientation: "mixed",
    resolution: "Editing preset",
    fileSize: "72 MB",
    software: ["DaVinci Resolve", "Premiere Pro", "Lightroom"],
    version: "1.1",
    rating: 4.9,
    reviewCount: 174,
    salesLabel: "3.2k licenses",
    price: 799,
    currency: "INR",
    licenses: ["personal", "commercial", "extended"],
    licenseOptions: [
      {
        type: "personal",
        price: 799,
        allowedUse: ["Personal edits", "Portfolio work"],
        prohibitedUse: ["Preset resale", "Client package resale"],
        seats: "1 user",
        projects: "Personal projects",
        distribution: "Rendered exports only",
      },
      {
        type: "commercial",
        price: 2499,
        allowedUse: ["Client edits", "Brand videos", "Agency use"],
        prohibitedUse: ["Raw preset redistribution", "Template marketplace bundling"],
        seats: "5 users",
        projects: "Commercial projects",
        distribution: "Rendered exports only",
      },
      {
        type: "extended",
        price: 5999,
        allowedUse: ["Agency library", "High-volume production"],
        prohibitedUse: ["Standalone preset resale", "SaaS embedding"],
        seats: "15 users",
        projects: "Extended production use",
        distribution: "Rendered exports only",
      },
    ],
    includedFiles: ["12 LUTs", "Lightroom presets", "Install guide"],
    updatedAt: "2026-04-29",
    copyrightDeclaration: "Creator declares original preset design ownership.",
    releaseMetadata: "No third-party footage included.",
    supportSummary: "Install guide and compatibility support readiness.",
    changelog: ["v1.1 added Lightroom presets", "v1.0 initial LUT release"],
    collectionSlugs: ["creator-launch-kits"],
  },
  {
    id: "asset-006",
    slug: "old-city-food-guide",
    title: "Old City Food Guide",
    subtitle: "A digital food trail guide with timing, etiquette and route notes.",
    description: "A downloadable guide for creator-led food walks, local neighbourhood stories and short-format route planning.",
    category: "guides",
    subcategory: "Digital food guides",
    mediaType: "document",
    creatorSlug: "routecraft-labs",
    creatorName: "RouteCraft Labs",
    creatorRole: "Digital itinerary publisher",
    previewQuery: "old city street food guide digital ebook",
    previewMedia: [
      { id: "food-guide-main", type: "document", title: "Guide preview", previewQuery: "old city street food guide digital ebook" },
      { id: "food-route", type: "image", title: "Route preview", previewQuery: "street food walking route map guide" },
      { id: "food-checklist", type: "document", title: "Checklist preview", previewQuery: "digital food guide checklist document" },
    ],
    tags: ["Food", "Guide", "City", "Local"],
    formats: ["PDF", "EPUB"],
    orientation: "portrait",
    resolution: "Digital guide",
    fileSize: "96 MB",
    version: "1.0",
    rating: 4.6,
    reviewCount: 52,
    salesLabel: "510 licenses",
    price: 599,
    currency: "INR",
    licenses: ["personal", "commercial"],
    licenseOptions: [
      {
        type: "personal",
        price: 599,
        allowedUse: ["Personal reading", "Private trip planning"],
        prohibitedUse: ["Public redistribution", "Paid guide resale"],
        seats: "1 user",
        projects: "Personal use",
        distribution: "Private access",
      },
      {
        type: "commercial",
        price: 1999,
        allowedUse: ["Client planning", "Creator production notes", "Small team reference"],
        prohibitedUse: ["Standalone resale", "Public reposting"],
        seats: "3 users",
        projects: "Up to 5 client plans",
        distribution: "Internal/client reference",
      },
    ],
    includedFiles: ["Guide PDF", "Checklist", "Route notes"],
    updatedAt: "2026-03-16",
    copyrightDeclaration: "Creator declares original writing and route compilation.",
    releaseMetadata: "Business opening times and menus require buyer-side current verification.",
    supportSummary: "Guide errata support readiness.",
    changelog: ["v1.0 initial guide release"],
    collectionSlugs: ["editorial-city-stories", "route-packs"],
  },
];

export const creatorAssets: CreatorAsset[] = [
  ...baseCreatorAssets,
  {
    ...baseCreatorAssets[0]!,
    id: "asset-007",
    slug: "himalayan-sunrise-aerials",
    title: "Himalayan Sunrise Aerials",
    subtitle: "Golden-hour 4K drone sequences across dramatic mountain ridges.",
    description: "A cinematic aerial collection designed for premium films, opening titles and destination campaigns.",
    creatorSlug: "northlight-motion",
    creatorName: "Northlight Motion",
    creatorRole: "Aerial and motion studio",
    previewQuery: "himalayan sunrise drone aerial mountains cinematic",
    previewMedia: [{ id: "himalayan-main", type: "video", title: "Sunrise aerial preview", previewQuery: "himalayan sunrise drone aerial mountains cinematic" }],
    tags: ["himalaya", "sunrise", "drone", "4k"],
    rating: 4.9,
    reviewCount: 196,
    salesLabel: "3.4k licenses",
    price: 2899,
    updatedAt: "2026-07-08",
    collectionSlugs: ["himalayan-aerials", "adventure-pack"],
  },
  {
    ...baseCreatorAssets[1]!,
    id: "asset-008",
    slug: "rajasthan-heritage-portraits",
    title: "Rajasthan Heritage Portraits",
    subtitle: "Editorial portraits, textiles and architectural details from Rajasthan.",
    description: "A carefully documented editorial photo series for publishing, cultural stories and destination features.",
    previewQuery: "rajasthan heritage portrait textiles editorial photography",
    tags: ["rajasthan", "portrait", "heritage", "editorial"],
    rating: 4.8,
    reviewCount: 143,
    salesLabel: "1.8k licenses",
    price: 1799,
    updatedAt: "2026-07-05",
    collectionSlugs: ["rajasthan-heritage", "incredible-india"],
  },
  {
    ...baseCreatorAssets[2]!,
    id: "asset-009",
    slug: "luxury-resort-reel-templates",
    title: "Luxury Resort Reel Templates",
    subtitle: "Elegant vertical video templates for premium hospitality stories.",
    description: "A refined motion template system with title cards, transitions and social-safe export presets.",
    previewQuery: "luxury resort vertical reel video template tropical",
    tags: ["luxury", "resort", "reels", "vertical"],
    rating: 4.9,
    reviewCount: 267,
    salesLabel: "4.6k licenses",
    price: 2299,
    updatedAt: "2026-07-09",
    collectionSlugs: ["luxury-travel-reels", "social-travel-templates"],
  },
  {
    ...baseCreatorAssets[3]!,
    id: "asset-010",
    slug: "tropical-island-route-pack",
    title: "Tropical Island Route Pack",
    subtitle: "Editable island maps, day plans and visual route sheets.",
    description: "A polished planning and publishing kit for tropical destination content and editorial itineraries.",
    previewQuery: "tropical island map route travel digital guide",
    tags: ["tropical", "island", "maps", "routes"],
    rating: 4.7,
    reviewCount: 88,
    salesLabel: "940 licenses",
    price: 699,
    updatedAt: "2026-06-28",
    collectionSlugs: ["tropical-destinations", "adventure-pack"],
  },
  {
    ...baseCreatorAssets[4]!,
    id: "asset-011",
    slug: "urban-night-mobile-presets",
    title: "Urban Night Mobile Presets",
    subtitle: "Moody one-tap grades for city nights, neon and street scenes.",
    description: "A mobile-first preset pack tuned for low-light travel photography and short-form social content.",
    creatorSlug: "noor-visuals",
    creatorName: "Noor Visuals",
    creatorRole: "Editorial photo creator",
    previewQuery: "urban india night neon street photography preset",
    tags: ["urban", "night", "mobile", "presets"],
    rating: 4.8,
    reviewCount: 319,
    salesLabel: "5.1k licenses",
    price: 399,
    updatedAt: "2026-07-10",
    collectionSlugs: ["urban-india", "social-travel-templates"],
  },
  {
    ...baseCreatorAssets[5]!,
    id: "asset-012",
    slug: "india-adventure-content-kit",
    title: "India Adventure Content Kit",
    subtitle: "Story prompts, graphic overlays and field-production checklists.",
    description: "A practical digital bundle for adventure filmmakers and social teams working across fast-moving trips.",
    creatorSlug: "northlight-motion",
    creatorName: "Northlight Motion",
    creatorRole: "Aerial and motion studio",
    previewQuery: "india adventure travel content kit graphics checklist",
    tags: ["adventure", "graphics", "content kit", "social"],
    rating: 4.7,
    reviewCount: 74,
    salesLabel: "780 licenses",
    price: 899,
    updatedAt: "2026-07-02",
    collectionSlugs: ["adventure-pack", "incredible-india"],
  },
];

export const creatorCollections: CreatorCollection[] = [
  {
    slug: "creator-launch-kits",
    title: "Creator Launch Kits",
    description: "Templates, LUTs and footage for fast campaign publishing.",
    coverQuery: "creator digital launch kit templates footage",
    curator: "TPL Editorial",
    assetSlugs: ["cinematic-ladakh-drone-pack", "creator-reel-template-kit", "cinematic-travel-lut-pack"],
  },
  {
    slug: "cinematic-india",
    title: "Cinematic India",
    description: "Video and photo assets for premium destination films.",
    coverQuery: "cinematic india travel film creator assets",
    curator: "TPL Visual Desk",
    assetSlugs: ["cinematic-ladakh-drone-pack", "jaipur-editorial-photo-set"],
  },
  {
    slug: "editorial-city-stories",
    title: "Editorial City Stories",
    description: "City culture, street, food and architecture assets.",
    coverQuery: "editorial city story photography food culture",
    curator: "TPL Culture Desk",
    assetSlugs: ["jaipur-editorial-photo-set", "old-city-food-guide"],
  },
  {
    slug: "route-packs",
    title: "Route Packs",
    description: "Maps, guidebooks and planning files for digital itineraries.",
    coverQuery: "digital route pack travel map guide",
    curator: "TPL Planner Desk",
    assetSlugs: ["monsoon-route-map-pack", "old-city-food-guide"],
  },
  {
    slug: "incredible-india",
    title: "Incredible India",
    description: "A broad visual library spanning landscapes, culture and modern city stories.",
    coverQuery: "incredible india travel photography cinematic collection",
    curator: "TPL Editorial",
    assetSlugs: ["cinematic-ladakh-drone-pack", "rajasthan-heritage-portraits", "india-adventure-content-kit"],
  },
  {
    slug: "himalayan-aerials",
    title: "Himalayan Aerials",
    description: "High-altitude drone footage and mountain establishing shots.",
    coverQuery: "himalayan drone aerial cinematic collection",
    curator: "TPL Motion Desk",
    assetSlugs: ["cinematic-ladakh-drone-pack", "himalayan-sunrise-aerials"],
  },
  {
    slug: "luxury-travel-reels",
    title: "Luxury Travel Reels",
    description: "Polished motion templates and visual assets for premium hospitality.",
    coverQuery: "luxury travel resort reel collection",
    curator: "TPL Design Desk",
    assetSlugs: ["luxury-resort-reel-templates", "cinematic-travel-lut-pack"],
  },
  {
    slug: "rajasthan-heritage",
    title: "Rajasthan Heritage",
    description: "Editorial architecture, portraits and cultural details.",
    coverQuery: "rajasthan heritage editorial photo collection",
    curator: "TPL Culture Desk",
    assetSlugs: ["jaipur-editorial-photo-set", "rajasthan-heritage-portraits"],
  },
  {
    slug: "tropical-destinations",
    title: "Tropical Destinations",
    description: "Island routes, coastal visuals and sunlit campaign assets.",
    coverQuery: "tropical destination island travel collection",
    curator: "TPL Visual Desk",
    assetSlugs: ["tropical-island-route-pack", "luxury-resort-reel-templates"],
  },
  {
    slug: "urban-india",
    title: "Urban India",
    description: "Contemporary city photography, street textures and night grades.",
    coverQuery: "urban india city night photography collection",
    curator: "TPL City Desk",
    assetSlugs: ["jaipur-editorial-photo-set", "urban-night-mobile-presets"],
  },
  {
    slug: "adventure-pack",
    title: "Adventure Pack",
    description: "Aerial footage, route assets and field-ready creator resources.",
    coverQuery: "adventure travel drone content pack collection",
    curator: "TPL Adventure Desk",
    assetSlugs: ["himalayan-sunrise-aerials", "tropical-island-route-pack", "india-adventure-content-kit"],
  },
  {
    slug: "social-travel-templates",
    title: "Social Travel Templates",
    description: "Reels, presets and graphics optimized for fast social publishing.",
    coverQuery: "social travel templates reels presets collection",
    curator: "TPL Social Desk",
    assetSlugs: ["creator-reel-template-kit", "luxury-resort-reel-templates", "urban-night-mobile-presets"],
  },
];
