import { creatorTestingDeliveryProvider } from "./creatorAssetDeliveryProvider";
import type { CreatorDownloadAuthorization,CreatorDownloadEvent } from "./creatorDownloadTypes";
import { readCreatorTestingStore } from "./creatorTestingCommerceRepository";

export type CreatorReconciliationIssue={code:string;resourceId:string;severity:"warning"|"error";repairable:boolean;message:string};
export type CreatorReconciliationReport={mode:"dry_run";checkedAt:string;issues:CreatorReconciliationIssue[];summary:{records:number;authorizations:number;events:number;errors:number;warnings:number};providerHealth:ReturnType<typeof creatorTestingDeliveryProvider.health>};

export function reconcileCreatorTestingDelivery():CreatorReconciliationReport{
  const data=readCreatorTestingStore(),authorizations=(data.downloads??[]) as CreatorDownloadAuthorization[],events=(data.downloadEvents??[]) as CreatorDownloadEvent[],issues:CreatorReconciliationIssue[]=[];
  const eventIds=new Set<string>();
  for(const event of events){if(eventIds.has(event.eventId))issues.push({code:"DUPLICATE_EVENT",resourceId:event.eventId,severity:"error",repairable:false,message:"Duplicate testing download event detected."});eventIds.add(event.eventId);const record=data.records.find(item=>item.entitlement.entitlementId===event.entitlementId);if(!record)issues.push({code:"EVENT_WITHOUT_ENTITLEMENT",resourceId:event.eventId,severity:"error",repairable:false,message:"Download event has no matching testing entitlement."});}
  for(const authorization of authorizations){if(authorization.status==="consumed_testing"&&!events.some(event=>event.authorizationId===authorization.authorizationId))issues.push({code:"CONSUMED_WITHOUT_EVENT",resourceId:authorization.authorizationId,severity:"error",repairable:false,message:"Consumed authorization has no successful history event."});if(authorization.status==="authorized_testing"&&new Date(authorization.expiresAt).getTime()<=Date.now())issues.push({code:"STALE_AUTHORIZATION",resourceId:authorization.authorizationId,severity:"warning",repairable:true,message:"Authorization is expired but still carries an authorized testing state."});const record=data.records.find(item=>item.entitlement.entitlementId===authorization.entitlementId);if(record&&["revoked_testing","refunded_testing","suspended_testing","expired_testing"].includes(record.entitlement.status)&&authorization.status==="authorized_testing")issues.push({code:"BLOCKED_ENTITLEMENT_ACTIVE_TOKEN",resourceId:authorization.authorizationId,severity:"error",repairable:true,message:"Blocked entitlement retains an outstanding token."});}
  for(const record of data.records){if(record.entitlement.downloadsRemaining<0)issues.push({code:"NEGATIVE_ALLOWANCE",resourceId:record.entitlement.entitlementId,severity:"error",repairable:false,message:"Testing allowance is negative."});if(!["testing_confirmed","confirmed_testing"].includes(record.order.orderStatus)&&record.entitlement.status==="active_testing")issues.push({code:"ENTITLEMENT_WITHOUT_CONFIRMED_ORDER",resourceId:record.entitlement.entitlementId,severity:"error",repairable:false,message:"Active testing entitlement lacks a confirmed testing order."});}
  const health=creatorTestingDeliveryProvider.health();if(!health.fixtureSelfCheck)issues.push({code:"FIXTURE_SELF_CHECK_FAILED",resourceId:"testing-registry",severity:"error",repairable:false,message:"One or more deterministic fixtures failed validation."});
  return {mode:"dry_run",checkedAt:new Date().toISOString(),issues,summary:{records:data.records.length,authorizations:authorizations.length,events:events.length,errors:issues.filter(item=>item.severity==="error").length,warnings:issues.filter(item=>item.severity==="warning").length},providerHealth:health};
}
