import { createHash } from "node:crypto";
import { validateTestingFixture,type TestingFixtureKind,type TestingFixturePolicy } from "./creatorTestingFixtureValidation";
export type TestingFileVariant="image"|"video-placeholder"|"template-placeholder"|"preset-placeholder"|"guide-placeholder";
export type CreatorTestingObject={reference:string;variant:TestingFileVariant;fileName:string;contentType:string;bytes:Uint8Array;checksum:string;deliveryMode:"testing_private_fixture";format:TestingFixtureKind};
const bytes=(value:string)=>new Uint8Array(Buffer.from(value,"binary"));
const png=()=>new Uint8Array(Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6ZQAAAABJRU5ErkJggg==","base64"));
const mp4=()=>bytes("\x00\x00\x00\x18ftypisom\x00\x00\x02\x00isomiso2");
function crc32(input:Uint8Array){let crc=0xffffffff;for(const byte of input){crc^=byte;for(let j=0;j<8;j++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
function zip(name:string,content:string){const nameBytes=Buffer.from(name),data=Buffer.from(content),header=Buffer.alloc(30),central=Buffer.alloc(46),end=Buffer.alloc(22),crc=crc32(data);header.writeUInt32LE(0x04034b50,0);header.writeUInt16LE(20,4);header.writeUInt32LE(crc,14);header.writeUInt32LE(data.length,18);header.writeUInt32LE(data.length,22);header.writeUInt16LE(nameBytes.length,26);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt32LE(crc,16);central.writeUInt32LE(data.length,20);central.writeUInt32LE(data.length,24);central.writeUInt16LE(nameBytes.length,28);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(1,8);end.writeUInt16LE(1,10);end.writeUInt32LE(central.length+nameBytes.length,12);end.writeUInt32LE(header.length+nameBytes.length+data.length,16);return new Uint8Array(Buffer.concat([header,nameBytes,data,central,nameBytes,end]));}
const pdf=()=>new Uint8Array(Buffer.from("%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\ntrailer<</Root 1 0 R>>\n%%EOF\n"));
const xmp=()=>new Uint8Array(Buffer.from('<?xpacket begin=""?>\n<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/></x:xmpmeta>\n<?xpacket end="w"?>'));
const generated:Record<TestingFileVariant,{fileName:string;contentType:string;format:TestingFixtureKind;build:()=>Uint8Array}>={
  image:{fileName:"tpl-creator-testing-image.png",contentType:"image/png",format:"png",build:png},
  "video-placeholder":{fileName:"tpl-creator-testing-video.mp4",contentType:"video/mp4",format:"mp4",build:mp4},
  "template-placeholder":{fileName:"tpl-creator-testing-template.zip",contentType:"application/zip",format:"zip",build:()=>zip("README.txt","TPL Creator deterministic safe template fixture.\n")},
  "preset-placeholder":{fileName:"tpl-creator-testing-preset.xmp",contentType:"application/rdf+xml",format:"xmp",build:xmp},
  "guide-placeholder":{fileName:"tpl-creator-testing-guide.pdf",contentType:"application/pdf",format:"pdf",build:pdf},
};
const sha=(value:Uint8Array)=>createHash("sha256").update(value).digest("hex");
function object(variant:TestingFileVariant):CreatorTestingObject{const spec=generated[variant],value=spec.build(),checksum=sha(value);const policy:TestingFixturePolicy={kind:spec.format,extension:`.${spec.fileName.split(".").pop()}`,contentType:spec.contentType,maxBytes:256_000,checksum};const result=validateTestingFixture(value,spec.fileName,spec.contentType,policy);if(!result.ok)throw new Error(result.code??"FIXTURE_VALIDATION_FAILED");return {reference:`testing-registry:${variant}:${checksum.slice(0,16)}`,variant,fileName:spec.fileName,contentType:spec.contentType,bytes:value,checksum,deliveryMode:"testing_private_fixture",format:spec.format};}
export type CreatorDeliveryHealth={status:"testing_ready"|"testing_degraded";providerMode:"testing_private_fixture";fixtureRegistryLoaded:boolean;fixtureSelfCheck:boolean;deliveryEnabled:boolean;productionPrivateObjectEnabled:false;lastSafeSelfCheck:string;warnings:string[]};
export interface CreatorAssetDeliveryProvider{authorizeObject(variant:TestingFileVariant):CreatorTestingObject;getObjectMetadata(reference:string):Omit<CreatorTestingObject,"bytes">|null;createTemporaryDelivery(reference:string):CreatorTestingObject|null;consumeTemporaryDelivery(reference:string):CreatorTestingObject|null;revokeTemporaryDelivery(reference:string):boolean;health():CreatorDeliveryHealth;}
export const creatorTestingDeliveryProvider:CreatorAssetDeliveryProvider={authorizeObject:object,getObjectMetadata(reference){const value=this.createTemporaryDelivery(reference);if(!value)return null;const {bytes:_,...meta}=value;void _;return meta;},createTemporaryDelivery(reference){if(!reference.startsWith("testing-registry:"))return null;const variant=reference.split(":")[1] as TestingFileVariant;if(!(variant in generated)||variant.includes("/")||variant.includes(".."))return null;const value=object(variant);return reference===value.reference?value:null;},consumeTemporaryDelivery(reference){return this.createTemporaryDelivery(reference);},revokeTemporaryDelivery(reference){return this.createTemporaryDelivery(reference)!==null;},health(){let fixtureSelfCheck=true;try{for(const variant of Object.keys(generated) as TestingFileVariant[])object(variant);}catch{fixtureSelfCheck=false;}return {status:fixtureSelfCheck?"testing_ready":"testing_degraded",providerMode:"testing_private_fixture",fixtureRegistryLoaded:true,fixtureSelfCheck,deliveryEnabled:true,productionPrivateObjectEnabled:false,lastSafeSelfCheck:new Date().toISOString(),warnings:["Synthetic fixtures only","Production object delivery disabled"]};}};
export function creatorTestingVariant(input:string):TestingFileVariant|null{return input in generated?input as TestingFileVariant:null;}
