import type { CreatorCommerceOrderDTO,CreatorCommerceProductType } from "./creatorCommerceTypes";
export const CREATOR_ENTITLEMENT_VERSION="creator-entitlement.v1" as const;
export const CREATOR_CERTIFICATE_VERSION="creator-license-certificate.v1" as const;
export type CreatorTestingEntitlementStatus="pending_testing"|"active_testing"|"exhausted_testing"|"expired_testing"|"suspended_testing"|"revoked_testing"|"refund_pending_testing"|"refunded_testing";
export type CreatorPlanAllowance={monthlyAllowance:number;annualAllowance:number;downloadsUsed:number;downloadsRemaining:number;resetDate:string;rolloverAllowed:false;eligibleAssetTypes:string[];standardLicenseIncluded:boolean;extendedLicenseDiscountPreview:string};
export type CreatorEntitlementV1={version:typeof CREATOR_ENTITLEMENT_VERSION;entitlementId:string;orderId:string;checkoutId:string;buyerId:string;productType:CreatorCommerceProductType;assetId?:string;assetSlug?:string;planId?:string;creatorId?:string;creatorSlug?:string;licenseType?:"standard"|"extended";licenseVersion:string;usageRightsSnapshot:{allowedUses:string[];prohibitedUses:string[];territory:string;duration:string;commercialEditorialPosition:string;modelReleaseStatus:string;propertyReleaseStatus:string;assetVersion:string;creatorIdentity:Record<string,unknown>;buyerIdentity:Record<string,unknown>};status:CreatorTestingEntitlementStatus;source:"testing_api";validFrom:string;validUntil:string|null;downloadAllowance:number;downloadsUsed:number;downloadsRemaining:number;planAllowance?:CreatorPlanAllowance;certificateStatus:"preview_generated"|"not_applicable";invoiceStatus:"not_generated"|"preview_available"|"pending_production_generation";revocationReason:string|null;requestId:string;createdAt:string;updatedAt:string;downloadAllowed:false};
export type CreatorLicenseCertificateV1={version:typeof CREATOR_CERTIFICATE_VERSION;certificateId:string;entitlementId:string;orderId:string;asset:{id?:string;slug?:string;title:string};creator:{id?:string;slug?:string};buyer:{id:string};licenseType:"standard"|"extended";licenseVersion:string;issueDate:string;testingVerificationCode:string;status:"preview_generated"|"pending_production_generation"|"revoked_testing";source:"testing_api";productionValid:false};
export type CreatorTestingCommerceRecord={order:CreatorCommerceOrderDTO;entitlement:CreatorEntitlementV1;certificate?:CreatorLicenseCertificateV1;timeline:Array<{status:string;at:string}>};
export type CreatorTestingStoreData={version:"creator-testing-store.v1";records:CreatorTestingCommerceRecord[];downloads?:unknown[];downloadEvents?:unknown[];downloadAudits?:unknown[];downloadIdempotency?:Record<string,string>;downloadRateLimits?:Record<string,{windowStartedAt:number;count:number}>;updatedAt:string};
