import type { CreatorDataSource } from "./creatorDataSource";

export const CREATOR_COMMERCE_CHECKOUT_VERSION = "creator-commerce-checkout.v1" as const;
export const CREATOR_COMMERCE_ORDER_VERSION = "creator-commerce-order.v1" as const;
export type CreatorCommerceProductType = "creator_plan" | "creator_asset_standard_license" | "creator_asset_extended_license" | "creator_enterprise_inquiry";
export type CreatorCommerceStatus = "draft" | "ready" | "payment_pending" | "payment_started" | "payment_processing" | "payment_succeeded" | "payment_failed" | "cancelled" | "expired" | "confirmation_pending";
export type CreatorCommerceSelection = { productType: CreatorCommerceProductType; planId?: string; assetSlug?: string; billingCycle?: "monthly" | "yearly"; context?: Record<string, string> };
export type CreatorCommerceItem = { id:string; productType:CreatorCommerceProductType; assetId?:string; assetSlug?:string; planId?:string; licenseType?:"standard"|"extended"; title:string; creatorId?:string; creatorSlug?:string; quantity:1; currency:"INR"; baseAmount:number; taxAmount:number; platformFee:number; gatewayFee:number; totalAmount:number; billingCycle?:"monthly"|"yearly"; licenseVersion?:string; usageRightsSnapshot:string[]; thumbnail?:string; source:CreatorDataSource; metadata:Record<string,unknown> };
export type CreatorCommerceCheckoutDTO = { version:typeof CREATOR_COMMERCE_CHECKOUT_VERSION; checkoutId:string; userId:string; productType:CreatorCommerceProductType; items:CreatorCommerceItem[]; subtotal:number; taxAmount:number; platformFee:number; gatewayFee:number; totalAmount:number; currency:"INR"; billingCycle?:"monthly"|"yearly"; licenseSnapshot?:Record<string,unknown>; planSnapshot?:Record<string,unknown>; creatorSnapshot?:Record<string,unknown>; source:CreatorDataSource; status:CreatorCommerceStatus; requestId:string; idempotencyKey:string; createdAt:string; expiresAt:string; safety:{testingOnly:true;realGatewayAllowed:false;walletCreditsApplied:false;entitlementActivationAllowed:false;downloadAllowed:false} };
export type CreatorCommerceOrderDTO = { version:typeof CREATOR_COMMERCE_ORDER_VERSION; orderId:string; checkoutId:string; buyerId:string; productType:CreatorCommerceProductType; items:CreatorCommerceItem[]; amounts:{subtotal:number;taxAmount:number;platformFee:number;gatewayFee:number;totalAmount:number}; currency:"INR"; paymentStatus:"testing_succeeded"|"testing_failed"|"testing_pending"; orderStatus:"draft"|"payment_pending"|"payment_processing"|"paid_testing"|"confirmation_pending"|"testing_confirmed"|"confirmed_testing"|"payment_failed"|"failed"|"cancelled"|"expired"|"refunded_testing"|"revoked_testing"; entitlementStatus:"pending_testing"; invoiceStatus:"not_generated"|"preview_available"|"pending_production_generation"; licenseCertificateStatus:"not_generated"|"preview_generated"|"pending_production_generation"; createdAt:string; updatedAt:string; requestId:string };
export type CreatorCommerceErrorCode = "COMMERCE_DISABLED"|"AUTH_REQUIRED"|"INVALID_PLAN"|"INVALID_ASSET"|"UNAVAILABLE_LICENSE"|"INVALID_AMOUNT"|"AMOUNT_MISMATCH"|"CHECKOUT_EXPIRED"|"CHECKOUT_NOT_FOUND"|"PAYMENT_FAILED"|"PAYMENT_NOT_SUCCESSFUL"|"ORDER_NOT_FOUND"|"ORDER_NOT_OWNED"|"ENTITLEMENT_NOT_FOUND"|"CERTIFICATE_UNAVAILABLE"|"INVALID_TRANSITION"|"ENTITLEMENT_REVOKED"|"ENTITLEMENT_EXPIRED"|"ENTITLEMENT_PENDING"|"ALLOWANCE_EXHAUSTED"|"ORDER_NOT_CONFIRMED"|"OBJECT_UNAVAILABLE"|"UNSUPPORTED_FILE_VARIANT"|"AUTHORIZATION_EXPIRED"|"AUTHORIZATION_CONSUMED"|"AUTHORIZATION_REVOKED"|"TOKEN_INVALID"|"DELIVERY_DISABLED"|"PERSISTENCE_UNAVAILABLE"|"RATE_LIMITED"|"IDEMPOTENCY_CONFLICT"|"INCOMPATIBLE_DTO";
export type CreatorCommerceResult<T> = {ok:true;data:T;requestId:string;source:"testing_api"}|{ok:false;error:{code:CreatorCommerceErrorCode;message:string};requestId:string};
