import type { CreatorAuthorProfile, CreatorDirectoryStat } from "./creatorAuthorPageTypes";

export const creatorDirectoryStats: CreatorDirectoryStat[] = [
  { label: "Total Creators", value: "2,400+" }, { label: "Premium Assets", value: "86K+" },
  { label: "Countries", value: "42" }, { label: "Updated", value: "Daily" },
];
export const popularCreatorSearches = ["Drone", "Travel photography", "Reels", "India", "Templates"];
export const creatorAuthorProfiles: CreatorAuthorProfile[] = [
  { id: "creator-01", slug: "aira-studio", displayName: "Aira Studio", username: "@aira.studio", avatar: "/themes/banners/culture-1.jpg", coverImage: "/experiences/luxury.jpg", verified: true, creatorLevel: "Enterprise Studio", specialization: "Videography", secondarySpecializations: ["Templates", "Presets & LUTs"], location: "Mumbai, India", country: "India", bio: "A compact creative studio building destination visuals, cinematic LUTs and campaign-ready motion packs for travel and hospitality teams.", shortBio: "Motion templates and cinematic colour for destination brands.", followers: 18400, assetCount: 42, downloadCount: 15040, rating: 4.9, reviewCount: 486, joinedAt: "March 2022", languages: ["English", "Hindi"], equipment: ["Sony Cinema Line", "DJI gimbal"], software: ["Premiere Pro", "After Effects", "DaVinci Resolve"], tags: ["Cinematic", "Travel", "Reels"], assetCategories: ["Videos", "Templates", "Presets"], featuredAssetSlugs: ["cinematic-ladakh-drone-pack", "creator-reel-template-kit", "cinematic-travel-lut-pack", "luxury-resort-reel-templates"], collectionSlugs: ["luxury-escapes", "social-media-packs"], locationsCovered: ["India", "South Asia"], contentStyle: "Polished, cinematic and campaign-led", commercialAvailable: true, editorialAvailable: true, modelReleaseReady: true, propertyReleaseReady: true },
  { id: "creator-02", slug: "northlight-motion", displayName: "Northlight Motion", username: "@northlight.motion", avatar: "/experiences/adventure.jpg", coverImage: "/holidays/manali.jpeg", verified: true, creatorLevel: "Elite", specialization: "Drone", secondarySpecializations: ["Videography", "Photography"], location: "Manali, India", country: "India", bio: "Mountain aerials, adventure footage and polished vertical edits created for modern destination campaigns.", shortBio: "High-altitude aerials and adventure storytelling.", followers: 29100, assetCount: 67, downloadCount: 23800, rating: 4.9, reviewCount: 392, joinedAt: "August 2021", languages: ["English", "Hindi"], equipment: ["DJI Mavic 3 Cine", "Sony A7S III"], software: ["DaVinci Resolve", "Premiere Pro"], tags: ["Drone", "Mountains", "Adventure"], assetCategories: ["Videos", "Photos"], featuredAssetSlugs: ["himalayan-sunrise-aerials", "india-adventure-content-kit"], collectionSlugs: ["himalayan-journeys", "drone-perspectives"], locationsCovered: ["Himalayas", "Ladakh"], contentStyle: "Immersive, natural and cinematic", commercialAvailable: true, editorialAvailable: true, modelReleaseReady: false, propertyReleaseReady: true },
  { id: "creator-03", slug: "noor-visuals", displayName: "Noor Visuals", username: "@noorvisuals", avatar: "/themes/banners/culture-2.jpg", coverImage: "/themes/banners/culture-3.jpg", verified: true, creatorLevel: "Professional", specialization: "Photography", secondarySpecializations: ["Presets & LUTs"], location: "Jaipur, India", country: "India", bio: "Editorial-grade culture, architecture and lifestyle photography with careful usage guidance and warm visual language.", shortBio: "Editorial culture and architecture photography.", followers: 24700, assetCount: 58, downloadCount: 17650, rating: 4.7, reviewCount: 284, joinedAt: "January 2023", languages: ["English", "Hindi", "Urdu"], equipment: ["Canon EOS R5", "Prime lens kit"], software: ["Lightroom", "Photoshop"], tags: ["Editorial", "Culture", "Architecture"], assetCategories: ["Photos", "Presets"], featuredAssetSlugs: ["jaipur-editorial-photo-set", "urban-night-mobile-presets", "rajasthan-heritage-portraits"], collectionSlugs: ["heritage-cities", "incredible-india"], locationsCovered: ["Rajasthan", "North India"], contentStyle: "Warm, observational and editorial", commercialAvailable: true, editorialAvailable: true, modelReleaseReady: true, propertyReleaseReady: false },
  { id: "creator-04", slug: "routecraft-labs", displayName: "RouteCraft Labs", username: "@routecraft", avatar: "/experiences/roadtrip.jpg", coverImage: "/continents/banners/asia-2.jpg", verified: true, creatorLevel: "Professional", specialization: "Writing & Guides", secondarySpecializations: ["Graphics", "Illustration"], location: "Bengaluru, India", country: "India", bio: "Route maps, planning kits and digital guides for explorers, creators and destination brands.", shortBio: "Useful route maps and destination publishing kits.", followers: 11200, assetCount: 31, downloadCount: 9200, rating: 4.8, reviewCount: 176, joinedAt: "June 2023", languages: ["English", "Hindi", "Kannada"], equipment: ["Field GPS", "Research toolkit"], software: ["Illustrator", "Figma", "InDesign"], tags: ["Maps", "Guides", "Routes"], assetCategories: ["Guides", "Graphics"], featuredAssetSlugs: ["monsoon-route-map-pack", "old-city-food-guide", "tropical-island-route-pack"], collectionSlugs: ["incredible-india", "beaches-of-asia"], locationsCovered: ["India", "Asia"], contentStyle: "Practical, precise and editorial", commercialAvailable: true, editorialAvailable: true, modelReleaseReady: false, propertyReleaseReady: false },
];
export const getCreatorAuthorProfile = (slug: string) => creatorAuthorProfiles.find((creator) => creator.slug === slug);
