import type { CreatorDownloadAudit,CreatorDownloadAuthorization,CreatorDownloadEvent } from "./creatorDownloadTypes";
import type { CreatorTestingCommerceRecord,CreatorTestingStoreData } from "./creatorEntitlementV1Types";
import { readCreatorTestingStore,writeCreatorTestingStore } from "./creatorTestingCommerceRepository";
export interface CreatorDownloadRepository{
  transaction<T>(operation:()=>T):T;
  getEntitlement(entitlementId:string,buyerId:string):CreatorTestingCommerceRecord|null;
  lockEntitlementForAuthorization(entitlementId:string,buyerId:string):CreatorTestingCommerceRecord|null;
  createDownloadAuthorization(value:CreatorDownloadAuthorization):{value:CreatorDownloadAuthorization;duplicate:boolean;persistence:string};
  findToken(tokenHash:string,buyerId:string):CreatorDownloadAuthorization|null;
  consumeAuthorizationToken(tokenHash:string,buyerId:string,event:CreatorDownloadEvent):{authorization:CreatorDownloadAuthorization;record:CreatorTestingCommerceRecord;event:CreatorDownloadEvent}|null;
  appendDownloadHistory(event:CreatorDownloadEvent):void;revokeOutstandingTokens(entitlementId:string,reason:string):number;recordAudit(event:CreatorDownloadAudit):void;findIdempotency(key:string):CreatorDownloadAuthorization|null;history(buyerId:string):CreatorDownloadEvent[];
  acquireRateLimit(input:{scope:string;actorId:string;secondaryKey?:string;limit:number;windowSeconds:number}):{allowed:boolean;remaining:number;resetAt:string;source:"file_fallback"};
  health():{status:"ready"|"degraded";provider:"file_fallback";transactionalDatabase:false;crossProcessLocking:false;warnings:string[]};
}
const auths=(data:CreatorTestingStoreData)=>(data.downloads??[]) as CreatorDownloadAuthorization[];
const events=(data:CreatorTestingStoreData)=>(data.downloadEvents??[]) as CreatorDownloadEvent[];
const audits=(data:CreatorTestingStoreData)=>(data.downloadAudits??[]) as CreatorDownloadAudit[];
function save(data:CreatorTestingStoreData){return writeCreatorTestingStore({...data,updatedAt:new Date().toISOString()});}
export const creatorFileTestingDownloadRepository:CreatorDownloadRepository={
  transaction(operation){return operation();},
  getEntitlement(id,buyer){return readCreatorTestingStore().records.find(item=>item.entitlement.entitlementId===id&&item.entitlement.buyerId===buyer)??null;},
  lockEntitlementForAuthorization(id,buyer){return this.getEntitlement(id,buyer);},
  findToken(tokenHash,buyerId){return auths(readCreatorTestingStore()).find(item=>item.tokenHash===tokenHash&&item.buyerId===buyerId)??null;},
  findIdempotency(key){const data=readCreatorTestingStore();const id=data.downloadIdempotency?.[key];return id?auths(data).find(item=>item.authorizationId===id)??null:null;},
  createDownloadAuthorization(value){const data=readCreatorTestingStore();const existing=this.findIdempotency(value.idempotencyKey);if(existing)return {value:existing,duplicate:true,persistence:"existing"};const nextAuths=[...auths(data),value];const nextKeys={...(data.downloadIdempotency??{}),[value.idempotencyKey]:value.authorizationId};const persistence=save({...data,downloads:nextAuths,downloadEvents:events(data),downloadAudits:audits(data),downloadIdempotency:nextKeys});return {value,duplicate:false,persistence};},
  consumeAuthorizationToken(tokenHash,buyerId,event){const data=readCreatorTestingStore();const list=auths(data);const index=list.findIndex(item=>item.tokenHash===tokenHash&&item.buyerId===buyerId);if(index<0)return null;const authorization=list[index];if(authorization.status!=="authorized_testing"||authorization.uses>=authorization.maxUses||new Date(authorization.expiresAt).getTime()<=Date.now())return null;const recordIndex=data.records.findIndex(item=>item.entitlement.entitlementId===authorization.entitlementId&&item.entitlement.buyerId===buyerId);if(recordIndex<0)return null;const record=data.records[recordIndex];if(record.entitlement.downloadsRemaining<=0||record.entitlement.status!=="active_testing")return null;const now=new Date().toISOString();const remaining=Math.max(0,record.entitlement.downloadsRemaining-1);const updatedRecord={...record,entitlement:{...record.entitlement,downloadsUsed:record.entitlement.downloadsUsed+1,downloadsRemaining:remaining,status:remaining===0?"exhausted_testing" as const:record.entitlement.status,updatedAt:now,planAllowance:record.entitlement.planAllowance?{...record.entitlement.planAllowance,downloadsUsed:record.entitlement.planAllowance.downloadsUsed+1,downloadsRemaining:Math.max(0,record.entitlement.planAllowance.downloadsRemaining-1)}:undefined},timeline:[...record.timeline,{status:"testing_download_complete",at:now}]};const updatedAuth={...authorization,status:"consumed_testing" as const,uses:authorization.uses+1,consumedAt:now};const nextRecords=[...data.records];nextRecords[recordIndex]=updatedRecord;const nextAuths=[...list];nextAuths[index]=updatedAuth;save({...data,records:nextRecords,downloads:nextAuths,downloadEvents:[...events(data),event],downloadAudits:[...audits(data),{auditId:`audit-${event.eventId}`,buyerId,entitlementId:authorization.entitlementId,authorizationId:authorization.authorizationId,eventType:"delivery_succeeded",reason:"Testing delivery consumed once",createdAt:now},{auditId:`audit-count-${event.eventId}`,buyerId,entitlementId:authorization.entitlementId,authorizationId:authorization.authorizationId,eventType:"allowance_decremented",reason:"Successful testing delivery",createdAt:now}]});return {authorization:updatedAuth,record:updatedRecord,event};},
  appendDownloadHistory(event){const data=readCreatorTestingStore();if(events(data).some(item=>item.eventId===event.eventId))return;save({...data,downloadEvents:[...events(data),event]});},
  revokeOutstandingTokens(entitlementId,reason){const data=readCreatorTestingStore();let count=0;const now=new Date().toISOString();const list=auths(data).map(item=>{if(item.entitlementId===entitlementId&&item.status==="authorized_testing"){count++;return {...item,status:"revoked_testing" as const,revokedAt:now,revocationReason:reason};}return item;});if(count)save({...data,downloads:list});return count;},
  recordAudit(event){const data=readCreatorTestingStore();if(audits(data).some(item=>item.auditId===event.auditId))return;save({...data,downloadAudits:[...audits(data),event]});},
  history(buyerId){return events(readCreatorTestingStore()).filter(item=>item.buyerId===buyerId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));},
  acquireRateLimit(input){const data=readCreatorTestingStore(),now=Date.now(),key=`${input.scope}:${input.actorId}:${input.secondaryKey??""}`,current=data.downloadRateLimits?.[key];const windowMs=input.windowSeconds*1000;const next=!current||now-current.windowStartedAt>=windowMs?{windowStartedAt:now,count:1}:{...current,count:current.count+1};save({...data,downloadRateLimits:{...(data.downloadRateLimits??{}),[key]:next}});return {allowed:next.count<=input.limit,remaining:Math.max(0,input.limit-next.count),resetAt:new Date(next.windowStartedAt+windowMs).toISOString(),source:"file_fallback"};},
  health(){return {status:"degraded",provider:"file_fallback",transactionalDatabase:false,crossProcessLocking:false,warnings:["Atomic rename is single-instance only","No approved testing PostgreSQL adapter is connected"]};},
};
export function getCreatorDownloadRepository():CreatorDownloadRepository{return creatorFileTestingDownloadRepository;}
