import { createHash,randomBytes } from "node:crypto";
import { getCreatorAsset } from "./creatorCatalogService";
import { creatorTestingDeliveryProvider,creatorTestingVariant,type TestingFileVariant } from "./creatorAssetDeliveryProvider";
import { getCreatorDownloadRepository,type CreatorDownloadRepository } from "./creatorDownloadRepository";
import type { CreatorDownloadAuthorization,CreatorDownloadAuthorizationResponse,CreatorDownloadAudit,CreatorDownloadEvent } from "./creatorDownloadTypes";
import { CREATOR_DOWNLOAD_AUTHORIZATION_VERSION,CREATOR_DOWNLOAD_EVENT_VERSION } from "./creatorDownloadTypes";
const sha=(value:string)=>createHash("sha256").update(value).digest("hex");
const audit=(buyerId:string,entitlementId:string,eventType:CreatorDownloadAudit["eventType"],reason:string,authorizationId?:string):CreatorDownloadAudit=>({auditId:`download-audit-${sha(`${buyerId}:${entitlementId}:${eventType}:${authorizationId??reason}`).slice(0,20)}`,buyerId,entitlementId,authorizationId,eventType,reason,createdAt:new Date().toISOString()});
function response(value:CreatorDownloadAuthorization,token:string|null):CreatorDownloadAuthorizationResponse{const {tokenHash:_,buyerId:__,objectReference:___,...safe}=value;void _;void __;void ___;return {...safe,token,deliverySource:"testing_private_fixture"};}
export function authorizeCreatorTestingDownload(input:{buyerId:string;entitlementId:string;assetSlug?:string;fileVariant:string;idempotencyKey:string},repository:CreatorDownloadRepository=getCreatorDownloadRepository()){
  if(!repository.acquireRateLimit({scope:"download_authorization",actorId:input.buyerId,limit:12,windowSeconds:60}).allowed)throw new Error("RATE_LIMITED");const requestHash=sha(JSON.stringify({buyerId:input.buyerId,entitlementId:input.entitlementId,assetSlug:input.assetSlug??null,fileVariant:input.fileVariant}));const existing=repository.findIdempotency(input.idempotencyKey);if(existing){if(existing.requestHash!==requestHash)throw new Error("IDEMPOTENCY_CONFLICT");return response(existing,null);}const record=repository.lockEntitlementForAuthorization(input.entitlementId,input.buyerId);if(!record)throw new Error("ENTITLEMENT_NOT_FOUND");const entitlement=record.entitlement;repository.recordAudit(audit(input.buyerId,input.entitlementId,"authorization_requested","Testing authorization requested"));
  if(entitlement.status!=="active_testing"){repository.recordAudit(audit(input.buyerId,input.entitlementId,"entitlement_blocked",entitlement.status));throw new Error(entitlement.status==="revoked_testing"||entitlement.status==="refunded_testing"?"ENTITLEMENT_REVOKED":entitlement.status==="expired_testing"?"ENTITLEMENT_EXPIRED":entitlement.status==="exhausted_testing"?"ALLOWANCE_EXHAUSTED":"ENTITLEMENT_PENDING");}
  if(!["testing_confirmed","confirmed_testing"].includes(record.order.orderStatus))throw new Error("ORDER_NOT_CONFIRMED");if(entitlement.downloadsRemaining<=0)throw new Error("ALLOWANCE_EXHAUSTED");if(entitlement.validUntil&&new Date(entitlement.validUntil).getTime()<=Date.now())throw new Error("ENTITLEMENT_EXPIRED");
  const assetSlug=entitlement.assetSlug??input.assetSlug;if(!assetSlug||!getCreatorAsset(assetSlug))throw new Error("OBJECT_UNAVAILABLE");const variant=creatorTestingVariant(input.fileVariant);if(!variant)throw new Error("UNSUPPORTED_FILE_VARIANT");const object=creatorTestingDeliveryProvider.authorizeObject(variant);
  const token=randomBytes(32).toString("base64url"),now=new Date(),authorizationId=`creator-download-auth-${randomBytes(12).toString("hex")}`;const authorization:CreatorDownloadAuthorization={version:CREATOR_DOWNLOAD_AUTHORIZATION_VERSION,authorizationId,tokenHash:sha(token),buyerId:input.buyerId,entitlementId:entitlement.entitlementId,orderId:entitlement.orderId,assetId:entitlement.assetId,assetSlug,assetVersion:entitlement.usageRightsSnapshot.assetVersion,licenseType:entitlement.licenseType,objectReference:object.reference,deliveryMode:"testing_private_fixture",fileVariant:variant,status:"authorized_testing",maxUses:1,uses:0,expiresAt:new Date(now.getTime()+2*60000).toISOString(),source:"testing_api",requestId:`download-request-${randomBytes(8).toString("hex")}`,createdAt:now.toISOString(),consumedAt:null,revokedAt:null,revocationReason:null,idempotencyKey:input.idempotencyKey,requestHash};repository.createDownloadAuthorization(authorization);repository.recordAudit(audit(input.buyerId,input.entitlementId,"authorization_granted","Short-lived testing token granted",authorizationId));return response(authorization,token);
}
export function consumeCreatorTestingDownload(input:{buyerId:string;token:string;ip?:string;userAgent?:string},repository:CreatorDownloadRepository=getCreatorDownloadRepository()){return repository.transaction(()=>{const tokenHash=sha(input.token);const storeRecord=repository.findToken(tokenHash,input.buyerId);if(!storeRecord)throw new Error("TOKEN_INVALID");if(new Date(storeRecord.expiresAt).getTime()<=Date.now())throw new Error("AUTHORIZATION_EXPIRED");if(storeRecord.status==="consumed_testing")throw new Error("AUTHORIZATION_CONSUMED");if(storeRecord.status==="revoked_testing")throw new Error("AUTHORIZATION_REVOKED");const object=creatorTestingDeliveryProvider.consumeTemporaryDelivery(storeRecord.objectReference);if(!object)throw new Error("OBJECT_UNAVAILABLE");const event:CreatorDownloadEvent={version:CREATOR_DOWNLOAD_EVENT_VERSION,eventId:`download-event-${sha(storeRecord.authorizationId).slice(0,24)}`,authorizationId:storeRecord.authorizationId,entitlementId:storeRecord.entitlementId,orderId:storeRecord.orderId,buyerId:input.buyerId,assetId:storeRecord.assetId,assetVersion:storeRecord.assetVersion,licenseType:storeRecord.licenseType,deliveryMode:storeRecord.deliveryMode,fileVariant:storeRecord.fileVariant,byteSize:object.bytes.byteLength,ipHash:sha(input.ip??"redacted").slice(0,16),userAgentHash:sha(input.userAgent??"redacted").slice(0,16),status:"delivery_succeeded",reason:"Synthetic testing file delivered",requestId:storeRecord.requestId,createdAt:new Date().toISOString(),countImpact:1};const consumed=repository.consumeAuthorizationToken(tokenHash,input.buyerId,event);if(!consumed)throw new Error("AUTHORIZATION_CONSUMED");return {object,event,record:consumed.record};});}
export function testingDownloadHistory(buyerId:string,repository:CreatorDownloadRepository=getCreatorDownloadRepository()){return repository.history(buyerId);}
export const creatorDownloadPolicy={tokenTtlSeconds:120,maxUses:1,productionPrivateObjectEnabled:false,publicOriginalsEnabled:false,allowedVariants:["image","video-placeholder","template-placeholder","preset-placeholder","guide-placeholder"] as TestingFileVariant[]};
