import type { CreatorLicenseDefinition } from "./creatorLicenseTypes";

const legalDisclaimer = "Platform policy foundation only. Final legal terms require review before public launch.";

export const creatorLicenseDefinitions: CreatorLicenseDefinition[] = [
  {
    licenseType: "personal",
    displayName: "Personal License",
    description: "For private, non-commercial creative use.",
    allowedUses: ["Personal projects", "Portfolio work", "Organic non-paid social posts"],
    prohibitedUses: ["Client work", "Paid advertising", "Raw file resale", "Template redistribution"],
    seatLimit: 1,
    projectLimit: 3,
    endProductLimit: 3,
    distributionLimit: "Private and organic channels",
    resaleAllowed: false,
    modificationAllowed: true,
    attributionRequired: false,
    geographicRestrictions: [],
    validityMode: "perpetual",
    validityDuration: null,
    accessWindow: "Account access while entitlement remains active",
    downloadLimit: 5,
    versionAccessPolicy: "purchased_version_only",
    supportPeriod: "30 days",
    commercialUseAllowed: false,
    editorialUseOnly: false,
    customTermsRequired: false,
    priceMultiplier: 1,
    policyReviewRequired: true,
    legalDisclaimer,
  },
  {
    licenseType: "commercial",
    displayName: "Commercial License",
    description: "For standard client, brand and business content usage.",
    allowedUses: ["Client campaigns", "Brand websites", "Owned and paid social", "Presentations"],
    prohibitedUses: ["Standalone resale", "Raw file redistribution", "Broadcast buyout without custom terms"],
    seatLimit: 5,
    projectLimit: 10,
    endProductLimit: 10,
    distributionLimit: "Digital commercial distribution",
    resaleAllowed: false,
    modificationAllowed: true,
    attributionRequired: false,
    geographicRestrictions: [],
    validityMode: "perpetual",
    validityDuration: null,
    accessWindow: "Account access while entitlement remains active",
    downloadLimit: 10,
    versionAccessPolicy: "minor_updates",
    supportPeriod: "90 days",
    commercialUseAllowed: true,
    editorialUseOnly: false,
    customTermsRequired: false,
    priceMultiplier: 2,
    policyReviewRequired: true,
    legalDisclaimer,
  },
  {
    licenseType: "extended_commercial",
    displayName: "Extended Commercial License",
    description: "For higher-scale campaigns and expanded commercial use.",
    allowedUses: ["Large campaigns", "Paid media", "Agency libraries", "Regional launches"],
    prohibitedUses: ["Raw file resale", "Trademark misuse", "SaaS embedding without custom terms"],
    seatLimit: 15,
    projectLimit: "unlimited",
    endProductLimit: "unlimited",
    distributionLimit: "High-scale digital and offline distribution",
    resaleAllowed: false,
    modificationAllowed: true,
    attributionRequired: false,
    geographicRestrictions: [],
    validityMode: "perpetual",
    validityDuration: null,
    accessWindow: "Account access while entitlement remains active",
    downloadLimit: 20,
    versionAccessPolicy: "all_updates_during_support",
    supportPeriod: "180 days",
    commercialUseAllowed: true,
    editorialUseOnly: false,
    customTermsRequired: false,
    priceMultiplier: 5,
    policyReviewRequired: true,
    legalDisclaimer,
  },
  {
    licenseType: "editorial",
    displayName: "Editorial License",
    description: "For news, guide, educational and commentary use where commercial endorsement is not permitted.",
    allowedUses: ["Editorial articles", "Blogs", "Guides", "Educational commentary"],
    prohibitedUses: ["Product endorsement", "Paid advertising", "Merchandise", "Sensitive commercial use"],
    seatLimit: 3,
    projectLimit: 5,
    endProductLimit: 5,
    distributionLimit: "Editorial distribution only",
    resaleAllowed: false,
    modificationAllowed: true,
    attributionRequired: true,
    geographicRestrictions: [],
    validityMode: "perpetual",
    validityDuration: null,
    accessWindow: "Account access while entitlement remains active",
    downloadLimit: 5,
    versionAccessPolicy: "purchased_version_only",
    supportPeriod: "30 days",
    commercialUseAllowed: false,
    editorialUseOnly: true,
    customTermsRequired: false,
    priceMultiplier: 1,
    policyReviewRequired: true,
    legalDisclaimer,
  },
  {
    licenseType: "subscription",
    displayName: "Subscription Entitlement",
    description: "For future subscription-based access while an active plan remains valid.",
    allowedUses: ["Subscription plan usage subject to active plan"],
    prohibitedUses: ["Access after subscription expiry", "Raw redistribution", "Plan sharing"],
    seatLimit: 1,
    projectLimit: "unlimited",
    endProductLimit: "unlimited",
    distributionLimit: "Subscription policy controlled",
    resaleAllowed: false,
    modificationAllowed: true,
    attributionRequired: false,
    geographicRestrictions: [],
    validityMode: "subscription",
    validityDuration: "Active subscription period",
    accessWindow: "Active subscription only",
    downloadLimit: 30,
    versionAccessPolicy: "latest_version_during_subscription",
    supportPeriod: "Active subscription period",
    commercialUseAllowed: true,
    editorialUseOnly: false,
    customTermsRequired: false,
    priceMultiplier: null,
    policyReviewRequired: true,
    legalDisclaimer,
  },
  {
    licenseType: "custom_enterprise_request",
    displayName: "Custom Enterprise Request",
    description: "For custom legal, geographic, seat, broadcast or enterprise usage review.",
    allowedUses: ["Custom use after written approval"],
    prohibitedUses: ["Automatic paid checkout", "Use before approval", "Unreviewed redistribution"],
    seatLimit: "custom",
    projectLimit: "custom",
    endProductLimit: "custom",
    distributionLimit: "Custom contract required",
    resaleAllowed: false,
    modificationAllowed: true,
    attributionRequired: false,
    geographicRestrictions: ["Custom"],
    validityMode: "enterprise_review",
    validityDuration: "Custom",
    accessWindow: "No access until approved",
    downloadLimit: "custom",
    versionAccessPolicy: "custom",
    supportPeriod: "Custom",
    commercialUseAllowed: true,
    editorialUseOnly: false,
    customTermsRequired: true,
    priceMultiplier: null,
    policyReviewRequired: true,
    legalDisclaimer,
  },
];
