export type ModerationStatus = "draft" | "submitted" | "under-review" | "changes-requested" | "approved" | "scheduled" | "published" | "rejected" | "archived";
export type ComplianceState = "pass" | "warning" | "pending";

export interface CreatorModerationSubmission {
  id: string; assetId: string; slug: string; title: string; preview: string; type: string; destination: string; collection: string; license: string; status: ModerationStatus; stage: string; submitted: string; sla: string; version: string;
  compliance: Record<"metadata" | "copyright" | "modelRelease" | "propertyRelease" | "license" | "ownership", ComplianceState>;
  note?: string; reason?: string; guideline?: string; fixes?: string[]; deadline?: string;
}

export const moderationStatuses: { id: "all" | ModerationStatus; label: string; description: string }[] = [
  { id: "all", label: "All", description: "Every submission" }, { id: "draft", label: "Draft", description: "Not submitted" },
  { id: "submitted", label: "Submitted", description: "Awaiting screening" }, { id: "under-review", label: "Under Review", description: "Review in progress" },
  { id: "changes-requested", label: "Changes Requested", description: "Creator action needed" }, { id: "approved", label: "Approved", description: "Review completed" },
  { id: "scheduled", label: "Scheduled", description: "Queued to publish" }, { id: "published", label: "Published", description: "Live in marketplace" },
  { id: "rejected", label: "Rejected", description: "Not approved" }, { id: "archived", label: "Archived", description: "Removed from queue" },
];

const complete = { metadata: "pass", copyright: "pass", modelRelease: "pass", propertyRelease: "pass", license: "pass", ownership: "pass" } as const;
export const moderationSubmissions: CreatorModerationSubmission[] = [
  { id: "mod-01", assetId: "TPL-CR-10482", slug: "cinematic-ladakh-drone-pack", title: "Cinematic Ladakh Drone Pack", preview: "/experiences/adventure.jpg", type: "Drone Footage", destination: "Ladakh", collection: "Himalayan Aerials", license: "Extended", status: "under-review", stage: "Quality Review", submitted: "16 Jul 2026", sla: "18 hours left", version: "v2.1", compliance: { ...complete, propertyRelease: "pending" }, note: "A reviewer is confirming the location and aerial capture details." },
  { id: "mod-02", assetId: "TPL-CR-10479", slug: "luxury-resort-reel-templates", title: "Luxury Resort Reel Templates", preview: "/experiences/luxury.jpg", type: "Template", destination: "Maldives", collection: "Luxury Escapes", license: "Commercial", status: "changes-requested", stage: "Metadata Review", submitted: "15 Jul 2026", sla: "Due 20 Jul", version: "v1.4", compliance: { ...complete, metadata: "warning", copyright: "warning" }, note: "Please clarify font licensing and add the editing software version.", guideline: "Metadata and third-party rights", fixes: ["Add supported software version", "Attach font license proof", "Remove two duplicate keywords"], deadline: "20 Jul 2026" },
  { id: "mod-03", assetId: "TPL-CR-10461", slug: "rajasthan-heritage-portraits", title: "Rajasthan Heritage Portraits", preview: "/themes/banners/culture-2.jpg", type: "Photos", destination: "Rajasthan", collection: "Heritage India", license: "Standard", status: "rejected", stage: "Compliance Check", submitted: "12 Jul 2026", sla: "Closed", version: "v1.0", compliance: { ...complete, modelRelease: "warning" }, reason: "Missing model release", guideline: "People and portrait releases", note: "A recognizable person is the primary subject. A signed release is required for commercial licensing.", fixes: ["Attach a signed model release", "Or change the submission to Editorial license", "Confirm the subject identity matches the release"] },
  { id: "mod-04", assetId: "TPL-CR-10457", slug: "goa-sunset-social-pack", title: "Goa Sunset Social Pack", preview: "/holidays/goa.jpeg", type: "Graphics", destination: "Goa", collection: "Coastal Stories", license: "Standard", status: "approved", stage: "Approval", submitted: "10 Jul 2026", sla: "Completed", version: "v1.2", compliance: complete, note: "All quality and compliance checks passed." },
  { id: "mod-05", assetId: "TPL-CR-10444", slug: "kerala-backwaters-film", title: "Kerala Backwaters Film", preview: "/demo/kerala-cover.jpg", type: "Videos", destination: "Kerala", collection: "Slow Travel", license: "Extended", status: "scheduled", stage: "Publishing", submitted: "8 Jul 2026", sla: "Publishes 19 Jul", version: "v3.0", compliance: complete },
  { id: "mod-06", assetId: "TPL-CR-10428", slug: "mumbai-after-dark", title: "Mumbai After Dark", preview: "/experiences/corporate.jpg", type: "Photos", destination: "Mumbai", collection: "Urban India", license: "Editorial", status: "published", stage: "Published", submitted: "3 Jul 2026", sla: "Live", version: "v1.0", compliance: { ...complete, modelRelease: "pending", propertyRelease: "pending" } },
  { id: "mod-07", assetId: "TPL-CR-10412", slug: "sikkim-destination-guide", title: "Sikkim Destination Guide", preview: "/experiences/wildlife.jpg", type: "Destination Guide", destination: "Sikkim", collection: "Eastern Himalayas", license: "Standard", status: "submitted", stage: "Initial Screening", submitted: "17 Jul 2026", sla: "2 days", version: "v1.0", compliance: { ...complete, copyright: "pending", ownership: "pending" } },
  { id: "mod-08", assetId: "TPL-CR-10398", slug: "desert-audio-atmospheres", title: "Desert Audio Atmospheres", preview: "/experiences/roadtrip.jpg", type: "Audio", destination: "Jaisalmer", collection: "Desert Journeys", license: "Commercial", status: "draft", stage: "Draft", submitted: "Not submitted", sla: "—", version: "v0.6", compliance: { metadata: "warning", copyright: "pending", modelRelease: "pending", propertyRelease: "pending", license: "warning", ownership: "pending" } },
  { id: "mod-09", assetId: "TPL-CR-10371", slug: "old-hampi-architecture", title: "Old Hampi Architecture", preview: "/themes/banners/culture-1.jpg", type: "Photos", destination: "Hampi", collection: "Historic India", license: "Editorial", status: "archived", stage: "Archived", submitted: "20 Jun 2026", sla: "Closed", version: "v1.0", compliance: complete },
];

export const moderationStages = ["Submission", "Initial Screening", "Metadata Review", "Compliance Check", "Quality Review", "Approval", "Publishing"];
export const rejectionReasons = [{ label: "Low Quality", value: 32 }, { label: "Copyright", value: 24 }, { label: "Missing Release", value: 19 }, { label: "Metadata", value: 14 }, { label: "Duplicate", value: 7 }, { label: "Policy", value: 4 }];
export const moderationFilterOptions = { type: ["Photos", "Videos", "Drone Footage", "Templates", "Graphics", "Destination Guide", "Audio"], destination: ["Ladakh", "Maldives", "Rajasthan", "Goa", "Kerala", "Mumbai", "Sikkim"], date: ["Last 7 days", "Last 30 days", "Last 90 days"], collection: ["Himalayan Aerials", "Luxury Escapes", "Heritage India", "Coastal Stories"], license: ["Standard", "Extended", "Commercial", "Editorial"], sort: ["Newest", "Oldest", "SLA soonest", "Title A–Z"] };
