import { creatorPlans } from "./creatorPlansData";
import type { CreatorCommerceOrderDTO } from "./creatorCommerceTypes";
import type { CreatorEntitlementV1,CreatorLicenseCertificateV1,CreatorTestingCommerceRecord } from "./creatorEntitlementV1Types";
import { CREATOR_CERTIFICATE_VERSION,CREATOR_ENTITLEMENT_VERSION } from "./creatorEntitlementV1Types";
import { creatorTestingCommerceRepository } from "./creatorTestingCommerceRepository";
import { creatorFileTestingDownloadRepository } from "./creatorDownloadRepository";
function hash(value:string){let h=0;for(const c of value){h=(h<<5)-h+c.charCodeAt(0);h|=0;}return Math.abs(h).toString(36);}
const request=(value:string)=>`creator-entitlement-request-${hash(value)}`;
export function finalizeTestingEntitlement(order:CreatorCommerceOrderDTO,now=new Date()){
  if(order.paymentStatus!=="testing_succeeded"||order.orderStatus!=="testing_confirmed")throw new Error("PAYMENT_NOT_SUCCESSFUL");
  if(order.productType==="creator_enterprise_inquiry")throw new Error("ENTITLEMENT_NOT_APPLICABLE");
  const existing=creatorTestingCommerceRepository.byOrder(order.orderId);if(existing)return {record:existing,persistence:"existing" as const};
  const item=order.items[0];if(!item||item.totalAmount!==order.amounts.totalAmount)throw new Error("AMOUNT_MISMATCH");
  const isPlan=order.productType==="creator_plan";const plan=isPlan?creatorPlans.find(value=>value.key===item.planId):undefined;
  if(isPlan&&!plan)throw new Error("INVALID_PLAN");
  const monthlyAllowance=plan?Number(plan.features.find(value=>value.includes("downloads / month"))?.match(/\d+/)?.[0]??0):1;
  const createdAt=now.toISOString();const entitlementId=`creator-entitlement-${hash(`${order.orderId}:${order.buyerId}:${item.id}`)}`;
  const entitlement:CreatorEntitlementV1={version:CREATOR_ENTITLEMENT_VERSION,entitlementId,orderId:order.orderId,checkoutId:order.checkoutId,buyerId:order.buyerId,productType:order.productType,assetId:item.assetId,assetSlug:item.assetSlug,planId:item.planId,creatorSlug:item.creatorSlug,licenseType:item.licenseType,licenseVersion:item.licenseVersion??(isPlan?"creator-plan-terms-v1":"creator-license-policy-v1"),usageRightsSnapshot:{allowedUses:[...item.usageRightsSnapshot],prohibitedUses:["Redistribution of source files","Resale as competing stock","Illegal or harmful use"],territory:"Worldwide testing snapshot",duration:isPlan?"Testing billing period":"Perpetual testing snapshot",commercialEditorialPosition:item.licenseType?"Commercial use subject to snapshot":"Plan terms snapshot",modelReleaseStatus:"Asset metadata dependent",propertyReleaseStatus:"Asset metadata dependent",assetVersion:String(item.metadata.assetVersion??"v1"),creatorIdentity:{slug:item.creatorSlug??null},buyerIdentity:{id:order.buyerId}},status:"active_testing",source:"testing_api",validFrom:createdAt,validUntil:isPlan?new Date(now.getTime()+30*86400000).toISOString():null,downloadAllowance:isPlan?monthlyAllowance:1,downloadsUsed:0,downloadsRemaining:isPlan?monthlyAllowance:1,planAllowance:isPlan?{monthlyAllowance,annualAllowance:monthlyAllowance*12,downloadsUsed:0,downloadsRemaining:monthlyAllowance,resetDate:new Date(now.getTime()+30*86400000).toISOString(),rolloverAllowed:false,eligibleAssetTypes:["photos","videos","reels","drone","templates","presets","graphics","destination-guides"],standardLicenseIncluded:true,extendedLicenseDiscountPreview:"Configuration dependent"}:undefined,certificateStatus:isPlan?"not_applicable":"preview_generated",invoiceStatus:"not_generated",revocationReason:null,requestId:request(entitlementId),createdAt,updatedAt:createdAt,downloadAllowed:false};
  const certificate:CreatorLicenseCertificateV1|undefined=item.licenseType?{version:CREATOR_CERTIFICATE_VERSION,certificateId:`creator-certificate-${hash(entitlementId)}`,entitlementId,orderId:order.orderId,asset:{id:item.assetId,slug:item.assetSlug,title:item.title},creator:{slug:item.creatorSlug},buyer:{id:order.buyerId},licenseType:item.licenseType,licenseVersion:entitlement.licenseVersion,issueDate:createdAt,testingVerificationCode:`TPL-TEST-${hash(entitlementId).toUpperCase()}`,status:"preview_generated",source:"testing_api",productionValid:false}:undefined;
  const record:CreatorTestingCommerceRecord={order:{...order,entitlementStatus:"pending_testing"},entitlement,certificate,timeline:[{status:"paid_testing",at:order.createdAt},{status:"confirmed_testing",at:order.updatedAt},{status:"active_testing",at:createdAt}]};return creatorTestingCommerceRepository.save(record);
}
export function revokeTestingEntitlement(orderId:string,reason:string){const existing=creatorTestingCommerceRepository.byOrder(orderId);if(!existing)return null;if(existing.entitlement.status==="revoked_testing")return existing;const now=new Date().toISOString();creatorFileTestingDownloadRepository.revokeOutstandingTokens(existing.entitlement.entitlementId,reason||"Testing revocation");return creatorTestingCommerceRepository.save({...existing,order:{...existing.order,orderStatus:"testing_confirmed"},entitlement:{...existing.entitlement,status:"revoked_testing",revocationReason:reason||"Testing revocation",certificateStatus:existing.certificate?"preview_generated":"not_applicable",updatedAt:now},certificate:existing.certificate?{...existing.certificate,status:"revoked_testing"}:undefined,timeline:[...existing.timeline,{status:"revoked_testing",at:now}]}).record;}
