export type StudioAssetStatus = "draft" | "under-review" | "published" | "rejected" | "archived";
export type StudioAssetType = "photos" | "videos" | "reels" | "drone" | "templates" | "graphics" | "guides" | "audio";
export type StudioLicenseType = "standard" | "extended" | "editorial" | "commercial" | "enterprise";

export interface StudioManagedAsset {
  id: string; assetId: string; slug: string; title: string; assetType: StudioAssetType; previewImage: string;
  fileFormat: string; duration?: string; resolution: string; orientation: string; status: StudioAssetStatus;
  moderationStatus: string; rejectionReason?: string; moderatorNote?: string; uploadedAt: string; updatedAt: string;
  downloads: number; views: number; revenue: number; conversion: number; licenseType: StudioLicenseType;
  planIncluded: boolean; price: number; destination: string; country: string; tags: string[]; collectionSlugs: string[]; fileSize: string;
}

const fixtures: Array<Omit<StudioManagedAsset, "id" | "assetId">> = [
  { slug: "cinematic-ladakh-drone-pack", title: "Cinematic Ladakh Drone Pack", assetType: "drone", previewImage: "/experiences/adventure.jpg", fileFormat: "MOV", duration: "4:30", resolution: "4K", orientation: "Landscape", status: "published", moderationStatus: "Approved", uploadedAt: "2026-07-12", updatedAt: "2026-07-12", downloads: 4820, views: 61000, revenue: 42800, conversion: 7.9, licenseType: "extended", planIncluded: true, price: 2499, destination: "Ladakh", country: "India", tags: ["ladakh", "drone", "mountains", "4k"], collectionSlugs: ["cinematic-india", "himalayan-aerials"], fileSize: "2.8 GB" },
  { slug: "rajasthan-heritage-portraits", title: "Rajasthan Heritage Portraits", assetType: "photos", previewImage: "/themes/banners/culture-2.jpg", fileFormat: "JPG", resolution: "24 MP", orientation: "Portrait", status: "published", moderationStatus: "Approved", uploadedAt: "2026-07-10", updatedAt: "2026-07-11", downloads: 3210, views: 47200, revenue: 31400, conversion: 6.8, licenseType: "editorial", planIncluded: true, price: 1799, destination: "Rajasthan", country: "India", tags: ["portrait", "heritage", "editorial"], collectionSlugs: ["rajasthan-heritage"], fileSize: "940 MB" },
  { slug: "luxury-resort-reel-templates", title: "Luxury Resort Reel Templates", assetType: "templates", previewImage: "/experiences/luxury.jpg", fileFormat: "ZIP", duration: "0:45", resolution: "1080p", orientation: "Portrait", status: "published", moderationStatus: "Approved", uploadedAt: "2026-07-08", updatedAt: "2026-07-09", downloads: 5600, views: 66700, revenue: 54100, conversion: 8.4, licenseType: "commercial", planIncluded: true, price: 2299, destination: "Global", country: "India", tags: ["luxury", "resort", "reels"], collectionSlugs: ["luxury-travel-reels"], fileSize: "410 MB" },
  { slug: "himalayan-sunrise-aerials", title: "Himalayan Sunrise Aerials", assetType: "drone", previewImage: "/holidays/manali.jpeg", fileFormat: "MOV", duration: "3:12", resolution: "4K", orientation: "Landscape", status: "under-review", moderationStatus: "Rights review", uploadedAt: "2026-07-15", updatedAt: "2026-07-15", downloads: 0, views: 0, revenue: 0, conversion: 0, licenseType: "extended", planIncluded: true, price: 2899, destination: "Himalayas", country: "India", tags: ["himalaya", "sunrise", "aerial"], collectionSlugs: ["himalayan-aerials"], fileSize: "3.1 GB" },
  { slug: "urban-night-mobile-presets", title: "Urban Night Mobile Presets", assetType: "templates", previewImage: "/themes/banners/culture-3.jpg", fileFormat: "XMP", resolution: "Preset", orientation: "Mixed", status: "draft", moderationStatus: "Not submitted", uploadedAt: "2026-07-14", updatedAt: "2026-07-16", downloads: 0, views: 0, revenue: 0, conversion: 0, licenseType: "standard", planIncluded: true, price: 399, destination: "Mumbai", country: "India", tags: ["urban", "night", "mobile"], collectionSlugs: ["urban-india"], fileSize: "48 MB" },
  { slug: "india-adventure-content-kit", title: "India Adventure Content Kit", assetType: "graphics", previewImage: "/experiences/roadtrip.jpg", fileFormat: "ZIP", resolution: "Print ready", orientation: "Mixed", status: "rejected", moderationStatus: "Changes requested", rejectionReason: "Third-party trademark visible", moderatorNote: "Remove the branded equipment mark from two preview graphics and resubmit.", uploadedAt: "2026-07-05", updatedAt: "2026-07-13", downloads: 0, views: 0, revenue: 0, conversion: 0, licenseType: "commercial", planIncluded: false, price: 899, destination: "India", country: "India", tags: ["adventure", "graphics", "content kit"], collectionSlugs: ["adventure-pack"], fileSize: "220 MB" },
  { slug: "tropical-island-route-pack", title: "Tropical Island Route Pack", assetType: "guides", previewImage: "/continents/banners/asia-2.jpg", fileFormat: "PDF", resolution: "Print ready", orientation: "Portrait", status: "published", moderationStatus: "Approved", uploadedAt: "2026-06-28", updatedAt: "2026-07-01", downloads: 940, views: 14800, revenue: 12600, conversion: 6.4, licenseType: "standard", planIncluded: true, price: 699, destination: "Asia", country: "India", tags: ["island", "routes", "guide"], collectionSlugs: ["tropical-destinations"], fileSize: "180 MB" },
  { slug: "creator-reel-template-kit", title: "Creator Reel Template Kit", assetType: "reels", previewImage: "/experiences/weekend.jpg", fileFormat: "MOGRT", duration: "1:20", resolution: "1080p", orientation: "Portrait", status: "archived", moderationStatus: "Previously approved", uploadedAt: "2026-05-20", updatedAt: "2026-06-12", downloads: 4600, views: 54200, revenue: 38200, conversion: 8.1, licenseType: "commercial", planIncluded: true, price: 1999, destination: "Global", country: "India", tags: ["reels", "templates", "social"], collectionSlugs: ["creator-launch-kits"], fileSize: "410 MB" },
  { slug: "jaipur-editorial-photo-set", title: "Jaipur Editorial Photo Set", assetType: "photos", previewImage: "/themes/banners/culture-1.jpg", fileFormat: "TIFF", resolution: "24 MP", orientation: "Mixed", status: "published", moderationStatus: "Approved", uploadedAt: "2026-05-27", updatedAt: "2026-06-02", downloads: 980, views: 16400, revenue: 14700, conversion: 6.0, licenseType: "editorial", planIncluded: true, price: 1499, destination: "Jaipur", country: "India", tags: ["jaipur", "architecture", "culture"], collectionSlugs: ["editorial-city-stories"], fileSize: "940 MB" },
  { slug: "cinematic-travel-lut-pack", title: "Cinematic Travel LUT Pack", assetType: "templates", previewImage: "/experiences/adventure.jpg", fileFormat: "CUBE", resolution: "Preset", orientation: "Mixed", status: "draft", moderationStatus: "Metadata incomplete", uploadedAt: "2026-07-16", updatedAt: "2026-07-16", downloads: 0, views: 0, revenue: 0, conversion: 0, licenseType: "standard", planIncluded: true, price: 799, destination: "Global", country: "India", tags: ["lut", "color", "video"], collectionSlugs: ["creator-launch-kits"], fileSize: "72 MB" },
  { slug: "old-city-food-guide", title: "Old City Food Guide", assetType: "guides", previewImage: "/demo/kerala-cover.jpg", fileFormat: "PDF", resolution: "Digital", orientation: "Portrait", status: "under-review", moderationStatus: "Metadata review", uploadedAt: "2026-07-13", updatedAt: "2026-07-14", downloads: 0, views: 0, revenue: 0, conversion: 0, licenseType: "standard", planIncluded: true, price: 599, destination: "Delhi", country: "India", tags: ["food", "city", "guide"], collectionSlugs: ["editorial-city-stories"], fileSize: "96 MB" },
  { slug: "monsoon-route-map-pack", title: "Monsoon Route Map Pack", assetType: "graphics", previewImage: "/experiences/roadtrip.jpg", fileFormat: "PDF", resolution: "Print ready", orientation: "Mixed", status: "archived", moderationStatus: "Previously approved", uploadedAt: "2026-04-12", updatedAt: "2026-06-18", downloads: 740, views: 11900, revenue: 8100, conversion: 6.2, licenseType: "commercial", planIncluded: false, price: 999, destination: "Western Ghats", country: "India", tags: ["monsoon", "maps", "routes"], collectionSlugs: ["route-packs"], fileSize: "180 MB" },
];

export const managedAssets: StudioManagedAsset[] = fixtures.map((asset, index) => ({ ...asset, id: `studio-asset-${index + 1}`, assetId: `TPL-ASSET-${String(1001 + index)}` }));
export const assetStatusTabs = ["all", "draft", "under-review", "published", "rejected", "archived"] as const;
export const assetStatusLabels: Record<string, string> = { all: "All Assets", draft: "Draft", "under-review": "Under Review", published: "Published", rejected: "Rejected", archived: "Archived" };
export const assetTypeLabels: Record<StudioAssetType, string> = { photos: "Photos", videos: "Videos", reels: "Reels", drone: "Drone Footage", templates: "Templates", graphics: "Graphics", guides: "Destination Guides", audio: "Audio" };
export const licenseLabels: Record<StudioLicenseType, string> = { standard: "Standard", extended: "Extended", editorial: "Editorial", commercial: "Commercial", enterprise: "Enterprise Ready" };
export const assetSortOptions = ["newest", "oldest", "downloads", "revenue", "views", "conversion", "updated", "title-asc", "title-desc"] as const;
export const assetSortLabels: Record<string, string> = { newest: "Newest", oldest: "Oldest", downloads: "Most Downloaded", revenue: "Highest Revenue", views: "Most Viewed", conversion: "Best Conversion", updated: "Recently Updated", "title-asc": "Title A–Z", "title-desc": "Title Z–A" };
export const bulkActions = ["Add to Collection", "Change License", "Submit for Review", "Archive", "Restore", "Duplicate", "Export Metadata", "Delete"];
export const quickActionsByStatus: Record<StudioAssetStatus, string[]> = { draft: ["Continue Editing", "Preview", "Duplicate", "Archive", "Delete"], "under-review": ["View Submission", "Preview", "Withdraw Request", "Duplicate"], published: ["View Public Asset", "View Analytics", "Edit Metadata", "Manage License", "Add to Collection", "Archive"], rejected: ["View Rejection Reason", "Edit and Resubmit", "Duplicate", "Archive"], archived: ["Restore", "Duplicate", "Delete"] };
