export type CreatorMessageCategory = "notifications" | "messages" | "moderation" | "revenue" | "payouts" | "system" | "promotions";
export type CreatorMessagePriority = "critical" | "high" | "normal" | "low";

export interface CreatorMessage {
  id: string; type: string; category: CreatorMessageCategory; priority: CreatorMessagePriority; title: string; preview: string; body: string; sender: string; sentAt: string; timestamp: string; unread: boolean; archived: boolean; keywords: string[];
  asset?: { title: string; id: string; slug: string; image: string }; action?: { label: string; href: string }; timelineStage?: number;
}

export const messageCategories = [
  { id: "all", label: "All", description: "Every communication" }, { id: "notifications", label: "Notifications", description: "Important updates" },
  { id: "messages", label: "Messages", description: "Direct conversations" }, { id: "moderation", label: "Moderation", description: "Publishing reviews" },
  { id: "revenue", label: "Revenue", description: "Earnings insights" }, { id: "payouts", label: "Payouts", description: "Settlement updates" },
  { id: "system", label: "System", description: "Platform notices" }, { id: "promotions", label: "Promotions", description: "Campaign opportunities" },
] as const;

export const creatorMessages: CreatorMessage[] = [
  { id: "MSG-5208", type: "Asset Approved", category: "moderation", priority: "high", title: "Cinematic Ladakh Drone Pack was approved", preview: "Your submission passed quality and compliance review.", body: "Great news. Your latest drone footage passed every required review stage and is ready for its scheduled marketplace release. You can review its public metadata before publishing.", sender: "TPL Moderation Team", sentAt: "12 Jul 2026, 10:42 AM", timestamp: "12m", unread: true, archived: false, keywords: ["approved", "drone", "review"], asset: { title: "Cinematic Ladakh Drone Pack", id: "TPL-CR-10482", slug: "cinematic-ladakh-drone-pack", image: "/experiences/adventure.jpg" }, action: { label: "Open Moderation", href: "/creator-studio/moderation?status=approved" }, timelineStage: 5 },
  { id: "MSG-5204", type: "Changes Requested", category: "moderation", priority: "critical", title: "Action required for Luxury Resort Reel Templates", preview: "Clarify font licensing and add the supported software version.", body: "The review team needs three metadata and licensing updates before this submission can continue. Open the review details for the complete moderator note and return through the existing Upload Wizard.", sender: "TPL Moderation Team", sentAt: "12 Jul 2026, 9:15 AM", timestamp: "1h", unread: true, archived: false, keywords: ["changes", "font", "metadata"], asset: { title: "Luxury Resort Reel Templates", id: "TPL-CR-10479", slug: "luxury-resort-reel-templates", image: "/experiences/luxury.jpg" }, action: { label: "Review Changes", href: "/creator-studio/moderation?status=changes-requested" }, timelineStage: 2 },
  { id: "MSG-5197", type: "Payout Initiated", category: "payouts", priority: "high", title: "Your payout preview is processing", preview: "Settlement CR-PAY-903 is expected by 20 July.", body: "A Creator payout settlement is shown as processing in this preview workspace. The masked payout account and fee breakdown are available in Revenue & Wallet. No real money movement is represented here.", sender: "TPL Creator Finance", sentAt: "11 Jul 2026, 5:30 PM", timestamp: "17h", unread: true, archived: false, keywords: ["payout", "settlement", "bank"], action: { label: "View Revenue", href: "/creator-studio/revenue?tab=payouts" } },
  { id: "MSG-5189", type: "License Purchased", category: "notifications", priority: "normal", title: "Extended license purchased", preview: "A buyer licensed Rajasthan Heritage Portraits.", body: "An Extended License purchase preview has been recorded for your asset. View the asset workspace for performance context and the licensing center for rights information.", sender: "TPL Licensing", sentAt: "11 Jul 2026, 1:08 PM", timestamp: "21h", unread: false, archived: false, keywords: ["license", "purchase", "portrait"], asset: { title: "Rajasthan Heritage Portraits", id: "TPL-CR-10461", slug: "rajasthan-heritage-portraits", image: "/themes/banners/culture-2.jpg" }, action: { label: "View Asset", href: "/creator-studio/assets" } },
  { id: "MSG-5172", type: "Revenue Summary", category: "revenue", priority: "normal", title: "Your weekly revenue summary is ready", preview: "Extended licenses led growth this week.", body: "Your fixture-backed weekly performance summary highlights stronger Extended License activity and continued subscription allocation growth. Open Analytics or Revenue for the complete preview.", sender: "TPL Creator Insights", sentAt: "10 Jul 2026, 8:00 AM", timestamp: "2d", unread: false, archived: false, keywords: ["revenue", "weekly", "growth"], action: { label: "Open Analytics", href: "/creator-studio/analytics" } },
  { id: "MSG-5158", type: "Campaign Invitation", category: "promotions", priority: "high", title: "Invitation: Incredible India summer campaign", preview: "Submit destination visuals for a featured campaign preview.", body: "You are invited to preview a curated tourism campaign opportunity for destination photography and short-form video. Participation and submission actions are not connected in this phase.", sender: "TPL Campaigns", sentAt: "9 Jul 2026, 4:45 PM", timestamp: "3d", unread: true, archived: false, keywords: ["campaign", "invitation", "tourism"], action: { label: "Preview Campaign", href: "/creator-studio/collections" } },
  { id: "MSG-5133", type: "System Maintenance", category: "system", priority: "normal", title: "Planned Creator Studio maintenance", preview: "A maintenance preview is scheduled for Sunday.", body: "Creator Studio may display a short maintenance window in this configuration preview. No live service interruption or notification delivery is scheduled by this implementation.", sender: "TPL System", sentAt: "8 Jul 2026, 11:00 AM", timestamp: "4d", unread: false, archived: false, keywords: ["system", "maintenance", "studio"] },
  { id: "MSG-5119", type: "Policy Update", category: "system", priority: "high", title: "Licensing policy clarification", preview: "Review updated guidance for property releases.", body: "The licensing guidance now includes clearer examples for private property, artwork, hotels, and recognizable architecture. This message links to the existing public Licensing Center.", sender: "TPL Policy Team", sentAt: "7 Jul 2026, 2:20 PM", timestamp: "5d", unread: false, archived: false, keywords: ["policy", "property", "release"], action: { label: "View Licensing", href: "/creators/licensing" } },
  { id: "MSG-5098", type: "Reminder", category: "notifications", priority: "low", title: "Complete your release documentation", preview: "One submission still has a pending property release.", body: "A fixture submission has a pending property release indicator. Open Moderation for its current compliance overview. No real document validation occurs.", sender: "TPL Creator Assistant", sentAt: "5 Jul 2026, 9:10 AM", timestamp: "7d", unread: false, archived: true, keywords: ["reminder", "release", "documentation"], action: { label: "Check Moderation", href: "/creator-studio/moderation" } },
  { id: "MSG-5071", type: "Creator Tip", category: "messages", priority: "low", title: "Improve discoverability with destination tags", preview: "Use specific city and landmark metadata.", body: "Specific destination, city, landmark, season, and experience tags can make asset discovery more useful. Review your metadata in the Asset Manager or Upload Wizard.", sender: "Creator Success Team", sentAt: "2 Jul 2026, 10:00 AM", timestamp: "10d", unread: false, archived: false, keywords: ["tip", "metadata", "discoverability"], action: { label: "Manage Assets", href: "/creator-studio/assets" } },
];

export const messageFilterOptions = { status: ["Unread", "Read"], priority: ["Critical", "High", "Normal", "Low"], category: ["Notifications", "Messages", "Moderation", "Revenue", "Payouts", "System", "Promotions"], date: ["Today", "Last 7 days", "Last 30 days"], archived: ["Active", "Archived"] };
export const messageActivity = ["Asset approval received", "Payout processing update", "Campaign invitation delivered", "Licensing policy reviewed"];
