export type CreatorCollectionConfig = {
  slug: string; title: string; description: string; bannerImage: string; thumbnail: string;
  popularTags: string[]; assetCount: string; creatorCount: string; categoryCount: string;
  updatedLabel: string; searchPlaceholder: string; featuredAssets: string[]; group: "Featured" | "Popular" | "Destination" | "Seasonal" | "Creator" | "Business" | "Trending";
  theme: string; curator: string; editorialPurpose: string; useCases: string[];
};

export const creatorCollectionConfigs: CreatorCollectionConfig[] = [
  { slug: "incredible-india", title: "Incredible India", description: "A vivid editorial journey through landscapes, culture, cities and living heritage.", bannerImage: "/themes/banners/culture-2.jpg", thumbnail: "/themes/banners/culture-1.jpg", popularTags: ["Varanasi", "Rajasthan", "Himalayas", "Kerala", "Jaipur", "Mumbai"], assetCount: "18.4K", creatorCount: "1.2K", categoryCount: "14", updatedLabel: "Updated Daily", searchPlaceholder: "Search in Incredible India...", featuredAssets: ["rajasthan-heritage-portraits", "jaipur-editorial-photo-set", "india-adventure-content-kit", "himalayan-sunrise-aerials"], group: "Featured", theme: "India, culture and destination storytelling", curator: "TPL Creators Team", editorialPurpose: "A broad, high-quality visual library for stories that celebrate the depth and diversity of India.", useCases: ["Tourism campaigns", "Editorial features", "Brand storytelling"] },
  { slug: "himalayan-journeys", title: "Himalayan Journeys", description: "Mountain aerials, road stories and cinematic high-altitude adventures.", bannerImage: "/holidays/manali.jpeg", thumbnail: "/experiences/adventure.jpg", popularTags: ["Leh", "Ladakh", "Sunrise", "Trekking", "Aerial", "Mountains"], assetCount: "7.8K", creatorCount: "620", categoryCount: "9", updatedLabel: "Fresh This Week", searchPlaceholder: "Search Himalayan journeys...", featuredAssets: ["himalayan-sunrise-aerials", "cinematic-ladakh-drone-pack", "india-adventure-content-kit"], group: "Destination", theme: "Mountains, adventure and aerial perspectives", curator: "TPL Adventure Desk", editorialPurpose: "Built for premium mountain narratives and dramatic destination campaigns.", useCases: ["Adventure films", "Destination launches", "Outdoor campaigns"] },
  { slug: "luxury-escapes", title: "Luxury Escapes", description: "Refined resorts, private journeys and elevated hospitality storytelling.", bannerImage: "/experiences/luxury.jpg", thumbnail: "/holidays/goa.jpeg", popularTags: ["Resorts", "Villas", "Spa", "Dining", "Reels", "Tropical"], assetCount: "9.6K", creatorCount: "840", categoryCount: "11", updatedLabel: "Updated Daily", searchPlaceholder: "Search luxury escapes...", featuredAssets: ["luxury-resort-reel-templates", "cinematic-travel-lut-pack", "creator-reel-template-kit"], group: "Business", theme: "Luxury hospitality and premium lifestyle", curator: "TPL Luxury Desk", editorialPurpose: "A polished collection for hospitality brands and elevated travel campaigns.", useCases: ["Hotel campaigns", "Luxury editorials", "Social launches"] },
  { slug: "beaches-of-asia", title: "Beaches of Asia", description: "Turquoise coasts, island routes and sunlit tropical destination assets.", bannerImage: "/continents/banners/asia-2.jpg", thumbnail: "/demo/kerala-cover.jpg", popularTags: ["Maldives", "Goa", "Thailand", "Islands", "Sunset", "Ocean"], assetCount: "12.1K", creatorCount: "970", categoryCount: "10", updatedLabel: "Seasonal Edit", searchPlaceholder: "Search beaches of Asia...", featuredAssets: ["tropical-island-route-pack", "luxury-resort-reel-templates", "cinematic-travel-lut-pack"], group: "Seasonal", theme: "Tropical coasts and island travel", curator: "TPL Asia Desk", editorialPurpose: "A sunlit collection for seasonal escapes, coastal campaigns and island discovery.", useCases: ["Summer campaigns", "Resort content", "Destination guides"] },
  { slug: "wildlife-nature", title: "Wildlife & Nature", description: "Responsible wildlife imagery, forests and inspiring natural landscapes.", bannerImage: "/experiences/wildlife.jpg", thumbnail: "/experiences/spiritual.jpg", popularTags: ["Wildlife", "Forest", "Tiger", "Birds", "Nature", "Conservation"], assetCount: "6.4K", creatorCount: "510", categoryCount: "8", updatedLabel: "Expert Curated", searchPlaceholder: "Search wildlife and nature...", featuredAssets: ["wildlife-of-central-india", "india-adventure-content-kit", "himalayan-sunrise-aerials"], group: "Popular", theme: "Wildlife, landscapes and conservation", curator: "TPL Nature Desk", editorialPurpose: "Curated to support responsible nature storytelling and conservation-led creative work.", useCases: ["Editorial stories", "Conservation campaigns", "Nature documentaries"] },
  { slug: "heritage-cities", title: "Heritage Cities", description: "Architecture, streets, food and cultural detail from historic urban India.", bannerImage: "/themes/banners/culture-3.jpg", thumbnail: "/themes/banners/culture-2.jpg", popularTags: ["Jaipur", "Varanasi", "Jodhpur", "Markets", "Food", "Architecture"], assetCount: "10.7K", creatorCount: "760", categoryCount: "12", updatedLabel: "Updated Daily", searchPlaceholder: "Search heritage cities...", featuredAssets: ["jaipur-editorial-photo-set", "rajasthan-heritage-portraits", "old-city-food-guide"], group: "Destination", theme: "Living heritage and historic cities", curator: "TPL Culture Desk", editorialPurpose: "Made for nuanced cultural, architectural and city-led narratives.", useCases: ["Culture features", "City branding", "Editorial publishing"] },
  { slug: "drone-perspectives", title: "Drone Perspectives", description: "Premium aerial footage and establishing views from remarkable destinations.", bannerImage: "/experiences/adventure.jpg", thumbnail: "/experiences/roadtrip.jpg", popularTags: ["4K", "Aerial", "Mountains", "Coast", "City", "Sunrise"], assetCount: "5.9K", creatorCount: "430", categoryCount: "7", updatedLabel: "Trending Now", searchPlaceholder: "Search drone perspectives...", featuredAssets: ["himalayan-sunrise-aerials", "cinematic-ladakh-drone-pack", "tropical-island-route-pack"], group: "Trending", theme: "Cinematic aerial perspectives", curator: "TPL Motion Desk", editorialPurpose: "Dramatic aerial material for opening shots, films and destination campaigns.", useCases: ["Film openings", "Tourism advertising", "Travel reels"] },
  { slug: "social-media-packs", title: "Social Media Packs", description: "Templates, presets and visual kits for fast, consistent travel publishing.", bannerImage: "/experiences/weekend.jpg", thumbnail: "/continents/banners/asia-1.jpg", popularTags: ["Reels", "Stories", "Templates", "Presets", "Vertical", "Social"], assetCount: "14.2K", creatorCount: "1.4K", categoryCount: "13", updatedLabel: "New Every Day", searchPlaceholder: "Search social media packs...", featuredAssets: ["creator-reel-template-kit", "luxury-resort-reel-templates", "urban-night-mobile-presets", "india-adventure-content-kit"], group: "Creator", theme: "Fast social and creator publishing", curator: "TPL Social Desk", editorialPurpose: "A practical collection for creators and teams producing polished social content at speed.", useCases: ["Social campaigns", "Creator channels", "Brand content"] },
];

const aliases: Record<string, string> = { "himalayan-aerials": "himalayan-journeys", "luxury-travel-reels": "luxury-escapes", "rajasthan-heritage": "heritage-cities", "tropical-destinations": "beaches-of-asia", "urban-india": "heritage-cities", "adventure-pack": "himalayan-journeys", "social-travel-templates": "social-media-packs", "creator-launch-kits": "social-media-packs", "cinematic-india": "incredible-india", "editorial-city-stories": "heritage-cities", "route-packs": "incredible-india" };
export function getCreatorCollectionConfig(slug: string) { const canonical = aliases[slug] ?? slug; const config = creatorCollectionConfigs.find((item) => item.slug === canonical); return config ? { ...config, slug } : undefined; }
