import { CheckCircle2, FilePlus2, ShieldCheck } from "lucide-react";
import { uploadLicenseOptions, type UploadWizardDraft } from "@/app/lib/creators/creatorUploadWizardData";
import { UploadField, UploadStepIntro } from "./CreatorUploadFields";

export function CreatorUploadLicenseStep({ data, error, update }: { data: UploadWizardDraft; error?: string; update: (patch: Partial<UploadWizardDraft>) => void }) {
  return <div><UploadStepIntro step="Step 5 · Usage rights" title="Choose the licensing path" copy="Select the primary license positioning buyers should see. Final eligibility remains subject to moderation and release review." /><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{uploadLicenseOptions.map(({ key, title, description, icon: Icon, tone }) => <button type="button" key={key} onClick={() => update({ license: key })} className={`relative min-h-40 rounded-2xl border-2 p-5 text-left shadow-sm ${data.license === key ? tone : "border-slate-200 bg-white text-slate-800"}`}>{data.license === key && <CheckCircle2 className="absolute right-4 top-4 h-5 w-5" />}<Icon className="h-6 w-6" /><h2 className="mt-4 text-lg font-bold">{title}</h2><p className="mt-2 text-sm font-medium text-slate-600">{description}</p></button>)}</div>{error && <p className="mt-4 rounded-lg bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-800">{error}</p>}<div className="mt-5 flex gap-3 rounded-xl bg-blue-50 p-4 text-sm font-semibold text-blue-900"><ShieldCheck className="h-5 w-5 shrink-0" />License selection is a publishing preview. It does not create rights, pricing or entitlements.</div></div>;
}

export function CreatorUploadPricingStep({ data, update }: { data: UploadWizardDraft; update: (patch: Partial<UploadWizardDraft>) => void }) {
  return <div><UploadStepIntro step="Step 6 · Price positioning" title="Preview how buyers will license it" copy="Configure marketplace price signals for moderation review. No checkout, payment or payout calculation is connected." /><div className="mt-7 grid gap-5 lg:grid-cols-[1fr_320px]"><section className="grid gap-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7 md:grid-cols-2"><label className="flex items-start gap-3 rounded-xl border border-slate-200 p-4 md:col-span-2"><input type="checkbox" checked={data.subscriptionIncluded} onChange={(event) => update({ subscriptionIncluded: event.target.checked })} className="mt-1 h-5 w-5" /><span><strong className="block text-sm">Subscription Included</strong><span className="mt-1 block text-xs font-medium text-slate-600">Show this asset as included with eligible Creator plans.</span></span></label><UploadField label="License From (₹)" inputMode="numeric" value={data.licenseFrom} onChange={(event) => update({ licenseFrom: event.target.value })} /><UploadField label="Suggested Price (₹)" inputMode="numeric" value={data.suggestedPrice} onChange={(event) => update({ suggestedPrice: event.target.value })} /><UploadField label="Commercial Price (₹)" inputMode="numeric" value={data.commercialPrice} onChange={(event) => update({ commercialPrice: event.target.value })} /><label className="flex items-start gap-3 rounded-xl bg-violet-50 p-4"><input type="checkbox" checked={data.enterpriseContact} onChange={(event) => update({ enterpriseContact: event.target.checked })} className="mt-1 h-5 w-5" /><span><strong className="block text-sm text-violet-900">Enterprise Contact</strong><span className="mt-1 block text-xs font-medium text-violet-800">Allow custom rights inquiries.</span></span></label></section><aside className="rounded-2xl bg-[#071831] p-5 text-white shadow-xl"><p className="text-xs font-bold uppercase tracking-wide text-blue-200">Buyer preview</p><h2 className="mt-2 text-white">Pricing summary</h2><dl className="mt-5 space-y-4"><div><dt className="text-xs font-semibold text-slate-300">Plan access</dt><dd className="mt-1 font-bold">{data.subscriptionIncluded ? "Included" : "Not included"}</dd></div><div><dt className="text-xs font-semibold text-slate-300">License from</dt><dd className="mt-1 text-2xl font-extrabold">₹{data.licenseFrom || "—"}</dd></div><div><dt className="text-xs font-semibold text-slate-300">Commercial</dt><dd className="mt-1 font-bold">₹{data.commercialPrice || "—"}</dd></div><div><dt className="text-xs font-semibold text-slate-300">Enterprise</dt><dd className="mt-1 font-bold">{data.enterpriseContact ? "Contact enabled" : "Unavailable"}</dd></div></dl><p className="mt-6 rounded-xl bg-white/10 p-3 text-xs font-semibold text-slate-200">Static preview calculation only.</p></aside></div></div>;
}

export function CreatorUploadReleasesStep({ data, errors, update }: { data: UploadWizardDraft; errors: Record<string, string>; update: (patch: Partial<UploadWizardDraft>) => void }) {
  const releaseCards = [{ key: "modelRelease" as const, title: "Model Release", copy: "Add when recognizable people require commercial permission." }, { key: "propertyRelease" as const, title: "Property Release", copy: "Add for private property, protected interiors or artwork when needed." }];
  return <div><UploadStepIntro step="Step 7 · Rights readiness" title="Confirm releases and ownership" copy="Make moderation requirements clear before submission. Release upload controls are placeholders and accept no files." /><div className="mt-7 grid gap-5 lg:grid-cols-2">{releaseCards.map(({ key, title, copy }) => <article key={key} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-700"><FilePlus2 className="h-5 w-5" /></span><h2 className="mt-4">{title}</h2><p className="mt-2 text-sm font-medium text-slate-600">{copy}</p><button type="button" onClick={() => update({ [key]: !data[key] })} className={`mt-5 min-h-11 rounded-lg border px-4 py-2 font-bold ${data[key] ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-slate-300 bg-white text-slate-700"}`}>{data[key] ? "Preview release attached" : "Add release placeholder"}</button></article>)}</div><div className="mt-5 space-y-3">{[{ key: "commercialEligibility" as const, title: "Commercial eligibility", copy: "I confirm this asset and its release status are suitable for the selected commercial positioning." }, { key: "ownershipDeclaration" as const, title: "Ownership declaration", copy: "I created this work or control all rights required to submit it." }].map(({ key, title, copy }) => <label key={key} className={`flex items-start gap-3 rounded-xl border bg-white p-4 ${errors[key] ? "border-rose-400" : "border-slate-200"}`}><input type="checkbox" checked={data[key]} onChange={(event) => update({ [key]: event.target.checked })} className="mt-1 h-5 w-5" /><span><strong className="block text-sm">{title}</strong><span className="mt-1 block text-xs font-medium text-slate-600">{copy}</span>{errors[key] && <span className="mt-1 block text-xs font-semibold text-rose-700">{errors[key]}</span>}</span></label>)}</div></div>;
}
