import Image from "next/image";
import { AlertTriangle, CheckCircle2, Clock3, ShieldCheck } from "lucide-react";
import { uploadReviewTimeline, uploadTypes, type UploadWizardDraft } from "@/app/lib/creators/creatorUploadWizardData";
import { UploadStepIntro } from "./CreatorUploadFields";

export function CreatorUploadPreviewStep({ data, warnings }: { data: UploadWizardDraft; warnings: string[] }) {
  const type = uploadTypes.find((item) => item.key === data.type);
  return <div><UploadStepIntro step="Step 8 · Buyer experience" title="Preview your marketplace listing" copy="Review exactly how key metadata, licensing, pricing and creator attribution will appear before moderation." /><div className="mt-7 grid gap-6 xl:grid-cols-[1fr_340px]"><article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-lg"><div className="relative aspect-[16/9] overflow-hidden bg-slate-100"><Image src="/themes/banners/culture-2.jpg" alt="Buyer-facing asset preview" fill sizes="(min-width:1280px) 50vw, 100vw" className="object-cover" /><span className="absolute left-4 top-4 rounded bg-[#071831]/90 px-3 py-1.5 text-xs font-bold uppercase text-white">{type?.label ?? "Asset"}</span></div><div className="p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-wide text-blue-700">{data.destination || "Destination"} · {data.country}</p><h2 className="mt-2 text-xl font-extrabold">{data.title || "Untitled creator asset"}</h2><p className="mt-3 text-sm font-medium text-slate-600">{data.description || "A helpful buyer-facing description will appear here."}</p><div className="mt-4 flex flex-wrap gap-2">{data.keywords.map((keyword) => <span key={keyword} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700">#{keyword}</span>)}</div><div className="mt-5 grid gap-3 border-t border-slate-200 pt-4 sm:grid-cols-3"><div><span className="text-xs font-medium text-slate-500">License</span><strong className="mt-1 block text-sm capitalize">{data.license || "Not selected"}</strong></div><div><span className="text-xs font-medium text-slate-500">Price from</span><strong className="mt-1 block text-sm">₹{data.licenseFrom || "—"}</strong></div><div><span className="text-xs font-medium text-slate-500">Creator</span><strong className="mt-1 block text-sm">Aira Studio</strong></div></div></div></article><aside className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2>Validation summary</h2><div className="mt-4 space-y-3">{["File preview ready", "Core metadata complete", `${data.keywords.length} keywords selected`, `${data.license || "No"} license positioning`, "Ownership confirmed"].map((item) => <p key={item} className="flex gap-2 text-sm font-semibold text-slate-700"><CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-600" />{item}</p>)}</div></section>{warnings.length > 0 && <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-700" /><h2 className="text-lg text-amber-950">Warnings</h2></div><ul className="mt-3 space-y-2">{warnings.map((warning) => <li key={warning} className="text-sm font-semibold text-amber-900">• {warning}</li>)}</ul></section>}</aside></div></div>;
}

export function CreatorUploadSubmittedStep({ onStudio }: { onStudio: () => void }) {
  return <div className="mx-auto max-w-4xl py-6 text-center"><span className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-emerald-100 text-emerald-700 ring-8 ring-emerald-50"><CheckCircle2 className="h-10 w-10" /></span><p className="mt-7 text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Submitted for moderation</p><h1 className="mt-2">Your content preview is in the review queue</h1><p className="mx-auto mt-4 max-w-2xl font-medium text-slate-600">The wizard reached its submitted state locally. No file, metadata, license or publishing request was sent to TPL.</p><div className="mt-8 grid gap-3 text-left sm:grid-cols-2 lg:grid-cols-4">{uploadReviewTimeline.map((item, index) => <div key={item} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><span className="grid h-8 w-8 place-items-center rounded-full bg-blue-50 text-sm font-bold text-blue-700">{index + 1}</span><p className="mt-3 text-sm font-semibold">{item}</p></div>)}</div><div className="mt-7 inline-flex items-center gap-2 rounded-xl bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-900"><Clock3 className="h-4 w-4" />Expected approval preview: 2–5 business days</div><div className="mt-7"><button type="button" onClick={onStudio} className="min-h-11 rounded-lg bg-blue-600 px-6 py-3 font-bold text-white">Return to Studio</button></div><p className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-slate-600"><ShieldCheck className="h-4 w-4 text-emerald-600" />No real moderation or publishing occurred.</p></div>;
}
