import Image from "next/image";
import { CheckCircle2, FileCheck2, FolderOpen, UploadCloud } from "lucide-react";
import { uploadTypes, type UploadWizardDraft } from "@/app/lib/creators/creatorUploadWizardData";
import { UploadStepIntro } from "./CreatorUploadFields";

export function CreatorUploadTypeStep({ data, error, update }: { data: UploadWizardDraft; error?: string; update: (patch: Partial<UploadWizardDraft>) => void }) {
  return <div><UploadStepIntro step="Step 1 · Content format" title="What are you publishing?" copy="Choose one primary asset type so technical, licensing and buyer-preview fields stay relevant." /><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{uploadTypes.map(({ key, label, description, formats, icon: Icon }) => <button type="button" key={key} onClick={() => update({ type: key, filesReady: false, fileName: "" })} className={`relative min-h-44 rounded-2xl border-2 p-5 text-left shadow-sm transition hover:-translate-y-0.5 ${data.type === key ? "border-blue-600 bg-blue-50" : "border-slate-200 bg-white hover:border-blue-300"}`}>{data.type === key && <CheckCircle2 className="absolute right-4 top-4 h-5 w-5 text-blue-700" />}<span className="grid h-11 w-11 place-items-center rounded-xl bg-[#071831] text-blue-200"><Icon className="h-5 w-5" /></span><h2 className="mt-4 text-lg font-bold">{label}</h2><p className="mt-2 text-sm font-medium text-slate-600">{description}</p><p className="mt-3 text-xs font-semibold text-blue-700">{formats}</p></button>)}</div>{error && <p className="mt-4 rounded-lg bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-800">{error}</p>}</div>;
}

export function CreatorUploadFilesStep({ data, error, update }: { data: UploadWizardDraft; error?: string; update: (patch: Partial<UploadWizardDraft>) => void }) {
  const mockName = data.type === "photos" ? "ladakh-sunrise-hero.jpg" : data.type === "templates" ? "travel-social-template-pack.zip" : `${data.type || "creator"}-preview-file.mp4`;
  return <div><UploadStepIntro step="Step 2 · Source files" title="Add your files" copy="Use the premium drop zone to preview file selection, thumbnails and processing status. No file is read or uploaded." /><div className={`mt-7 rounded-3xl border-2 border-dashed p-7 text-center ${error ? "border-rose-400 bg-rose-50/40" : "border-blue-300 bg-blue-50/40"}`}><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-blue-600 text-white shadow-lg"><UploadCloud className="h-7 w-7" /></span><h2 className="mt-5">Drag &amp; drop your {data.type || "content"} files</h2><p className="mt-2 text-sm font-medium text-slate-600">Preview only · supported formats depend on the chosen upload type.</p><button type="button" onClick={() => update({ filesReady: true, fileName: mockName })} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#071831] px-5 py-3 font-bold text-white"><FolderOpen className="h-4 w-4" />Browse Files</button>{error && <p className="mt-3 text-sm font-semibold text-rose-700">{error}</p>}</div>{data.filesReady && <article className="mt-5 grid gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-[140px_1fr] sm:items-center"><div className="relative aspect-video overflow-hidden rounded-xl bg-slate-100"><Image src="/themes/banners/culture-2.jpg" alt="Selected file preview" fill sizes="140px" className="object-cover" /></div><div><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{data.fileName}</h3><p className="mt-1 text-xs font-medium text-slate-600">48.2 MB · preview file · no bytes transferred</p></div><FileCheck2 className="h-5 w-5 text-emerald-600" /></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full w-full rounded-full bg-emerald-500" /></div><p className="mt-2 text-xs font-semibold text-emerald-700">Preview processing complete</p></div></article>}</div>;
}
