import Link from "next/link";
import { ArrowLeft, CheckCircle2, Sparkles } from "lucide-react";
import { studioPlaceholderMeta } from "@/app/lib/creators/creatorStudioData";

export default function CreatorStudioPlaceholder({ section }: { section: string }) {
  const meta = studioPlaceholderMeta[section];
  if (!meta) return null;
  const Icon = meta.icon;
  return <div className="space-y-6"><section><p className="text-xs font-bold uppercase tracking-[0.15em] text-blue-700">Creator Studio module</p><h1 className="mt-2">{meta.title}</h1><p className="mt-2 max-w-3xl font-medium text-slate-600">{meta.description}</p></section><section className="relative overflow-hidden rounded-3xl border border-slate-200 bg-white px-6 py-16 text-center shadow-sm"><div className="absolute left-1/2 top-0 h-40 w-72 -translate-x-1/2 rounded-full bg-blue-100 blur-3xl" /><div className="relative"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-[#071831] text-blue-200 shadow-xl"><Icon className="h-7 w-7" /></span><p className="mt-6 text-xs font-bold uppercase tracking-[0.15em] text-blue-700">Shell-ready placeholder</p><h2 className="mt-2">{meta.title} is ready for its dedicated phase</h2><p className="mx-auto mt-3 max-w-xl font-medium text-slate-600">B11 establishes navigation, responsive structure and premium empty-state guidance only. No business workflow or mutation has been implemented here.</p><div className="mx-auto mt-6 grid max-w-2xl gap-3 text-left sm:grid-cols-3">{["Shared Studio layout", "Responsive navigation", "Future module mount point"].map((item) => <div key={item} className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-sm font-semibold text-slate-700"><CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-600" />{item}</div>)}</div>{meta.relatedHref && <Link href={meta.relatedHref} className="mt-7 mr-2 inline-flex min-h-11 items-center rounded-lg bg-blue-600 px-5 py-3 font-bold text-white">{meta.relatedLabel}</Link>}<Link href="/creator-studio" className="mt-7 inline-flex min-h-11 items-center gap-2 rounded-lg bg-blue-600 px-5 py-3 font-bold text-white hover:bg-blue-500"><ArrowLeft className="h-4 w-4" />Back to Dashboard</Link></div></section><section className="flex items-start gap-3 rounded-xl border border-violet-200 bg-violet-50 p-4 text-sm font-semibold text-violet-900"><Sparkles className="mt-0.5 h-5 w-5 shrink-0" />This placeholder deliberately prevents feature creep while proving the reusable shell can support future Studio modules.</section></div>;
}
