import Link from "next/link";
import { HelpCircle, Sparkles, X } from "lucide-react";
import { studioNavigation } from "@/app/lib/creators/creatorStudioData";

export default function CreatorStudioSidebar({ pathname, open, onClose, onUpgrade }: { pathname: string; open: boolean; onClose: () => void; onUpgrade: () => void }) {
  const isActive = (href: string) => href === "/creator-studio" ? pathname === href : pathname.startsWith(href);
  const content = <div className="flex h-full flex-col bg-[#071831] text-white"><div className="border-b border-white/10 p-5"><Link href="/creator-studio" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600 text-xs font-extrabold">TPL</span><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-blue-200">Creator</p><h1 className="text-lg font-extrabold text-white">Studio</h1></div></Link><button type="button" onClick={onClose} aria-label="Close Studio navigation" className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-lg border border-white/15 lg:hidden"><X className="h-5 w-5" /></button><div className="mt-6 flex items-center gap-3 rounded-xl bg-white/10 p-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-violet-500 font-extrabold">AS</div><div className="min-w-0"><p className="truncate text-sm font-bold">Aira Studio</p><span className="mt-1 inline-flex rounded-full bg-violet-400/20 px-2 py-0.5 text-xs font-semibold text-violet-100">Creator Plan</span></div></div></div><nav aria-label="Creator Studio" className="flex-1 space-y-1 overflow-y-auto p-3">{studioNavigation.map(({ href, label, icon: Icon, badge }) => <Link key={href} href={href} onClick={onClose} aria-current={isActive(href) ? "page" : undefined} className={`flex min-h-10 items-center gap-3 rounded-lg px-3 py-2 text-sm font-semibold transition ${isActive(href) ? "bg-white text-[#071831] shadow" : "text-slate-200 hover:bg-white/10 hover:text-white"}`}><Icon className="h-4 w-4 shrink-0" /><span className="flex-1">{label}</span>{badge && <span className={`rounded-full px-2 py-0.5 text-xs font-bold ${isActive(href) ? "bg-blue-100 text-blue-800" : "bg-white/15 text-white"}`}>{badge}</span>}</Link>)}<Link href="/creator-studio/settings" className="flex min-h-10 items-center gap-3 rounded-lg px-3 py-2 text-sm font-semibold text-slate-200 hover:bg-white/10"><HelpCircle className="h-4 w-4" />Help &amp; Support</Link></nav><div className="border-t border-white/10 p-4"><div className="rounded-xl bg-white/10 p-4"><div className="flex items-center justify-between text-xs font-semibold text-slate-200"><span>Storage</span><span>6.4 / 25 GB</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full w-[26%] rounded-full bg-blue-400" /></div></div><button type="button" onClick={onUpgrade} className="mt-3 flex min-h-10 w-full items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white hover:bg-blue-500"><Sparkles className="h-4 w-4" />Upgrade Plan</button></div></div>;
  return <><aside className="fixed inset-y-0 left-0 z-40 hidden w-[260px] lg:block">{content}</aside>{open && <div className="fixed inset-0 z-50 lg:hidden"><button type="button" onClick={onClose} aria-label="Close Studio navigation backdrop" className="absolute inset-0 bg-slate-950/60" /><aside className="absolute inset-y-0 left-0 w-[min(88vw,340px)] shadow-2xl">{content}</aside></div>}</>;
}
