import { BadgeCheck, Building2, CreditCard, Landmark, MailCheck, ShieldCheck, Smartphone } from "lucide-react";
import type { CreatorOnboardingDraft } from "@/app/lib/creators/creatorOnboardingData";
import { Field, SelectField, StepIntro } from "./CreatorOnboardingFields";

export function CreatorIdentityStep({ data, update }: { data: CreatorOnboardingDraft; update: (patch: Partial<CreatorOnboardingDraft>) => void }) {
  return <div><StepIntro eyebrow="Step 4 · Verification preview" title="Confirm your identity" copy="Identity checks protect creators, buyers and payouts. No document is uploaded or verified in this preview flow." /><div className="mt-8 grid gap-5 lg:grid-cols-[1fr_.7fr]"><div className="grid gap-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7 md:grid-cols-2"><SelectField label="Government ID type" value={data.governmentId} onChange={(event) => update({ governmentId: event.target.value })}><option value="">Select ID type</option><option>Passport</option><option>Driving Licence</option><option>National ID</option><option>Aadhaar · masked preview</option></SelectField><Field label="Identity status" value={data.identityStatus} readOnly /><Field label="Email" type="email" value={data.email} onChange={(event) => update({ email: event.target.value })} placeholder="creator@example.com" /><Field label="Phone" type="tel" value={data.phone} onChange={(event) => update({ phone: event.target.value })} placeholder="+91 98XXXXXX00" /></div><aside className="rounded-2xl bg-[#071831] p-6 text-white shadow-xl"><ShieldCheck className="h-8 w-8 text-blue-300" /><h2 className="mt-4 text-white">Your identity stays protected</h2><p className="mt-3 text-sm font-medium text-slate-200">Future verification will use secure, approved providers. TPL will never display identity documents on your public profile.</p><div className="mt-5 space-y-3 text-sm font-semibold text-slate-100"><p className="flex gap-2"><MailCheck className="h-4 w-4 text-blue-300" />Email and phone confirmation</p><p className="flex gap-2"><BadgeCheck className="h-4 w-4 text-blue-300" />Private verification status</p></div></aside></div></div>;
}

export function CreatorTaxStep({ data, update }: { data: CreatorOnboardingDraft; update: (patch: Partial<CreatorOnboardingDraft>) => void }) {
  return <div><StepIntro eyebrow="Step 5 · Tax profile preview" title="Set up your tax profile" copy="Provide the structure your future earnings records may require. Nothing is submitted to a tax authority in this phase." /><div className="mt-8 grid gap-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7 md:grid-cols-2"><SelectField label="Tax country" value={data.taxCountry} onChange={(event) => update({ taxCountry: event.target.value })}><option>India</option><option>United States</option><option>United Kingdom</option><option>United Arab Emirates</option><option>Singapore</option><option>Other</option></SelectField><div><span className="text-sm font-semibold text-slate-800">Account type</span><div className="mt-1.5 grid grid-cols-2 gap-3">{(["individual", "business"] as const).map((value) => <button type="button" key={value} onClick={() => update({ taxType: value })} className={`min-h-11 rounded-lg border px-4 py-2 text-sm font-bold capitalize ${data.taxType === value ? "border-blue-600 bg-blue-50 text-blue-800" : "border-slate-300 bg-white text-slate-700"}`}>{value}</button>)}</div></div><Field label="PAN" value={data.pan} onChange={(event) => update({ pan: event.target.value })} placeholder="Preview only" /><Field label="GST / VAT" value={data.gstVat} onChange={(event) => update({ gstVat: event.target.value })} placeholder="Optional preview" /><Field label="TIN" value={data.tin} onChange={(event) => update({ tin: event.target.value })} placeholder="If applicable" /><div className="flex items-center gap-3 rounded-xl bg-amber-50 p-4 text-sm font-semibold text-amber-900"><Building2 className="h-5 w-5 shrink-0" />Business documentation requirements vary by country.</div></div></div>;
}

export function CreatorPayoutStep({ data, update }: { data: CreatorOnboardingDraft; update: (patch: Partial<CreatorOnboardingDraft>) => void }) {
  const methods = [{ key: "bank", label: "Bank", icon: Landmark }, { key: "upi", label: "UPI", icon: Smartphone }, { key: "paypal", label: "PayPal · future", icon: CreditCard }, { key: "wise", label: "Wise · future", icon: CreditCard }] as const;
  return <div><StepIntro eyebrow="Step 6 · Earnings destination" title="Choose a payout preference" copy="Preview how creator earnings could be routed after verification. No bank, UPI or provider connection is made." /><div className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{methods.map(({ key, label, icon: Icon }) => <button type="button" key={key} onClick={() => update({ payoutMethod: key })} className={`min-h-24 rounded-xl border p-4 text-left ${data.payoutMethod === key ? "border-blue-600 bg-blue-50 text-blue-800" : "border-slate-200 bg-white text-slate-700"}`}><Icon className="h-5 w-5" /><span className="mt-3 block text-sm font-bold">{label}</span></button>)}</div><div className="mt-6 grid gap-5 md:grid-cols-2">{data.payoutMethod === "bank" && <><Field label="Bank name" value={data.bankName} onChange={(event) => update({ bankName: event.target.value })} placeholder="Preview bank" /><Field label="Masked account reference" value={data.accountReference} onChange={(event) => update({ accountReference: event.target.value })} placeholder="XXXX 1234" /></>}{data.payoutMethod === "upi" && <Field label="UPI ID" value={data.upiId} onChange={(event) => update({ upiId: event.target.value })} placeholder="creator@upi" />}{(data.payoutMethod === "paypal" || data.payoutMethod === "wise") && <div className="md:col-span-2 rounded-xl bg-slate-100 p-5 text-sm font-semibold text-slate-700">{data.payoutMethod === "paypal" ? "PayPal" : "Wise"} support is a future option and is not connected in this preview.</div>}</div></div></div>;
}
