"use client";

import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowLeft, ArrowRight, RotateCcw, Save } from "lucide-react";
import { useAuth } from "@/app/hooks/useAuth";
import { initialOnboardingDraft, onboardingSteps, type CreatorOnboardingDraft, type OnboardingStepKey } from "@/app/lib/creators/creatorOnboardingData";
import CreatorMarketplaceHeader from "../CreatorMarketplaceHeader";
import CreatorMarketplaceFooter from "../CreatorMarketplaceFooter";
import typography from "../CreatorTypography.module.css";
import CreatorStepper from "./CreatorStepper";
import { CreatorBenefitsStep, CreatorEligibilityStep } from "./CreatorBenefitsEligibilitySteps";
import CreatorProfileStep from "./CreatorProfileStep";
import { CreatorIdentityStep, CreatorPayoutStep, CreatorTaxStep } from "./CreatorComplianceSteps";
import { CreatorAgreementStep, CreatorPortfolioStep } from "./CreatorPortfolioAgreementSteps";
import { CreatorReviewStep, CreatorSubmittedStep } from "./CreatorReviewSubmittedSteps";

const draftKey = "tpl-creator-onboarding-preview";

export default function CreatorOnboardingPage() {
  const router = useRouter(); const params = useSearchParams(); const { user, isAuthenticated, openLoginModal } = useAuth();
  const requested = params.get("step") as OnboardingStepKey | null; const requestedIndex = requested ? onboardingSteps.findIndex((item) => item.key === requested) : 0;
  const [current, setCurrent] = useState(requestedIndex >= 0 ? requestedIndex : 0); const [data, setData] = useState<CreatorOnboardingDraft>(initialOnboardingDraft); const [errors, setErrors] = useState<Record<string, string>>({}); const [notice, setNotice] = useState("");
  const studio = () => isAuthenticated && user ? router.push("/creator-studio") : openLoginModal();
  const update = (patch: Partial<CreatorOnboardingDraft>) => { setData((value) => ({ ...value, ...patch })); setErrors((value) => { const next = { ...value }; Object.keys(patch).forEach((key) => delete next[key]); return next; }); };
  const go = (index: number) => { const safe = Math.max(0, Math.min(index, onboardingSteps.length - 1)); setCurrent(safe); const step = onboardingSteps[safe].key; router.replace(step === "benefits" ? "/creators/onboarding" : `/creators/onboarding?step=${step}`, { scroll: false }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const validate = () => { const next: Record<string, string> = {}; const step = onboardingSteps[current].key; if (step === "profile") { if (!data.displayName.trim()) next.displayName = "Enter a creator display name."; if (!/^[a-z0-9-]{3,}$/.test(data.username)) next.username = "Use at least 3 lowercase letters, numbers or hyphens."; if (data.bio.trim().length < 30) next.bio = "Add at least 30 characters about your creative work."; if (!data.location.trim()) next.location = "Add your location."; if (!data.primaryCategory) next.primaryCategory = "Choose a primary category."; } if (step === "agreement") { if (!data.creatorAgreement) next.creatorAgreement = "Required to continue."; if (!data.licensingAgreement) next.licensingAgreement = "Required to continue."; if (!data.communityGuidelines) next.communityGuidelines = "Required to continue."; } setErrors(next); if (Object.keys(next).length) { setNotice("Please review the highlighted fields before continuing."); return false; } setNotice(""); return true; };
  const save = () => { window.localStorage.setItem(draftKey, JSON.stringify({ data, current })); setNotice("Draft saved in this browser only. Nothing was sent to TPL."); };
  const resume = () => { const raw = window.localStorage.getItem(draftKey); if (!raw) return setNotice("No local preview draft was found on this browser."); try { const parsed = JSON.parse(raw) as { data?: CreatorOnboardingDraft; current?: number }; if (parsed.data) setData({ ...initialOnboardingDraft, ...parsed.data }); if (typeof parsed.current === "number") go(Math.min(parsed.current, 8)); setNotice("Local preview draft restored."); } catch { setNotice("The local preview draft could not be restored."); } };
  const next = () => { if (validate()) go(current + 1); }; const submit = () => { if (!data.creatorAgreement || !data.licensingAgreement || !data.communityGuidelines) return setNotice("Return to Agreement and complete every confirmation before submitting."); window.localStorage.removeItem(draftKey); go(9); };
  const key = onboardingSteps[current].key;
  return <div className={`${typography.scope} min-h-screen overflow-x-clip bg-slate-50 text-slate-950`}><CreatorMarketplaceHeader onStudio={studio} userName={user?.fullName ?? user?.email ?? "Account"} /><CreatorStepper current={current} /><main className="mx-auto max-w-[1240px] px-4 py-8 sm:px-6 lg:px-10 lg:py-12">{key === "benefits" && <CreatorBenefitsStep />}{key === "eligibility" && <CreatorEligibilityStep />}{key === "profile" && <CreatorProfileStep data={data} errors={errors} update={update} />}{key === "identity" && <CreatorIdentityStep data={data} update={update} />}{key === "tax" && <CreatorTaxStep data={data} update={update} />}{key === "payout" && <CreatorPayoutStep data={data} update={update} />}{key === "portfolio" && <CreatorPortfolioStep data={data} update={update} />}{key === "agreement" && <CreatorAgreementStep data={data} errors={errors} update={update} />}{key === "review" && <CreatorReviewStep data={data} onEdit={(step) => go(onboardingSteps.findIndex((item) => item.key === step))} />}{key === "submitted" && <CreatorSubmittedStep onTrack={() => setNotice("Application tracking preview opened — no backend application exists.")} onMarketplace={() => router.push("/creators")} />}{notice && <p role="status" className={`mt-6 rounded-xl px-4 py-3 text-sm font-semibold ${Object.keys(errors).length ? "bg-rose-50 text-rose-800" : "bg-blue-50 text-blue-800"}`}>{notice}</p>}{key !== "submitted" && <footer className="mt-10 flex flex-col-reverse gap-3 border-t border-slate-200 pt-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-col gap-2 sm:flex-row"><button type="button" onClick={save} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2 font-bold text-slate-800"><Save className="h-4 w-4" />Save Draft</button><button type="button" onClick={resume} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg px-4 py-2 font-bold text-blue-700 hover:bg-blue-50"><RotateCcw className="h-4 w-4" />Resume Draft</button></div><div className="flex gap-2"><button type="button" disabled={current === 0} onClick={() => go(current - 1)} className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-5 py-2 font-bold text-slate-800 disabled:opacity-40 sm:flex-none"><ArrowLeft className="h-4 w-4" />Previous</button>{key === "review" ? <button type="button" onClick={submit} className="min-h-11 flex-1 rounded-lg bg-emerald-600 px-6 py-2 font-bold text-white sm:flex-none">Submit Application</button> : <button type="button" onClick={next} className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-lg bg-blue-600 px-6 py-2 font-bold text-white sm:flex-none">Save &amp; Continue <ArrowRight className="h-4 w-4" /></button>}</div></footer>}</main><CreatorMarketplaceFooter onStudio={studio} /></div>;
}
