import { CheckCircle2, FileText } from "lucide-react";
import type { CreatorOnboardingDraft } from "@/app/lib/creators/creatorOnboardingData";
import { Field, StepIntro, TextareaField } from "./CreatorOnboardingFields";

export function CreatorPortfolioStep({ data, update }: { data: CreatorOnboardingDraft; update: (patch: Partial<CreatorOnboardingDraft>) => void }) {
  return <div><StepIntro eyebrow="Step 7 · Creative expertise" title="Show us your portfolio" copy="Share the experience, tools and destinations that shape your strongest work. Example uploads remain disabled." /><div className="mt-8 grid gap-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7 md:grid-cols-2"><Field label="Experience" value={data.experience} onChange={(event) => update({ experience: event.target.value })} placeholder="5 years travel photography" /><Field label="Specializations" value={data.specializations} onChange={(event) => update({ specializations: event.target.value })} placeholder="Aerial, editorial, hospitality" /><Field label="Equipment" value={data.equipment} onChange={(event) => update({ equipment: event.target.value })} placeholder="Camera, drone, lenses" /><Field label="Software" value={data.software} onChange={(event) => update({ software: event.target.value })} placeholder="Lightroom, Premiere Pro" /><div className="md:col-span-2"><TextareaField label="Portfolio links" value={data.portfolioLinks} onChange={(event) => update({ portfolioLinks: event.target.value })} placeholder="One link per line" /></div><Field label="Travel destinations" value={data.destinations} onChange={(event) => update({ destinations: event.target.value })} placeholder="Ladakh, Rajasthan, Kerala" /><Field label="Example work" value={data.exampleWork} onChange={(event) => update({ exampleWork: event.target.value })} placeholder="Describe your strongest series" help="Upload processing is intentionally unavailable in B10." /></div></div>;
}

export function CreatorAgreementStep({ data, errors, update }: { data: CreatorOnboardingDraft; errors: Record<string, string>; update: (patch: Partial<CreatorOnboardingDraft>) => void }) {
  const agreements = [{ key: "creatorAgreement" as const, label: "Creator Agreement", copy: "I confirm I own or control the rights required for work I submit." }, { key: "licensingAgreement" as const, label: "Licensing Agreement", copy: "I understand that approved assets may be offered under TPL licensing tiers." }, { key: "communityGuidelines" as const, label: "Community Guidelines", copy: "I agree to authenticity, safety, respect and marketplace quality standards." }];
  return <div><StepIntro eyebrow="Step 8 · Agreements" title="Review the creator commitments" copy="These preview agreements show the structure of future onboarding. No legal acceptance is transmitted in B10." /><div className="mt-8 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><article className="max-h-[430px] overflow-y-auto rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><FileText className="h-6 w-6 text-blue-700" /><h2>Agreement preview</h2></div>{["Ownership and authority", "Marketplace quality", "Licensing participation", "Model and property releases", "Prohibited content", "Creator conduct", "Earnings and reporting", "Account integrity"].map((title) => <section key={title} className="mt-5"><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm font-medium text-slate-600">You agree to provide accurate information and only submit eligible original work. Final contractual language will be presented before real onboarding is enabled.</p></section>)}</article><div className="space-y-3">{agreements.map(({ key, label, copy }) => <label key={key} className={`flex cursor-pointer items-start gap-3 rounded-xl border bg-white p-4 shadow-sm ${errors[key] ? "border-rose-400" : "border-slate-200"}`}><input type="checkbox" checked={data[key]} onChange={(event) => update({ [key]: event.target.checked })} className="mt-1 h-5 w-5 rounded border-slate-300 text-blue-600" /><span><strong className="block text-sm text-slate-950">{label}</strong><span className="mt-1 block text-xs font-medium text-slate-600">{copy}</span>{errors[key] && <span className="mt-1 block text-xs font-semibold text-rose-700">{errors[key]}</span>}</span></label>)}<div className="flex gap-2 rounded-xl bg-blue-50 p-4 text-sm font-semibold text-blue-900"><CheckCircle2 className="h-5 w-5 shrink-0" />All three confirmations are required to continue to review.</div></div></div></div>;
}
