import { CheckCircle2, Clock3, Pencil, ShieldCheck } from "lucide-react";
import type { CreatorOnboardingDraft, OnboardingStepKey } from "@/app/lib/creators/creatorOnboardingData";
import { onboardingReviewTimeline } from "@/app/lib/creators/creatorOnboardingData";
import { StepIntro } from "./CreatorOnboardingFields";

export function CreatorReviewStep({ data, onEdit }: { data: CreatorOnboardingDraft; onEdit: (step: OnboardingStepKey) => void }) {
  const sections = [
    { title: "Creator profile", step: "profile" as const, rows: [["Display name", data.displayName || "Not provided"], ["Username", data.username || "Not provided"], ["Location", data.location || "Not provided"], ["Primary category", data.primaryCategory || "Not provided"]] },
    { title: "Identity", step: "identity" as const, rows: [["Government ID", data.governmentId || "Not selected"], ["Email", data.email || "Not provided"], ["Phone", data.phone || "Not provided"], ["Status", data.identityStatus]] },
    { title: "Tax & payout", step: "tax" as const, rows: [["Country", data.taxCountry], ["Tax type", data.taxType], ["Payout", data.payoutMethod], ["Bank / UPI", data.bankName || data.upiId || "Preview not provided"]] },
    { title: "Portfolio", step: "portfolio" as const, rows: [["Experience", data.experience || "Not provided"], ["Specializations", data.specializations || "Not provided"], ["Equipment", data.equipment || "Not provided"], ["Destinations", data.destinations || "Not provided"]] },
  ];
  return <div><StepIntro eyebrow="Step 9 · Final review" title="Review your application" copy="Check the information below before submitting this local preview application." /><div className="mt-8 grid gap-4 md:grid-cols-2">{sections.map((section) => <article key={section.title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-bold">{section.title}</h2><button type="button" onClick={() => onEdit(section.step)} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg px-3 text-sm font-bold text-blue-700 hover:bg-blue-50"><Pencil className="h-3.5 w-3.5" />Edit</button></div><dl className="mt-4 divide-y divide-slate-100">{section.rows.map(([label, value]) => <div key={label} className="grid grid-cols-[120px_1fr] gap-3 py-2.5 text-sm"><dt className="font-medium text-slate-600">{label}</dt><dd className="break-words font-semibold text-slate-900">{value}</dd></div>)}</dl></article>)}</div><div className="mt-5 flex items-start gap-3 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-900"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0" />Submitting creates a success preview only. No application, identity record, tax profile or payout account is transmitted.</div></div>;
}

export function CreatorSubmittedStep({ onTrack, onMarketplace }: { onTrack: () => void; onMarketplace: () => void }) {
  return <div className="mx-auto max-w-4xl text-center"><span className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-emerald-100 text-emerald-700 ring-8 ring-emerald-50"><CheckCircle2 className="h-10 w-10" /></span><p className="mt-7 text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Application received</p><h1 className="mt-2">You’re on your way to becoming a TPL Creator</h1><p className="mx-auto mt-4 max-w-2xl font-medium text-slate-600">Your preview application has reached the submitted state. No information was sent to a backend or review team.</p><div className="mt-8 grid gap-3 text-left sm:grid-cols-2 lg:grid-cols-4">{onboardingReviewTimeline.map((item, index) => <div key={item} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><span className="grid h-8 w-8 place-items-center rounded-full bg-blue-50 text-sm font-bold text-blue-700">{index + 1}</span><p className="mt-3 text-sm font-semibold text-slate-800">{item}</p></div>)}</div><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button type="button" onClick={onTrack} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-blue-600 px-6 py-3 font-bold text-white"><Clock3 className="h-4 w-4" />Track Status</button><button type="button" onClick={onMarketplace} className="min-h-11 rounded-lg border border-slate-300 bg-white px-6 py-3 font-bold text-slate-900">Back to Marketplace</button></div></div>;
}
