import { Filter, RotateCcw, X } from "lucide-react";
import { analyticsFilterOptions } from "@/app/lib/creators/creatorAnalyticsData";

const fields = [["type", "Asset Type"], ["collection", "Collection"], ["license", "License Type"], ["status", "Publishing Status"], ["destination", "Destination"]] as const;

export default function CreatorAnalyticsFilters({ params, open, onOpen, onClose, onUpdate, onReset }: { params: URLSearchParams; open: boolean; onOpen: () => void; onClose: () => void; onUpdate: (patch: Record<string, string | null>) => void; onReset: () => void }) {
  const controls = <>{fields.map(([key, label]) => <label key={key} className="block text-xs font-semibold text-slate-600">{label}<select value={params.get(key) ?? ""} onChange={(event) => onUpdate({ [key]: event.target.value || null })} className="mt-1 h-10 w-full rounded-lg border border-slate-300 bg-white px-2 text-sm font-semibold text-slate-800"><option value="">All</option>{analyticsFilterOptions[key].map((item) => <option key={item}>{item}</option>)}</select></label>)}</>;
  return <><section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between gap-3 lg:hidden"><div className="flex items-center gap-2"><Filter className="h-4 w-4 text-blue-700" /><h2 className="text-lg">Analytics Filters</h2></div><button type="button" onClick={onOpen} className="min-h-10 rounded-lg border border-slate-300 px-4 font-bold">Open Filters</button></div><div className="hidden grid-cols-5 gap-3 lg:grid">{controls}</div><div className="mt-3 hidden justify-end lg:flex"><button type="button" onClick={onReset} className="inline-flex min-h-9 items-center gap-2 text-xs font-bold text-blue-700"><RotateCcw className="h-3.5 w-3.5" />Reset Filters</button></div></section>{open && <div className="fixed inset-0 z-50 lg:hidden"><button type="button" onClick={onClose} aria-label="Close analytics filters backdrop" className="absolute inset-0 bg-slate-950/60" /><aside className="absolute inset-y-0 right-0 w-[min(90vw,360px)] overflow-y-auto bg-white p-5 shadow-2xl"><div className="flex items-center justify-between gap-3"><h2>Analytics Filters</h2><button type="button" onClick={onClose} className="grid h-10 w-10 place-items-center rounded-lg border border-slate-200" aria-label="Close analytics filters"><X className="h-5 w-5" /></button></div><div className="mt-6 space-y-5">{controls}</div><button type="button" onClick={onReset} className="mt-6 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-lg border border-slate-300 font-bold"><RotateCcw className="h-4 w-4" />Reset Filters</button></aside></div>}</>;
}
