import Link from "next/link";
import { ArrowRight, CheckCircle2, HelpCircle, Sparkles, X } from "lucide-react";
import { analyticsInsights, analyticsQuickSummary } from "@/app/lib/creators/creatorAnalyticsData";

const tones: Record<string, string> = { emerald: "border-emerald-200 bg-emerald-50 text-emerald-900", blue: "border-blue-200 bg-blue-50 text-blue-900", violet: "border-violet-200 bg-violet-50 text-violet-900", amber: "border-amber-200 bg-amber-50 text-amber-900" };
export function CreatorAnalyticsInsightGrid() { return <section><div><p className="text-xs font-bold uppercase tracking-wide text-blue-700">Fixture-derived guidance</p><h2 className="mt-1">Quick Insights</h2></div><div className="mt-4 grid gap-4 sm:grid-cols-2">{analyticsInsights.map((item) => <article key={item.title} className={`rounded-2xl border p-5 ${tones[item.tone]}`}><Sparkles className="h-5 w-5" /><h3 className="mt-3 font-bold">{item.title}</h3><p className="mt-2 text-sm font-medium">{item.copy}</p></article>)}</div></section>; }

export default function CreatorAnalyticsSidebar({ params, open, onClose }: { params: URLSearchParams; open: boolean; onClose: () => void }) {
  const applied = [...params.entries()].filter(([key, value]) => value && !["granularity", "series"].includes(key));
  const content = <div className="space-y-4"><div className="flex items-center justify-between lg:hidden"><h2>Analytics Summary</h2><button type="button" onClick={onClose} className="grid h-10 w-10 place-items-center rounded-lg border border-slate-200" aria-label="Close analytics summary"><X className="h-5 w-5" /></button></div><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg">Applied Filters</h2>{applied.length ? <div className="mt-3 flex flex-wrap gap-2">{applied.map(([key, value]) => <span key={key} className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-800">{key}: {value}</span>)}</div> : <p className="mt-3 text-sm font-medium text-slate-600">Showing all analytics preview data.</p>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg">Performance Summary</h2><ul className="mt-3 space-y-3">{analyticsQuickSummary.map((item) => <li key={item} className="flex gap-2 text-sm font-medium text-slate-600"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />{item}</li>)}</ul></section><section className="rounded-2xl bg-[#071831] p-5 text-white shadow-xl"><Sparkles className="h-6 w-6 text-blue-300" /><h2 className="mt-3 text-white">Upgrade to Pro Analytics</h2><p className="mt-2 text-sm font-medium text-slate-200">Preview advanced segmentation, exports and team reporting.</p><Link href="/creators/plans" className="mt-4 inline-flex min-h-10 items-center gap-2 rounded-lg bg-blue-600 px-4 text-sm font-bold text-white">View Plans <ArrowRight className="h-4 w-4" /></Link></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><HelpCircle className="h-5 w-5 text-blue-700" /><h2 className="text-lg">Need Help?</h2></div><p className="mt-2 text-sm font-medium text-slate-600">Learn how to interpret preview performance and improve discovery.</p><Link href="/creator-studio/settings" className="mt-3 inline-flex items-center gap-1 text-sm font-bold text-blue-700">Analytics Guide <ArrowRight className="h-4 w-4" /></Link></section></div>;
  return <><aside className="hidden lg:block">{content}</aside>{open && <div className="fixed inset-0 z-50 lg:hidden"><button type="button" onClick={onClose} aria-label="Close analytics summary backdrop" className="absolute inset-0 bg-slate-950/60" /><aside className="absolute inset-y-0 right-0 w-[min(90vw,360px)] overflow-y-auto bg-[#f4f7fb] p-4 shadow-2xl">{content}</aside></div>}</>;
}
