import { performanceSeries } from "@/app/lib/creators/creatorAnalyticsData";

export function CreatorPerformanceChart({ series, onSeries }: { series: string; onSeries: (series: string) => void }) {
  const active = performanceSeries.find((item) => item.key === series) ?? performanceSeries[0]; const max = Math.max(...active.values); const points = active.values.map((value, index) => `${40 + index * 52},${245 - (value / max) * 190}`).join(" ");
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-blue-700">Configuration preview</p><h2 className="mt-1">Performance Over Time</h2></div><div className="flex rounded-lg border border-slate-200 p-1">{performanceSeries.map((item) => <button type="button" key={item.key} onClick={() => onSeries(item.key)} className={`rounded-md px-3 py-1.5 text-xs font-bold ${active.key === item.key ? "bg-[#071831] text-white" : "text-slate-600"}`}>{item.label}</button>)}</div></div><div className="mt-5 overflow-x-auto"><svg role="img" aria-label={`${active.label} performance preview chart`} viewBox="0 0 660 280" className="min-w-[620px]"><defs><linearGradient id="analytics-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={active.color} stopOpacity="0.28" /><stop offset="100%" stopColor={active.color} stopOpacity="0" /></linearGradient></defs>{[55, 105, 155, 205, 255].map((y) => <line key={y} x1="40" y1={y} x2="630" y2={y} stroke="#e2e8f0" />)}<polygon points={`40,250 ${points} 612,250`} fill="url(#analytics-fill)" /><polyline points={points} fill="none" stroke={active.color} strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" />{active.values.map((value, index) => <circle key={index} cx={40 + index * 52} cy={245 - (value / max) * 190} r="4" fill="white" stroke={active.color} strokeWidth="3" />)}</svg></div><p className="mt-2 text-xs font-semibold text-slate-600">Static preview data · no tracking SDK or live aggregation.</p></section>;
}

export function CreatorBarChart({ title, subtitle, data, color = "bg-blue-600" }: { title: string; subtitle: string; data: { label: string; value: number }[]; color?: string }) { const max = Math.max(...data.map((item) => item.value)); return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg">{title}</h2><p className="mt-1 text-xs font-medium text-slate-600">{subtitle}</p><div className="mt-5 space-y-4">{data.map((item) => <div key={item.label}><div className="flex justify-between gap-3 text-xs font-semibold"><span>{item.label}</span><span>{item.value}%</span></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{ width: `${(item.value / max) * 100}%` }} /></div></div>)}</div></section>; }

export function CreatorListChart({ title, subtitle, data }: { title: string; subtitle: string; data: { label: string; value: string }[] }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg">{title}</h2><p className="mt-1 text-xs font-medium text-slate-600">{subtitle}</p><div className="mt-4 divide-y divide-slate-100">{data.map((item, index) => <div key={item.label} className="flex items-center justify-between gap-3 py-3"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-slate-100 text-xs font-bold text-slate-600">{index + 1}</span><span className="text-sm font-semibold">{item.label}</span></div><strong className="text-sm text-blue-700">{item.value}</strong></div>)}</div></section>; }
