export type PartnerAmenity={code:string;profileCode:string;profileVersion:number;scope:'PROPERTY'|'ROOM';category:string;label:string;translationKey:string;displayOrder:number;valueKind:'BOOLEAN'|'ENUM';allowedValues:string[]};
export type PartnerHotelContent={id:string;serviceScopeId:string;supplyItemId:string|null;scope:'PROPERTY'|'ROOM';profileCode:string;profileVersion:number;shortDescription:string;detailedDescription:string|null;structuredValues:Record<string,string>;amenities:Array<{code:string;value:string|null}>;reviewStatus:'pending_review'|'approved'|'rejected';reviewReason:string|null;version:number;clientSurface:'website'|'mobile'|'api';updatedAt:string};
export type PartnerPolicyOption={code:string;entityType:'POLICY_TEMPLATE'|'INCLUSION'|'EXCLUSION';label:string;category:string;displayOrder:number;scopes:string[];valueType:string;allowedValues:string[];entityVersion:number};
export type PartnerHotelPolicyConfiguration={checkInStart:string;checkInEnd:string|null;earlyCheckIn:'not_available'|'on_request';checkOutTime:string;lateCheckOut:'not_available'|'on_request';governmentIdRequired:boolean;acceptedIdCategories:string[];minimumLeadGuestAge:number|null;localIdAcceptance:'accepted'|'on_request'|'not_configured';foreignGuestRequirement:'passport_and_valid_visa'|'passport'|'not_configured';children:'allowed'|'not_allowed';existingBed:'allowed'|'not_allowed'|'on_request';extraBed:'not_available'|'on_request';extraGuests:'not_allowed'|'on_request';maximumGuestsPerRoom:number;pets:'allowed'|'not_allowed'|'on_request';smoking:'non_smoking_property'|'designated_areas';parties:'allowed'|'not_allowed'|'prior_approval';visitors:'allowed'|'restricted'|'not_allowed';visitorStart:string|null;visitorEnd:string|null;quietHoursEnabled:boolean;quietHoursStart:string|null;quietHoursEnd:string|null;damageDeposit:'not_required'|'required_disclosure'|'on_request';accessibilityAssistance:'available_on_request'|'not_configured';otherRules:string|null};
export type PartnerHotelPolicy={id:string;serviceScopeId:string;profileCode:string;profileVersion:number;catalogueVersion:number;configuration:PartnerHotelPolicyConfiguration;inclusions:Array<{code:string;value:Record<string,unknown>}>;exclusions:Array<{code:string;value:Record<string,unknown>}>;reviewStatus:'pending_review'|'approved'|'rejected';reviewReason:string|null;version:number;clientSurface:'website'|'mobile'|'api';updatedAt:string};
export type PartnerSupply={
 contractVersion:1;organizationId:string;syntheticFixture?:boolean;scope:'organization';canWrite:boolean;canWriteSupply:boolean;canReadMedia:boolean;canWriteMedia:boolean;canReviewMedia?:boolean;canWriteContent:boolean;canReviewContent?:boolean;canWritePolicies:boolean;canReviewPolicies?:boolean;
 moderationAutomation?:{contractVersion:1;runtime:{mode:'MANUAL'|'ASSISTED'|'AUTO';provider:'NONE'|'EXTERNAL';autoApprovalEnabled:boolean;autoRejectionEnabled:boolean;providerStatus:'NOT_RUN_NO_PROVIDER'|'CONFIGURED'};policies:Array<{serviceScopeId:string;serviceLabel:string;profileCode:string;profileVersion:number;capabilityFamilyCode:string;status:'active'|'inactive'|'retired';mode:'MANUAL'|'ASSISTED'|'AUTO';provider:'NONE'|'EXTERNAL';humanReviewRequired:boolean}>;assessments:Array<{mediaId:string;mediaVersion:number;policyProfileCode:string;policyProfileVersion:number;mode:'MANUAL'|'ASSISTED'|'AUTO';provider:'NONE'|'EXTERNAL';status:string;riskScore:number|null;confidence:number|null;checkResults:unknown[];reasonCodes:string[];recommendation:string;finalDecision:string|null;decisionSource:'HUMAN'|'AUTOMATION'|null;completedAt:string|null}>;finalAuthority:'HUMAN_ADMIN_REVIEWER'};
 ratePolicy:{currency:string;minorUnitScale:2;maxAmountMinor:number;states:readonly ['draft','active','inactive'];multiplePlans:boolean;overlapPolicy:'not_configured'};quota:{activeMedia:number;maxActiveMedia:number;maxFileBytes:number};
 serviceScopes:Array<{id:string;serviceCode:string;label:string;status:string;supplyApplicable:boolean;mediaApplicable:boolean;ready:boolean}>;
 items:Array<{id:string;serviceScopeId:string;stableKey:string;label:string;inventoryType:string;capacityUnit:string;capacityTotal:number;status:string;version:number;updatedAt:string}>;
 availability:Array<{id:string;supplyItemId:string;startDate:string;endDate:string;availableCapacity:number;status:string;version:number;updatedAt:string}>;
 rates:Array<{id:string;supplyItemId:string;name:string;currency:string;baseAmountMinor:number;validFrom:string;validTo:string;status:string;version:number;updatedAt:string}>;
 media:Array<{id:string;serviceScopeId:string;supplyItemId:string|null;label:string;altText:string;mimeType:string;sizeBytes:number;status:string;sortOrder:number;version:number;updatedAt:string;mediaKind:'image'|'youtube';category:string;safeFilename:string|null;externalVideoId:string|null;width:number|null;height:number|null;isCover:boolean;moderationStatus:'pending_review'|'approved'|'rejected';clientSurface:'website'|'mobile'|'api';reviewedAt?:string|null;reviewNote?:string|null}>;
 contentCatalogueVersion:number;profiles:Array<{profileCode:string;profileVersion:number;capabilityFamilyCode:string;serviceCode:string}>;amenityCatalogue:PartnerAmenity[];contentRecords:PartnerHotelContent[];
 policyCatalogueVersion:number;policyProfiles:Array<{profileCode:string;profileVersion:number;capabilityFamilyCode:string;serviceCode:string}>;policyCatalogue:PartnerPolicyOption[];policyRecords:PartnerHotelPolicy[];
 history:Array<{entityType:string;entityId:string;action:string;version:number;summary:Record<string,unknown>;at:string}>;freshness:{asOf:string;catalogueVersion:number|null}
};
export function validSupply(v:unknown):v is PartnerSupply{const x=v as PartnerSupply|null;return !!x&&x.contractVersion===1&&typeof x.organizationId==='string'&&Number.isInteger(x.contentCatalogueVersion)&&Number.isInteger(x.policyCatalogueVersion)&&typeof x.ratePolicy?.currency==='string'&&x.ratePolicy.minorUnitScale===2&&Number.isInteger(x.ratePolicy.maxAmountMinor)&&Array.isArray(x.serviceScopes)&&Array.isArray(x.items)&&Array.isArray(x.availability)&&Array.isArray(x.rates)&&Array.isArray(x.media)&&Array.isArray(x.profiles)&&Array.isArray(x.amenityCatalogue)&&Array.isArray(x.contentRecords)&&Array.isArray(x.policyProfiles)&&Array.isArray(x.policyCatalogue)&&Array.isArray(x.policyRecords)&&Array.isArray(x.history);}
