export type HotelBookingRequestState='DRAFT'|'SUBMITTED'|'UNDER_REVIEW'|'APPROVED'|'REJECTED'|'WITHDRAWN'|'EXPIRED';
export type HotelBookingRequest={id:string;requestRef:string;bookingId:string;bookingRef:string;hotel:string;room:string;requestType:'MODIFICATION'|'CANCELLATION';requestKind:string;state:HotelBookingRequestState;reasonCode:string;requesterNote:string|null;requestedChanges:Record<string,unknown>;before:Record<string,unknown>;policy:Record<string,unknown>;eligibility:{allowed:boolean;reasonCode:string;explanation:string;requiredApprovals:string[];inventoryRevalidationRequired:boolean;financialReviewRequired:boolean};financialImpactState:string;inventoryRevalidationRequired:boolean;financialReviewRequired:boolean;partnerRecommendation:string|null;partnerNote:string|null;decisionReason:string|null;applied:Record<string,unknown>|null;stayStatus:string;paymentDisclosure:string;version:number;correlationId:string;routingStatus:string;customerStatus:string;routing:{attempts:number;routedAt:string|null;responseDueAt:string|null;respondedAt:string|null;reminderAt:string|null;escalatedAt:string|null;completedAt:string|null};automation:{mode:'MANUAL'|'ASSISTED'|'AUTO';provider:'NONE';autoDecisionEnabled:boolean;externalDeliveryEnabled:false};canWithdraw:boolean;canAcknowledge:boolean;canDecide:boolean;createdAt:string;updatedAt:string;timeline:Array<{id:string;eventType:string;fromState:string|null;toState:string;version:number;actorType:string;clientSurface:string;at:string;summary:Record<string,unknown>}>};
export type HotelBookingSubmissionEligibility={allowed:boolean;code?:string;reasonCode:string;explanation:string;requiredApprovals?:string[];inventoryRevalidationRequired?:boolean;financialReviewRequired?:boolean};
export type HotelBookingEligibility={bookingId:string;modificationEligibility:HotelBookingSubmissionEligibility;cancellationEligibility:HotelBookingSubmissionEligibility};
export type HotelBookingRequestSnapshot={contractVersion:2;audience:'partner'|'admin'|'customer';organizationId:string;canSubmit:boolean;canReview:boolean;bookingEligibility:HotelBookingEligibility[];automation:{mode:'MANUAL'|'ASSISTED'|'AUTO';provider:'NONE';autoDecisionEnabled:boolean;externalDeliveryEnabled:false};paymentBoundary:string;requests:HotelBookingRequest[];booking?:{id:string;bookingRef:string;stayStatus:string;paymentDisclosure:string;modificationEligibility:HotelBookingSubmissionEligibility;cancellationEligibility:HotelBookingSubmissionEligibility};freshness:{asOf:string;timezone:'UTC'}};
export type HotelBookingModificationSummary={bookingId:string;bookingRef:string;requestRef:string;status:'UPDATED';appliedAt:string;applied:Record<string,unknown>};
export type HotelBookingModificationSummarySnapshot={contractVersion:1;items:HotelBookingModificationSummary[];freshness:{asOf:string;timezone:'UTC'}};
export function validHotelBookingRequestSnapshot(value:unknown):value is HotelBookingRequestSnapshot{const v=value as HotelBookingRequestSnapshot|null;return !!v&&v.contractVersion===2&&typeof v.organizationId==='string'&&Array.isArray(v.bookingEligibility)&&v.bookingEligibility.every(e=>typeof e.bookingId==='string'&&typeof e.modificationEligibility?.allowed==='boolean'&&typeof e.modificationEligibility?.reasonCode==='string'&&typeof e.cancellationEligibility?.allowed==='boolean'&&typeof e.cancellationEligibility?.reasonCode==='string')&&Array.isArray(v.requests)&&v.requests.every(r=>typeof r.id==='string'&&typeof r.requestRef==='string'&&typeof r.customerStatus==='string'&&typeof r.routingStatus==='string'&&Number.isSafeInteger(r.version)&&Array.isArray(r.timeline));}
export function validHotelBookingModificationSummarySnapshot(value:unknown):value is HotelBookingModificationSummarySnapshot{const v=value as HotelBookingModificationSummarySnapshot|null;return !!v&&v.contractVersion===1&&Array.isArray(v.items)&&v.items.every(item=>typeof item.bookingId==='string'&&typeof item.bookingRef==='string'&&typeof item.requestRef==='string'&&item.status==='UPDATED'&&typeof item.appliedAt==='string'&&!!item.applied&&typeof item.applied==='object');}
export function requestChangeSummary(values:Record<string,unknown>){const labels:Record<string,string>={stayStart:'Check-in',stayEnd:'Check-out',adults:'Adults',children:'Children',guestDisplayName:'Guest name',specialRequest:'Special request',fullCancellation:'Cancellation'};return Object.entries(values).filter(([,v])=>v!==undefined&&v!==null&&v!=='').map(([k,v])=>`${labels[k]??k}: ${typeof v==='boolean'?(v?'Yes':'No'):String(v)}`);}
