import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {describe,expect,it} from 'vitest';
import {requestChangeSummary,validHotelBookingRequestSnapshot} from './partnerHotelBookingRequests';
const automation={mode:'MANUAL',provider:'NONE',autoDecisionEnabled:false,externalDeliveryEnabled:false};
const routing={attempts:1,routedAt:'2026-09-25T00:00:01Z',responseDueAt:'2026-09-25T00:30:01Z',respondedAt:null,reminderAt:null,escalatedAt:null,completedAt:null};
describe('HOTEL-M3B request contract',()=>{
 it('accepts only the bounded versioned routing shape',()=>{const value={contractVersion:2,audience:'partner',organizationId:'o',canSubmit:false,canReview:true,bookingEligibility:[{bookingId:'b',modificationEligibility:{allowed:false,reasonCode:'CUSTOMER_REQUEST_ONLY',explanation:'Only the customer submits.'},cancellationEligibility:{allowed:false,reasonCode:'CUSTOMER_REQUEST_ONLY',explanation:'Only the customer submits.'}}],automation,paymentBoundary:'No finance.',requests:[{id:'r',requestRef:'TPL-M3B',version:1,customerStatus:'Waiting for Hotel confirmation',routingStatus:'ROUTED',correlationId:'c',routing,automation,timeline:[]}],freshness:{asOf:'2026-09-25T00:00:00Z',timezone:'UTC'}};expect(validHotelBookingRequestSnapshot(value)).toBe(true);expect(validHotelBookingRequestSnapshot({...value,contractVersion:1})).toBe(false);});
 it('creates readable before/after labels',()=>expect(requestChangeSummary({stayStart:'2026-10-02',adults:3})).toEqual(['Check-in: 2026-10-02','Adults: 3']));
 it('keeps Admin decisions as an explicit inline two-step action',()=>{const source=readFileSync(resolve(process.cwd(),'app/components/partner/PartnerHotelBookingWorkspace.tsx'),'utf8');expect(source).toContain('Confirm approve & apply');expect(source).toContain("disabled={busy||decisionReason.trim().length<3}");expect(source).toContain('type="button"');});
 it('keeps customer submission and Hotel recommendation boundaries',()=>{const source=readFileSync(resolve(process.cwd(),'app/components/partner/PartnerHotelBookingWorkspace.tsx'),'utf8');expect(source).toContain('Only the booking customer can request a modification or cancellation from My Booking.');expect(source).toContain('Yes · Hotel can support request');expect(source).toContain('No · Hotel cannot support request');expect(source).toContain('TPL remains the final decision authority');expect(source).not.toContain('Submit modification request');expect(source).not.toContain('Submit cancellation request');expect(source).not.toContain('Withdraw my request');});
 it('shows every open request in the Admin intake queue before Hotel response',()=>{
  const source=readFileSync(resolve(process.cwd(),'app/components/partner/PartnerHotelBookingWorkspace.tsx'),'utf8');
  expect(source).toContain('TPL INTAKE · IMMEDIATE ADMIN VISIBILITY');
  expect(source).toContain("requests?.requests.filter(r=>['DRAFT','SUBMITTED','UNDER_REVIEW'].includes(r.state))");
  expect(source).toContain('Customer requests appear here before the Hotel responds.');
  expect(source).toContain('onClick={()=>setSelected(item.bookingId)}');
  expect(source).toContain("if(item.state==='SUBMITTED')return'Customer request received'");
  expect(source).toContain("return item.routingStatus==='ESCALATED'?'TPL System sent · Hotel response overdue · Admin monitoring':'TPL System sent · Hotel response pending'");
  expect(source).toContain('TPL received and automatically sent this customer request to the Hotel.');
  expect(source).toContain('Customer → TPL');
  expect(source).toContain('TPL System → Hotel');
  expect(source).toContain('Hotel → TPL');
  expect(source).toContain('TPL → Customer');
  expect(source).toContain('Final Admin decision remains locked until Hotel response.');
  expect(source).toContain("'Original booking receipt acknowledged'");
  expect(source).not.toContain('Visible to TPL · ${item.customerStatus}');
 });
 it('keeps one canonical account booking across modification and cancellation projections',()=>{
  const bookings=readFileSync(resolve(process.cwd(),'app/components/account/bookings/BookingsDetails.tsx'),'utf8');
  const detail=readFileSync(resolve(process.cwd(),'app/account/bookings/hotel/[bookingId]/page.tsx'),'utf8');
  const cancelled=readFileSync(resolve(process.cwd(),'app/components/account/bookings/sections/CancelledJourneySection.tsx'),'utf8');
  const refunds=readFileSync(resolve(process.cwd(),'app/components/account/bookings/sections/RefundStatusSection.tsx'),'utf8');
  expect(bookings).toContain('window.setInterval(refreshBookings, 5000)');
  expect(bookings).toContain('window.addEventListener("focus", refreshBookings)');
  expect(detail).toContain('mode="status"');
  expect(cancelled).toContain('Financial review required');
  expect(cancelled).toContain('financialReviewRequired');
  expect(refunds).toContain('REFUND_REVIEW_REQUIRED');
 });
 it('routes card-level Manage and Cancel actions to distinct Hotel request flows',()=>{
  const panel=readFileSync(resolve(process.cwd(),'app/components/account/HotelBookingRequestPanel.tsx'),'utf8');
  const detail=readFileSync(resolve(process.cwd(),'app/account/bookings/hotel/[bookingId]/page.tsx'),'utf8');
  const manage=readFileSync(resolve(process.cwd(),'app/hotels/manage/page.tsx'),'utf8');
  const bookingConfig=readFileSync(resolve(process.cwd(),'app/lib/booking/bookingServiceConfig.ts'),'utf8');
  const upcoming=readFileSync(resolve(process.cwd(),'app/components/account/bookings/sections/UpcomingJourneySection.tsx'),'utf8');
  expect(detail).toContain('mode="status"');
  expect(panel).not.toContain('Open Manage Booking');
  expect(bookingConfig).toContain('&action=modification');
  expect(upcoming).toContain('/hotels/cancel?bookingId=');
  expect(upcoming).toContain('handleCancelBooking(booking)');
  expect(manage).toContain('requestType={requestedType}');
  expect(manage).toContain('getBackendFirstBookingPayload<Payload>');
  expect(manage).toContain('booking?.dateRange?.end');
  expect(manage).toContain('flow={requestedType === "CANCELLATION" ? "cancel" : "manage"}');
  const cancel=readFileSync(resolve(process.cwd(),'app/hotels/cancel/page.tsx'),'utf8');
  expect(cancel).toContain('import HotelManagePage');
  expect(panel).not.toContain('<Field label="Request type">');
  expect(panel).toContain('setInterval(()=>void load(true),5_000)');
  expect(panel).toContain('Submit ${flowName.toLowerCase()} request');
  expect(panel).toContain('openRequest?.requestType===form.type');
  expect(panel).toContain('View the open request from ${openRequestName==="modification"?"Manage Booking":"Cancel Booking"}');
  expect(panel).toContain('!initialLoading&&!openRequest&&!visibleRequests?.length');
  expect(panel).not.toContain("busy?'Working…'");
 });
});

describe('HOTEL-M3B approved modification presentation',()=>{
 it('shows one bounded updated marker and binds detail cards to canonical stay values',()=>{const list=readFileSync(resolve(process.cwd(),'app/components/account/bookings/sections/UpcomingJourneySection.tsx'),'utf8'),details=readFileSync(resolve(process.cwd(),'app/account/bookings/hotel/[bookingId]/page.tsx'),'utf8'),bookings=readFileSync(resolve(process.cwd(),'app/components/account/bookings/BookingsDetails.tsx'),'utf8');expect(list).toContain('Updated booking');expect(bookings).toContain('/api/v1/bookings/hotel-modification-summaries');expect(details).toContain('The current stay details below are authoritative.');expect(details).toContain('hotelName={displayedHotelName}');expect(details).toContain('roomName={displayedRoomName}');expect(details).toContain('stayLifecycle?.guests.adults');});
});
