"use client";
import Image from 'next/image';
import {useCallback,useEffect,useState} from 'react';
import {getTplApiBaseUrl} from '@/app/lib/api/tplApiClient';

type Media={id:string;scope:'property'|'room';inventoryItemId:string|null;inventoryItemLabel:string|null;label:string;altText:string;mediaKind:'image'|'youtube';category:string;isCover:boolean;sortOrder:number;version:number;videoId:string|null;contentPath:string|null};
type Gallery={contractVersion:1;context:{businessLabel:string;serviceLabel:string;syntheticStagingOnly:true};propertyMedia:Media[];rooms:Array<{inventoryItemId:string;inventoryItemLabel:string;media:Media[]}>;projection:'approved_active_only';freshness:{asOf:string}};
type ApprovedContent={id:string;inventoryItemId:string|null;inventoryItemLabel:string|null;shortDescription:string;detailedDescription:string|null;amenities:Array<{code:string;label:string;category:string;value:string|null}>;version:number};
type PolicyRecord={configuration:{checkInStart:string;checkInEnd:string|null;earlyCheckIn:string;checkOutTime:string;lateCheckOut:string;governmentIdRequired:boolean;minimumLeadGuestAge:number|null;children:string;existingBed:string;extraBed:string;extraGuests:string;maximumGuestsPerRoom:number;pets:string;smoking:string;parties:string;visitors:string;visitorStart:string|null;visitorEnd:string|null;quietHoursEnabled:boolean;quietHoursStart:string|null;quietHoursEnd:string|null;damageDeposit:string;accessibilityAssistance:string;otherRules:string|null};additionalPolicies?:Array<{code:string;label:string;value:boolean|string}>;inclusions:Array<{code:string;label:string}>;exclusions:Array<{code:string;label:string}>;version:number};
type HotelDetail={contractVersion:1;context:Gallery['context'];property:ApprovedContent|null;rooms:ApprovedContent[];projection:'approved_content_only';freshness:{asOf:string};gallery:Gallery;policies:{profileCode:string;profileVersion?:number;record:PolicyRecord|null;projection:'approved_policy_only'}};

export default function GalleryPreview({organizationId,serviceScopeId}:{organizationId:string;serviceScopeId:string}){
 const [data,setData]=useState<HotelDetail|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),base=getTplApiBaseUrl();
 const load=useCallback(async()=>{setLoading(true);setError('');try{if(!organizationId||!serviceScopeId)throw Error();const response=await fetch(`${base}/api/v1/public/staging/partner-hotels/${encodeURIComponent(organizationId)}/services/${encodeURIComponent(serviceScopeId)}/detail`,{cache:'no-store'}),json=await response.json();if(!response.ok||!json.ok)throw Error();setData(json.data as HotelDetail);}catch{setError('This staging Hotel detail preview is unavailable.');}finally{setLoading(false);}},[base,organizationId,serviceScopeId]);
 useEffect(()=>{void load();},[load]);
 if(loading)return <main className="min-h-screen bg-slate-50 p-6 text-slate-700"><p>Loading approved Hotel media…</p></main>;
 if(error||!data)return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-5xl rounded-2xl border border-amber-200 bg-white p-6"><h1 className="text-xl font-semibold text-slate-950">Hotel gallery preview</h1><p className="mt-2 text-amber-800">{error}</p><button className="mt-4 rounded-lg bg-slate-900 px-4 py-2 text-white" onClick={()=>void load()}>Try again</button></div></main>;
 const total=data.gallery.propertyMedia.length+data.gallery.rooms.reduce((sum,room)=>sum+room.media.length,0);
 return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900"><div className="mx-auto max-w-6xl space-y-6"><header className="rounded-2xl bg-[#142d43] p-6 text-white"><span className="rounded-full bg-orange-500 px-3 py-1 text-xs font-semibold">SYNTHETIC STAGING PREVIEW</span><h1 className="mt-4 text-2xl font-semibold">{data.context.businessLabel}</h1><p className="mt-1 text-sm text-slate-200">{data.context.serviceLabel} · approved media only · approved content only · approved policies only</p></header>{data.property?<ContentSection title="About this property" content={data.property}/>:<section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Property details awaiting approval</h2><p className="mt-2 text-sm text-slate-600">Pending or returned descriptions and amenities stay private.</p></section>}{!total?<section className="rounded-2xl border border-slate-200 bg-white p-8"><h2 className="text-lg font-semibold">No approved gallery media yet</h2><p className="mt-2 text-sm text-slate-600">Pending or returned media stays private and does not appear here.</p></section>:null}<GallerySection title="Property gallery" media={data.gallery.propertyMedia} base={base}/>{data.rooms.map(room=><ContentSection key={room.id} title={'Room details · '+(room.inventoryItemLabel??'Room')} content={room}/>)}{data.gallery.rooms.map(room=><GallerySection key={room.inventoryItemId} title={`Room gallery · ${room.inventoryItemLabel}`} media={room.media} base={base}/>)}{data.policies.record?<PolicySection record={data.policies.record}/>:<section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Hotel policies awaiting approval</h2><p className="mt-2 text-sm text-slate-600">Pending or returned Hotel rules, inclusions and exclusions stay private.</p></section>}<footer className="text-xs text-slate-500">Approved active projection · refreshed {new Date(data.freshness.asOf).toLocaleString('en-GB',{timeZone:'UTC'})} UTC</footer></div></main>;
}

function PolicySection({record}:{record:PolicyRecord}){const c=record.configuration,h=(value:string)=>value.replaceAll('_',' ');return <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Hotel policies</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><strong>Arrival &amp; departure</strong><p className="mt-2 text-sm text-slate-700">Check-in {c.checkInStart}{c.checkInEnd?`–${c.checkInEnd}`:''} · Check-out {c.checkOutTime}</p><p className="mt-1 text-sm text-slate-600">Early check-in: {h(c.earlyCheckIn)} · Late check-out: {h(c.lateCheckOut)}</p></div><div className="rounded-xl bg-slate-50 p-4"><strong>Guest &amp; property rules</strong><p className="mt-2 text-sm text-slate-700">Pets: {h(c.pets)} · Smoking: {h(c.smoking)} · Parties: {h(c.parties)}</p><p className="mt-1 text-sm text-slate-600">Visitors: {h(c.visitors)} · Maximum guests per room: {c.maximumGuestsPerRoom}</p></div></div>{c.quietHoursEnabled?<p className="mt-4 text-sm text-slate-700"><strong>Quiet hours:</strong> {c.quietHoursStart}–{c.quietHoursEnd}</p>:null}{c.otherRules?<p className="mt-3 text-sm text-slate-700"><strong>Other property rules:</strong> {c.otherRules}</p>:null}{record.additionalPolicies?.length?<div className="mt-4"><h3 className="font-semibold">Additional policies</h3><ul className="mt-2 space-y-2">{record.additionalPolicies.map(item=><li key={item.code} className="rounded-lg bg-slate-50 px-3 py-2 text-sm">{item.label}: {typeof item.value==='boolean'?(item.value?'Yes':'No'):h(item.value)}</li>)}</ul></div>:null}<div className="mt-5 grid gap-5 md:grid-cols-2"><div><h3 className="font-semibold text-emerald-800">What’s included</h3><ul className="mt-2 space-y-2">{record.inclusions.map(item=><li key={item.code} className="rounded-lg bg-emerald-50 px-3 py-2 text-sm">{item.label}</li>)}{!record.inclusions.length?<li className="text-sm text-slate-500">No structured inclusions approved.</li>:null}</ul></div><div><h3 className="font-semibold text-amber-800">What’s not included</h3><ul className="mt-2 space-y-2">{record.exclusions.map(item=><li key={item.code} className="rounded-lg bg-amber-50 px-3 py-2 text-sm">{item.label}</li>)}{!record.exclusions.length?<li className="text-sm text-slate-500">No structured exclusions approved.</li>:null}</ul></div></div></section>}

function ContentSection({title,content}:{title:string;content:ApprovedContent}){const groups=Array.from(new Set(content.amenities.map(value=>value.category)));return <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-3 text-slate-700">{content.shortDescription}</p>{content.detailedDescription?<p className="mt-2 text-sm text-slate-600">{content.detailedDescription}</p>:null}{groups.map(group=><div key={group} className="mt-4"><h3 className="text-sm font-semibold text-slate-700">{group.replaceAll('_',' ').toLowerCase()}</h3><ul className="mt-2 grid gap-2 sm:grid-cols-2">{content.amenities.filter(value=>value.category===group).map(value=><li key={value.code} className="rounded-lg bg-slate-50 px-3 py-2 text-sm">{value.label}{value.value?' · '+value.value:''}</li>)}</ul></div>)}</section>}

function GallerySection({title,media,base}:{title:string;media:Media[];base:string}){if(!media.length)return null;return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">{title}</h2><span className="text-sm text-slate-500">{media.length} approved</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{media.map(item=><article key={item.id} className="overflow-hidden rounded-xl border border-slate-200 bg-slate-50">{item.mediaKind==='image'&&item.contentPath?<Image src={base+item.contentPath} alt={item.altText} width={800} height={520} unoptimized className="aspect-[4/3] h-auto w-full object-cover"/>:item.videoId?<SafeYouTubeVideo videoId={item.videoId} title={item.altText}/>:null}<div className="p-4"><div className="flex items-center gap-2"><strong>{item.label}</strong>{item.isCover?<span className="rounded-full bg-orange-100 px-2 py-1 text-xs font-semibold text-orange-800">Cover</span>:null}</div><p className="mt-1 text-sm text-slate-600">{item.category} · order {item.sortOrder}</p></div></article>)}</div></section>}

function SafeYouTubeVideo({videoId,title}:{videoId:string;title:string}){const [play,setPlay]=useState(false);if(!play)return <div className="flex aspect-video items-center justify-center bg-slate-900 p-4"><button type="button" className="rounded-lg bg-white px-4 py-2 font-semibold text-slate-950" onClick={()=>setPlay(true)}>Play approved YouTube video</button></div>;return <iframe className="aspect-video w-full" src={`https://www.youtube-nocookie.com/embed/${videoId}`} title={title} loading="lazy" referrerPolicy="strict-origin-when-cross-origin" sandbox="allow-scripts allow-same-origin allow-presentation" allow="accelerometer; encrypted-media; picture-in-picture" allowFullScreen/>;}
