"use client";
import Image from 'next/image';
import {useCallback,useEffect,useState} from 'react';
import {getTplApiBaseUrl} from '@/app/lib/api/tplApiClient';

type Media={id:string;scope:'property'|'room';inventoryItemId:string|null;inventoryItemLabel:string|null;label:string;altText:string;mediaKind:'image'|'youtube';category:string;isCover:boolean;sortOrder:number;version:number;videoId:string|null;contentPath:string|null};
type Gallery={contractVersion:1;context:{businessLabel:string;serviceLabel:string;syntheticStagingOnly:true};propertyMedia:Media[];rooms:Array<{inventoryItemId:string;inventoryItemLabel:string;media:Media[]}>;projection:'approved_active_only';freshness:{asOf:string}};

export default function GalleryPreview({organizationId,serviceScopeId}:{organizationId:string;serviceScopeId:string}){
 const [data,setData]=useState<Gallery|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),base=getTplApiBaseUrl();
 const load=useCallback(async()=>{setLoading(true);setError('');try{if(!organizationId||!serviceScopeId)throw Error();const response=await fetch(`${base}/api/v1/public/staging/partner-hotels/${encodeURIComponent(organizationId)}/services/${encodeURIComponent(serviceScopeId)}/gallery`,{cache:'no-store'}),json=await response.json();if(!response.ok||!json.ok)throw Error();setData(json.data as Gallery);}catch{setError('This staging Hotel gallery preview is unavailable.');}finally{setLoading(false);}},[base,organizationId,serviceScopeId]);
 useEffect(()=>{void load();},[load]);
 if(loading)return <main className="min-h-screen bg-slate-50 p-6 text-slate-700"><p>Loading approved Hotel media…</p></main>;
 if(error||!data)return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-5xl rounded-2xl border border-amber-200 bg-white p-6"><h1 className="text-xl font-semibold text-slate-950">Hotel gallery preview</h1><p className="mt-2 text-amber-800">{error}</p><button className="mt-4 rounded-lg bg-slate-900 px-4 py-2 text-white" onClick={()=>void load()}>Try again</button></div></main>;
 const total=data.propertyMedia.length+data.rooms.reduce((sum,room)=>sum+room.media.length,0);
 return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900"><div className="mx-auto max-w-6xl space-y-6"><header className="rounded-2xl bg-[#142d43] p-6 text-white"><span className="rounded-full bg-orange-500 px-3 py-1 text-xs font-semibold">SYNTHETIC STAGING PREVIEW</span><h1 className="mt-4 text-2xl font-semibold">{data.context.businessLabel}</h1><p className="mt-1 text-sm text-slate-200">{data.context.serviceLabel} · approved media only</p></header>{!total?<section className="rounded-2xl border border-slate-200 bg-white p-8"><h2 className="text-lg font-semibold">No approved gallery media yet</h2><p className="mt-2 text-sm text-slate-600">Pending or returned media stays private and does not appear here.</p></section>:null}<GallerySection title="Property gallery" media={data.propertyMedia} base={base}/>{data.rooms.map(room=><GallerySection key={room.inventoryItemId} title={`Room gallery · ${room.inventoryItemLabel}`} media={room.media} base={base}/>)}<footer className="text-xs text-slate-500">Approved active projection · refreshed {new Date(data.freshness.asOf).toLocaleString('en-GB',{timeZone:'UTC'})} UTC</footer></div></main>;
}

function GallerySection({title,media,base}:{title:string;media:Media[];base:string}){if(!media.length)return null;return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">{title}</h2><span className="text-sm text-slate-500">{media.length} approved</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{media.map(item=><article key={item.id} className="overflow-hidden rounded-xl border border-slate-200 bg-slate-50">{item.mediaKind==='image'&&item.contentPath?<Image src={base+item.contentPath} alt={item.altText} width={800} height={520} unoptimized className="aspect-[4/3] h-auto w-full object-cover"/>:item.videoId?<SafeYouTubeVideo videoId={item.videoId} title={item.altText}/>:null}<div className="p-4"><div className="flex items-center gap-2"><strong>{item.label}</strong>{item.isCover?<span className="rounded-full bg-orange-100 px-2 py-1 text-xs font-semibold text-orange-800">Cover</span>:null}</div><p className="mt-1 text-sm text-slate-600">{item.category} · order {item.sortOrder}</p></div></article>)}</div></section>}

function SafeYouTubeVideo({videoId,title}:{videoId:string;title:string}){const [play,setPlay]=useState(false);if(!play)return <div className="flex aspect-video items-center justify-center bg-slate-900 p-4"><button type="button" className="rounded-lg bg-white px-4 py-2 font-semibold text-slate-950" onClick={()=>setPlay(true)}>Play approved YouTube video</button></div>;return <iframe className="aspect-video w-full" src={`https://www.youtube-nocookie.com/embed/${videoId}`} title={title} loading="lazy" referrerPolicy="strict-origin-when-cross-origin" sandbox="allow-scripts allow-same-origin allow-presentation" allow="accelerometer; encrypted-media; picture-in-picture" allowFullScreen/>;}
