"use client";

import Image from "next/image";
import Link from "next/link";
import { BadgeCheck, Heart, Star } from "lucide-react";
import { useState } from "react";
import type { CreatorAsset } from "@/app/lib/creators/creatorCatalogTypes";
import { marketplaceHomeAssets } from "@/app/lib/creators/creatorMarketplaceHomeData";

export default function CreatorRelatedAssets({ assets }: { assets: CreatorAsset[] }) {
  const [wished, setWished] = useState<Set<string>>(new Set());
  return <section className="border-t border-slate-200 bg-white py-10"><div className="mx-auto max-w-[1440px] px-4 sm:px-6 lg:px-10"><div className="flex items-end justify-between"><div><h2 className="text-xl font-black">You may also like</h2><p className="mt-1 text-xs font-medium text-slate-500">Related assets selected by category, type, tags and collection</p></div><Link href="/creators/search" className="text-[11px] font-black text-blue-700">View all →</Link></div><div className="mt-5 grid grid-cols-1 gap-4 min-[480px]:grid-cols-2 md:grid-cols-3 xl:grid-cols-6">{assets.map((asset) => { const home = marketplaceHomeAssets.find((item) => item.slug === asset.slug); const image = home?.previewImage ?? "/themes/banners/culture-1.jpg"; return <article key={asset.slug} className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="relative aspect-[4/3]"><Image src={image} alt={asset.title} fill sizes="(min-width:1280px) 16vw, 33vw" className="object-cover" /><span className="absolute left-2 top-2 rounded bg-[#071831]/85 px-2 py-1 text-[8px] font-black uppercase text-white">{asset.mediaType}</span><button type="button" onClick={() => setWished((current) => { const next = new Set(current); if (next.has(asset.slug)) next.delete(asset.slug); else next.add(asset.slug); return next; })} className="absolute right-2 top-2 grid h-7 w-7 place-items-center rounded-full bg-white" aria-label="Toggle wishlist"><Heart className={`h-3.5 w-3.5 ${wished.has(asset.slug) ? "fill-rose-600 text-rose-600" : ""}`} /></button><Link href={`/creators/assets/${asset.slug}`} className="absolute inset-0" aria-label={`View ${asset.title}`} /></div><div className="p-3"><Link href={`/creators/assets/${asset.slug}`} className="line-clamp-2 min-h-9 text-xs font-black">{asset.title}</Link><p className="mt-2 flex items-center gap-1 truncate text-[9px] font-bold text-slate-500">{asset.creatorName}<BadgeCheck className="h-3 w-3 text-blue-600" /></p><p className="mt-2 flex items-center gap-1 text-[9px] font-bold"><Star className="h-3 w-3 fill-amber-400 text-amber-400" />{asset.rating} ({asset.reviewCount})</p><p className="mt-3 border-t border-slate-100 pt-2 text-[10px] font-black text-blue-700">Included with Creator Plan</p></div></article>; })}</div></div></section>;
}
