"use client";

import Image from "next/image";
import Link from "next/link";
import { BadgeCheck, Check, ChevronDown, FolderPlus, MapPin, ShieldCheck, Star, Users } from "lucide-react";
import { useState } from "react";
import type { CreatorAsset, CreatorProfile } from "@/app/lib/creators/creatorCatalogTypes";

export default function CreatorAssetSidebar({ asset, creator, avatar, followed, saved, onFollow, onSave, onGatedPreview }: { asset: CreatorAsset; creator: CreatorProfile | null; avatar: string; followed: boolean; saved: boolean; onFollow: () => void; onSave: () => void; onGatedPreview: (message: string) => void }) {
  const [license, setLicense] = useState<"standard" | "extended">("standard");
  const [collection, setCollection] = useState("Travel Inspiration");
  const standardPrice = asset.licenseOptions.find((item) => item.type === "commercial")?.price ?? asset.price;
  const extendedPrice = asset.licenseOptions.find((item) => item.type === "extended")?.price ?? Math.max(asset.price * 3, 2499);

  return <aside className="min-w-0 space-y-4"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-lg shadow-slate-950/5 lg:sticky lg:top-20"><div className="rounded-lg bg-blue-50 p-3"><p className="text-xs font-black text-blue-800">Included with Creator Plan</p><p className="mt-1 text-[10px] font-medium text-blue-700">This asset is available with selected Creator Plans.</p></div><div className="mt-4 space-y-3">{[["standard", "Standard License", standardPrice, "Commercial use for one project"], ["extended", "Extended License", extendedPrice, "Expanded campaign and distribution use"]].map(([value, label, price, copy]) => <button type="button" role="radio" aria-checked={license === value} onClick={() => setLicense(value as "standard" | "extended")} key={String(value)} className={`flex w-full gap-3 rounded-lg border p-3 text-left ${license === value ? "border-blue-600 bg-blue-50/40" : "border-slate-200"}`}><span className={`mt-0.5 grid h-4 w-4 shrink-0 place-items-center rounded-full border ${license === value ? "border-blue-600" : "border-slate-400"}`}>{license === value && <span className="h-2 w-2 rounded-full bg-blue-600" />}</span><span className="min-w-0 flex-1"><span className="flex justify-between gap-3 text-xs font-black"><span>{label}</span><span>{value === "standard" ? "Included" : `₹${Number(price).toLocaleString("en-IN")}`}</span></span><span className="mt-1 block text-[10px] font-medium leading-4 text-slate-500">{copy}</span></span></button>)}</div><button type="button" onClick={() => onGatedPreview(`__commerce:${license}`)} className="mt-4 w-full rounded-md bg-blue-600 py-3 text-xs font-black text-white hover:bg-blue-700">{license === "standard" ? "Download with Plan" : `Buy License from ₹${extendedPrice.toLocaleString("en-IN")}`}</button><Link href="/creators/search?plan=creator" className="mt-2 block rounded-md border border-slate-300 py-2.5 text-center text-[11px] font-black hover:border-blue-600">View Plans</Link><div className="mt-4 flex justify-between border-t border-slate-100 pt-3 text-[9px] font-semibold text-slate-500"><span className="inline-flex items-center gap-1"><ShieldCheck className="h-3 w-3" />Secure transaction ready</span><span className="inline-flex items-center gap-1"><BadgeCheck className="h-3 w-3" />License certificate included</span></div></section>
    <section className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex gap-3"><Image src={avatar} alt={asset.creatorName} width={48} height={48} className="h-12 w-12 rounded-full object-cover" /><div className="min-w-0"><h2 className="flex items-center gap-1 text-sm font-black">{asset.creatorName}<BadgeCheck className="h-3.5 w-3.5 text-blue-600" /></h2><p className="mt-0.5 text-[10px] font-semibold text-slate-500">{creator?.role ?? asset.creatorRole}</p><p className="mt-1 flex items-center gap-1 text-[9px] text-slate-400"><MapPin className="h-3 w-3" />{creator?.location ?? "India"}</p></div></div><div className="mt-3 flex gap-4 text-[10px] font-bold text-slate-600"><span className="inline-flex items-center gap-1"><Star className="h-3 w-3 fill-amber-400 text-amber-400" />{creator?.rating ?? asset.rating}</span><span>{asset.salesLabel}</span><span>{creator?.followersLabel ?? "10k+"} followers</span></div><p className="mt-3 text-[10px] font-medium leading-5 text-slate-600">{creator?.bio ?? "Verified creator building premium destination assets."}</p><div className="mt-3 grid grid-cols-2 gap-2"><Link href={`/creators/authors/${asset.creatorSlug}`} className="rounded-md border border-slate-300 py-2 text-center text-[10px] font-black">View Profile</Link><button type="button" onClick={onFollow} className={`rounded-md py-2 text-[10px] font-black ${followed ? "bg-blue-50 text-blue-700" : "bg-[#071831] text-white"}`}>{followed ? "Following" : "Follow"}</button></div></section>
    <section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="text-sm font-black">Need a custom license?</h2><p className="mt-2 text-[10px] font-medium leading-5 text-slate-500">Broadcast, large-scale print, tourism campaigns, hotel chains, exclusive usage or special commercial requirements.</p><button type="button" onClick={() => onGatedPreview("Custom-license request preview ready — no message was sent")} className="mt-3 w-full rounded-md border border-blue-200 bg-blue-50 py-2.5 text-[10px] font-black text-blue-700">Contact Creator</button></section>
    <section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="text-sm font-black">Save to Collection</h2><div className="relative mt-3"><select value={collection} onChange={(event) => setCollection(event.target.value)} className="h-10 w-full appearance-none rounded-md border border-slate-300 bg-white px-3 text-[10px] font-bold"><option>Travel Inspiration</option><option>Campaign Ideas</option><option>Saved Assets</option></select><ChevronDown className="pointer-events-none absolute right-3 top-3 h-4 w-4 text-slate-400" /></div><button type="button" onClick={onSave} className={`mt-2 inline-flex w-full items-center justify-center gap-1.5 rounded-md py-2.5 text-[10px] font-black ${saved ? "bg-blue-50 text-blue-700" : "bg-slate-100 text-slate-700"}`}>{saved ? <Check className="h-3.5 w-3.5" /> : <FolderPlus className="h-3.5 w-3.5" />}{saved ? `Saved to ${collection}` : "Save selection"}</button><button type="button" onClick={() => onGatedPreview("New collection preview ready — nothing was persisted")} className="mt-2 inline-flex w-full items-center justify-center gap-1 text-[9px] font-bold text-blue-700"><Users className="h-3 w-3" />Add new collection</button></section>
  </aside>;
}
