"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import {tplApiRequest} from "@/app/lib/api/tplApiClient";
import {requestChangeSummary,validHotelBookingRequestSnapshot,type HotelBookingRequestSnapshot} from "@/app/lib/partner/partnerHotelBookingRequests";

type Form={type:"MODIFICATION"|"CANCELLATION";stayStart:string;stayEnd:string;adults:string;children:string;guestDisplayName:string;specialRequest:string;reasonCode:string;note:string};
type Props={bookingId:string;stayStart:string;stayEnd:string;adults:number;childGuests:number;guestName:string;mode?:"manage"|"status";requestType?:"MODIFICATION"|"CANCELLATION"};

export default function HotelBookingRequestPanel({bookingId,stayStart,stayEnd,adults,childGuests,guestName,mode="manage",requestType="MODIFICATION"}:Props){
 const [data,setData]=useState<HotelBookingRequestSnapshot|null>(null);
 const [initialLoading,setInitialLoading]=useState(true);
 const [action,setAction]=useState<"submit"|"withdraw"|null>(null);
 const [message,setMessage]=useState("");
 const [form,setForm]=useState<Form>({type:requestType,stayStart,stayEnd,adults:String(adults),children:String(childGuests),guestDisplayName:guestName,specialRequest:"",reasonCode:"GUEST_REQUEST",note:""});
 const loadingRef=useRef(false);
 const base=`/api/v1/bookings/${encodeURIComponent(bookingId)}/hotel-requests`;
 const load=useCallback(async(silent=false)=>{if(loadingRef.current)return;loadingRef.current=true;if(!silent)setInitialLoading(true);try{const result=await tplApiRequest<HotelBookingRequestSnapshot>(base);if(result.ok&&validHotelBookingRequestSnapshot(result.data))setData(result.data);else if(!silent)setMessage(result.ok?"Request status could not be verified.":result.error.message);}finally{loadingRef.current=false;if(!silent)setInitialLoading(false);}},[base]);
 useEffect(()=>{void load(false);const timer=setInterval(()=>void load(true),5_000);return()=>clearInterval(timer);},[load]);
 const openRequest=data?.requests.find(request=>["DRAFT","SUBMITTED","UNDER_REVIEW"].includes(request.state));
 const eligibility=form.type==="MODIFICATION"?data?.booking?.modificationEligibility:data?.booking?.cancellationEligibility;
 const visibleRequests=mode==="manage"?data?.requests.filter(request=>request.requestType===form.type):data?.requests;
 const flowName=form.type==="MODIFICATION"?"Modification":"Cancellation";
 const openRequestName=openRequest?.requestType==="MODIFICATION"?"modification":"cancellation";
 const openRequestMatchesFlow=openRequest?.requestType===form.type;
 async function create(){if(action)return;if(!eligibility?.allowed){setMessage(eligibility?.explanation??"This request is not available.");return;}if(!confirm(`Submit this ${form.type.toLowerCase()} request? Your booking remains unchanged until approval.`))return;setAction("submit");setMessage("");try{const result=await tplApiRequest(base,{method:"POST",headers:{"X-TPL-Client-Surface":"website"},body:{requestType:form.type,reasonCode:form.reasonCode,note:form.note,requestedChanges:form.type==="MODIFICATION"?{stayStart:form.stayStart,stayEnd:form.stayEnd,adults:Number(form.adults),children:Number(form.children),guestDisplayName:form.guestDisplayName,specialRequest:form.specialRequest}:{},submit:true,idempotencyKey:`customer:${bookingId}:${Date.now()}:${form.type}`}});if(!result.ok){setMessage(result.error.message);return;}await load(true);setMessage("Request submitted once. TPL is checking it and the confirmed booking is unchanged until final approval.");}finally{setAction(null);}}
 async function withdraw(id:string,version:number){if(action||!confirm("Withdraw this request before a final decision?"))return;setAction("withdraw");setMessage("");try{const result=await tplApiRequest(`${base}/${encodeURIComponent(id)}/withdraw`,{method:"POST",headers:{"X-TPL-Client-Surface":"website"},body:{version,idempotencyKey:`customer:${id}:${version}:withdraw`}});if(!result.ok){setMessage(result.error.message);return;}await load(true);setMessage("Request withdrawn once. Your confirmed booking remains unchanged.");}finally{setAction(null);}}
 const title=mode==="status"?"Request status & history":form.type==="MODIFICATION"?"Modification request":"Cancellation request";
 return <section className="overflow-hidden rounded-[18px] border border-[#cfe2dc] bg-white shadow-[0_8px_24px_rgba(15,81,63,0.06)] md:rounded-[24px]">
  <header className="border-b border-[#dce9e5] bg-[#fff7f2] px-4 py-4 md:px-5"><p className="text-[11px] font-black uppercase tracking-[.8px] text-[#d65b08]">HOTEL-M3B · Customer request</p><h2 className="mt-1 text-[18px] font-black text-[#123d36]">{title}</h2><p className="mt-1 text-[12px] leading-5 text-[#526b66]">{mode==="manage"?form.type==="MODIFICATION"?"Request an eligible booking change. TPL remains the final decision authority.":"Request full booking cancellation. TPL remains the final decision authority.":"View the latest request result and immutable history here."}</p></header>
  <div className="grid gap-4 p-4 md:p-5">
   {mode==="manage"?<div className="grid gap-2 sm:grid-cols-3"><ProcessStep number="1" title={form.type==="MODIFICATION"?"Enter requested changes":"Confirm cancellation reason"} detail={form.type==="MODIFICATION"?"Only the fields entered below are requested.":"This sends a request; it does not cancel immediately."}/><ProcessStep number="2" title="Hotel responds" detail="The Hotel confirms whether it can support the request."/><ProcessStep number="3" title="TPL decides" detail="TPL applies the final result and updates My Booking."/></div>:null}
   {initialLoading?<p className="rounded-xl bg-[#f8fbfa] p-3 text-[13px] text-[#526b66]">Loading request status…</p>:null}
   {message?<p role="status" className="rounded-xl border border-[#ead49a] bg-[#fff9e8] p-3 text-[13px] font-semibold text-[#684e19]">{message}</p>:null}
   {mode==="manage"&&!openRequest?<><div className="grid gap-3 md:grid-cols-3">{form.type==="MODIFICATION"?<><Field label="Requested check-in"><input type="date" value={form.stayStart} onChange={event=>setForm({...form,stayStart:event.target.value})}/></Field><Field label="Requested check-out"><input type="date" value={form.stayEnd} onChange={event=>setForm({...form,stayEnd:event.target.value})}/></Field><Field label="Adults"><input type="number" min="1" max="8" value={form.adults} onChange={event=>setForm({...form,adults:event.target.value})}/></Field><Field label="Children"><input type="number" min="0" max="7" value={form.children} onChange={event=>setForm({...form,children:event.target.value})}/></Field><Field label="Guest name correction"><input value={form.guestDisplayName} maxLength={120} onChange={event=>setForm({...form,guestDisplayName:event.target.value})}/></Field><Field label="Special request (not guaranteed)"><input value={form.specialRequest} maxLength={500} onChange={event=>setForm({...form,specialRequest:event.target.value})}/></Field></>:null}<Field label={form.type==="MODIFICATION"?"Reason for modification":"Reason for cancellation"}><select value={form.reasonCode} onChange={event=>setForm({...form,reasonCode:event.target.value})}>{form.type==="MODIFICATION"?<><option value="GUEST_REQUEST">Guest request</option><option value="DATE_CHANGE">Date change</option><option value="CORRECTION">Correction</option></>:<><option value="PLAN_CHANGED">Plans changed</option><option value="GUEST_REQUEST">Guest request</option></>}</select></Field><Field label="Optional note"><input value={form.note} maxLength={500} onChange={event=>setForm({...form,note:event.target.value})}/></Field></div><p className={`rounded-xl p-3 text-[12px] font-semibold ${eligibility?.allowed?"bg-[#eaf7f2] text-[#17604f]":"bg-[#fff3ed] text-[#914a25]"}`}>{eligibility?.explanation??"Checking server eligibility…"}</p><button disabled={action!==null||!eligibility?.allowed} onClick={()=>void create()} className="min-h-11 justify-self-start rounded-xl border border-[#e55f00] bg-[#ff6b00] px-5 font-extrabold text-white disabled:opacity-50">{action==="submit"?`Submitting ${flowName.toLowerCase()} request…`:`Submit ${flowName.toLowerCase()} request` }</button></>:null}
   {mode==="manage"&&openRequest?<p className="rounded-xl border border-[#ead49a] bg-[#fff9e8] p-3 text-[13px] font-semibold leading-5 text-[#684e19]">{openRequestMatchesFlow?`A ${openRequestName} request ${openRequest.requestRef} is already open (${openRequest.customerStatus}). Follow it below; another request cannot be submitted until TPL decides it or you withdraw it.`:`A ${openRequestName} request ${openRequest.requestRef} is already open (${openRequest.customerStatus}). To prevent conflicting changes, a ${flowName.toLowerCase()} request cannot be submitted until TPL decides it or you withdraw it. View the open request from ${openRequestName==="modification"?"Manage Booking":"Cancel Booking"}.`}</p>:null}
   {visibleRequests?.map(request=><article key={request.id} className="rounded-2xl border border-[#dce8e4] p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><strong className="text-[14px] text-[#123d36]">{request.requestRef}</strong><p className="text-[11px] text-[#637873]">{request.requestType} · {request.requestKind.replaceAll("_"," ")}</p></div><span className="rounded-full border border-[#d6b765] bg-[#fff9e8] px-3 py-1 text-[10px] font-black text-[#765716]">{request.customerStatus}</span></div><div className="mt-3 grid gap-2 md:grid-cols-2"><div className="rounded-xl bg-[#f8fbfa] p-3"><b className="text-[11px] text-[#123d36]">Before</b>{requestChangeSummary(request.before).slice(0,6).map(value=><p key={value} className="mt-1 text-[11px] text-[#637873]">{value}</p>)}</div><div className="rounded-xl bg-[#f8fbfa] p-3"><b className="text-[11px] text-[#123d36]">Requested</b>{requestChangeSummary(request.requestedChanges).map(value=><p key={value} className="mt-1 text-[11px] text-[#637873]">{value}</p>)}</div></div><p className="mt-3 text-[11px] font-semibold text-[#765716]">{request.customerStatus} · {request.financialImpactState.replaceAll("_"," ")} · no financial execution</p>{mode==="manage"&&request.canWithdraw?<button disabled={action!==null} onClick={()=>void withdraw(request.id,request.version)} className="mt-3 rounded-lg border border-[#e55f00] px-4 py-2 text-[12px] font-bold text-[#d65b08]">{action==="withdraw"?"Withdrawing once…":"Withdraw request"}</button>:null}</article>)}
   {!initialLoading&&!openRequest&&!visibleRequests?.length?<p className="rounded-xl bg-[#f8fbfa] p-3 text-[13px] text-[#526b66]">No {flowName.toLowerCase()} request has been submitted for this booking.</p>:null}
  </div>
 </section>;
}
function ProcessStep({number,title,detail}:{number:string;title:string;detail:string}){return <div className="rounded-2xl border border-[#ead8ca] bg-[#fffaf6] p-3"><span className="inline-grid h-7 w-7 place-items-center rounded-full bg-[#ff6b00] text-[12px] font-black text-white">{number}</span><p className="mt-2 text-[13px] font-black text-[#123d36]">{title}</p><p className="mt-1 text-[11px] leading-5 text-[#526b66]">{detail}</p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1.5 text-[12px] font-bold text-[#31564d]">{label}<span className="[&>input]:h-11 [&>input]:w-full [&>input]:rounded-lg [&>input]:border [&>input]:border-[#b9cbc6] [&>input]:px-3 [&>select]:h-11 [&>select]:w-full [&>select]:rounded-lg [&>select]:border [&>select]:border-[#b9cbc6] [&>select]:bg-white [&>select]:px-3">{children}</span></label>}
