"use client";

import Image from "next/image";
import { Search, Sparkles } from "lucide-react";
import { useState } from "react";
import type { CreatorCategoryPageConfig } from "@/app/lib/creators/creatorCategoryPageConfig";

export default function CreatorCategoryHero({ config, query, onSearch, onTag }: { config: CreatorCategoryPageConfig; query: string; onSearch: (query: string) => void; onTag: (tag: string) => void }) {
  const [value, setValue] = useState(query);
  return <section className="relative isolate overflow-hidden bg-[#071831] text-white"><Image src={config.heroImage} alt={`${config.title} marketplace`} fill priority sizes="100vw" className="object-cover opacity-65" /><div className={`absolute inset-0 bg-gradient-to-r ${config.accent} via-[#071831]/85 to-[#071831]/15`} /><div className="relative mx-auto max-w-[1440px] px-4 py-10 sm:px-6 lg:px-10 lg:py-12"><span className="inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-white/10 px-3 py-1 text-[9px] font-black uppercase tracking-[0.16em]"><Sparkles className="h-3 w-3 text-blue-200" />TPL Creator Category</span><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{config.title}</h1><p className="mt-2 max-w-2xl text-sm font-medium leading-6 text-slate-200">{config.description}</p><form onSubmit={(event) => { event.preventDefault(); if (value.trim()) onSearch(value.trim()); }} className="mt-5 flex max-w-2xl overflow-hidden rounded-lg bg-white p-1 shadow-2xl"><Search className="ml-3 mt-3 h-4 w-4 shrink-0 text-slate-400" /><input suppressHydrationWarning value={value} onChange={(event) => setValue(event.target.value)} placeholder={config.searchPlaceholder} className="h-10 min-w-0 flex-1 px-3 text-sm font-semibold text-slate-900 outline-none" /><button type="submit" className="rounded-md bg-blue-600 px-5 text-[10px] font-black text-white">Search</button></form><div className="mt-3 flex gap-2 overflow-x-auto"><span className="shrink-0 py-1 text-[9px] font-bold text-slate-300">Popular:</span>{config.popularTags.map((tag) => <button type="button" key={tag} onClick={() => onTag(tag)} className="shrink-0 rounded-full border border-white/20 bg-white/10 px-2.5 py-1 text-[9px] font-bold hover:bg-white/20">{tag}</button>)}</div><div className="mt-7 grid max-w-3xl grid-cols-2 gap-3 sm:grid-cols-4">{config.stats.map((stat) => <div key={stat.label} className="rounded-lg border border-white/15 bg-[#071831]/45 px-4 py-3 backdrop-blur"><strong className="block text-lg font-black">{stat.value}</strong><span className="text-[9px] font-semibold text-slate-300">{stat.label}</span></div>)}</div></div></section>;
}
