import type { CabResultItem } from "./cabResultTypes";

export const CAB_RESULT_DATA: CabResultItem[] = [
  {
    id: "cab-1",
    rideType: "outstationOneWay",
    name: "WagonR",
    image: "/cab/wagonr.png",
    vehicleType: "hatchback",
    brand: "Maruti",
    rating: 4.3,
    reviewCount: 128,
    basePrice: 2400,
    finalPrice: 2074,
    discountPercent: 14,
    fuelType: "cng",
    transmission: "manual",
    seats: 4,
    luggage: 2,
    kmsIncluded: 148,
    extraKmFare: 12,
    pickupIncluded: true,
    freeCancellation: true,
    instantConfirm: true,
    tags: ["Trusted Driver", "Clean Cab"],
  },
  {
    id: "cab-2",
    rideType: "outstationOneWay",
    name: "Dzire",
    image: "/cab/dzire.png",
    vehicleType: "sedan",
    brand: "Maruti",
    rating: 4.2,
    reviewCount: 96,
    basePrice: 2449,
    finalPrice: 2149,
    discountPercent: 14,
    fuelType: "cng",
    transmission: "manual",
    seats: 4,
    luggage: 3,
    kmsIncluded: 148,
    extraKmFare: 13,
    pickupIncluded: true,
    freeCancellation: true,
    instantConfirm: true,
    tags: ["On-Time Pickup"],
  },
  {
    id: "cab-3",
    rideType: "outstationRoundTrip",
    name: "Ertiga",
    image: "/cab/ertiga.png",
    vehicleType: "suv",
    brand: "Maruti",
    rating: 4.5,
    reviewCount: 155,
    basePrice: 5200,
    finalPrice: 4680,
    discountPercent: 10,
    fuelType: "diesel",
    transmission: "manual",
    seats: 6,
    luggage: 4,
    kmsIncluded: 300,
    extraKmFare: 15,
    pickupIncluded: true,
    freeCancellation: true,
    instantConfirm: true,
  },
  {
    id: "cab-4",
    rideType: "airportTransfers",
    name: "Aura",
    image: "/cab/aura.png",
    vehicleType: "sedan",
    brand: "Hyundai",
    rating: 4.4,
    reviewCount: 88,
    basePrice: 1499,
    finalPrice: 1320,
    discountPercent: 12,
    fuelType: "petrol",
    transmission: "manual",
    seats: 4,
    luggage: 3,
    pickupIncluded: true,
    instantConfirm: true,
  },
  {
    id: "cab-5",
    rideType: "hourlyRentals",
    name: "Innova Crysta",
    image: "/cab/innova.png",
    vehicleType: "suv",
    brand: "Toyota",
    rating: 4.7,
    reviewCount: 201,
    basePrice: 3200,
    finalPrice: 2890,
    discountPercent: 9,
    fuelType: "diesel",
    transmission: "manual",
    seats: 6,
    luggage: 4,
    packageLabel: "8 hrs 80 kms",
    extraKmFare: 18,
    pickupIncluded: true,
    freeCancellation: true,
  },
  {
    id: "car-1",
    rideType: "carRental",
    name: "Baleno",
    image: "/cab/baleno.png",
    vehicleType: "hatchback",
    brand: "Maruti",
    rating: 4.3,
    reviewCount: 72,
    basePrice: 2200,
    finalPrice: 1999,
    discountPercent: 9,
    fuelType: "petrol",
    transmission: "automatic",
    seats: 5,
    luggage: 2,
    freeCancellation: true,
    instantConfirm: true,
  },
  {
    id: "car-2",
    rideType: "carRental",
    name: "Creta",
    image: "/cab/creta.png",
    vehicleType: "suv",
    brand: "Hyundai",
    rating: 4.6,
    reviewCount: 112,
    basePrice: 4200,
    finalPrice: 3890,
    discountPercent: 7,
    fuelType: "diesel",
    transmission: "automatic",
    seats: 5,
    luggage: 3,
    freeCancellation: true,
    instantConfirm: true,
  },
  {
    id: "bike-1",
    rideType: "bikeRental",
    name: "Activa 6G",
    image: "/cab/activa.png",
    vehicleType: "scooter",
    brand: "Honda",
    rating: 4.4,
    reviewCount: 65,
    basePrice: 699,
    finalPrice: 599,
    discountPercent: 14,
    fuelType: "petrol",
    engineCc: 110,
    helmetIncluded: true,
    instantConfirm: true,
  },
  {
    id: "bike-2",
    rideType: "bikeRental",
    name: "Royal Enfield Classic",
    image: "/cab/classic350.png",
    vehicleType: "bike",
    brand: "Royal Enfield",
    rating: 4.7,
    reviewCount: 91,
    basePrice: 1599,
    finalPrice: 1449,
    discountPercent: 9,
    fuelType: "petrol",
    engineCc: 350,
    helmetIncluded: true,
    instantConfirm: true,
  },
];