import { Filter, X } from "lucide-react";
import { assetStatusLabels, assetStatusTabs, assetTypeLabels, licenseLabels } from "@/app/lib/creators/creatorAssetManagerData";

export default function CreatorAssetFilters({ params, open, onClose, onUpdate, onClear }: { params: URLSearchParams; open: boolean; onClose: () => void; onUpdate: (patch: Record<string, string | null>) => void; onClear: () => void }) {
  const panel = <div className="space-y-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Filter className="h-4 w-4 text-blue-700" /><h2 className="text-lg">Filters</h2></div><button type="button" onClick={onClear} className="text-xs font-bold text-blue-700">Clear All</button><button type="button" onClick={onClose} aria-label="Close filters" className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 xl:hidden"><X className="h-4 w-4" /></button></div><Select label="Asset Type" value={params.get("type") ?? ""} onChange={(value) => onUpdate({ type: value || null })} options={Object.entries(assetTypeLabels)} /><Select label="Status" value={params.get("filterStatus") ?? ""} onChange={(value) => onUpdate({ filterStatus: value || null })} options={assetStatusTabs.filter((item) => item !== "all").map((item) => [item, assetStatusLabels[item]])} /><Select label="License Type" value={params.get("license") ?? ""} onChange={(value) => onUpdate({ license: value || null })} options={Object.entries(licenseLabels)} /><Select label="Collection" value={params.get("collection") ?? ""} onChange={(value) => onUpdate({ collection: value || null })} options={[["cinematic-india", "Cinematic India"], ["creator-launch-kits", "Creator Launch Kits"], ["himalayan-aerials", "Himalayan Aerials"], ["editorial-city-stories", "Editorial City Stories"], ["route-packs", "Route Packs"]]} /><Select label="Upload Date" value={params.get("date") ?? ""} onChange={(value) => onUpdate({ date: value || null })} options={[["7d", "Last 7 days"], ["30d", "Last 30 days"], ["older", "Older"]]} /><Select label="Orientation" value={params.get("orientation") ?? ""} onChange={(value) => onUpdate({ orientation: value || null })} options={[["Landscape", "Landscape"], ["Portrait", "Portrait"], ["Mixed", "Mixed"]]} /><Select label="Resolution" value={params.get("resolution") ?? ""} onChange={(value) => onUpdate({ resolution: value || null })} options={[["4K", "4K"], ["1080p", "1080p"], ["24 MP", "24 MP"], ["Print ready", "Print ready"]]} /><label className="block text-sm font-semibold text-slate-800">Destination<input value={params.get("destination") ?? ""} onChange={(event) => onUpdate({ destination: event.target.value || null })} placeholder="Search location" className="mt-1.5 h-10 w-full rounded-lg border border-slate-300 px-3 text-sm outline-none focus:border-blue-500" /></label><label className="flex items-start gap-3 rounded-xl bg-slate-50 p-3 text-sm font-semibold text-slate-800"><input type="checkbox" checked={params.get("plan") === "included"} onChange={(event) => onUpdate({ plan: event.target.checked ? "included" : null })} className="mt-0.5 h-5 w-5" />Creator Plan Included</label><button type="button" onClick={onClear} className="min-h-10 w-full rounded-lg border border-slate-300 bg-white px-4 font-bold text-slate-800">Reset Filters</button></div>;
  return <><aside className="hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:block">{panel}</aside>{open && <div className="fixed inset-0 z-50 xl:hidden"><button type="button" onClick={onClose} aria-label="Close filter backdrop" className="absolute inset-0 bg-slate-950/60" /><aside className="absolute inset-y-0 right-0 w-[min(90vw,360px)] overflow-y-auto bg-white p-5 shadow-2xl">{panel}</aside></div>}</>;
}

function Select({ label, value, options, onChange }: { label: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <label className="block text-sm font-semibold text-slate-800">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm outline-none focus:border-blue-500"><option value="">All</option>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
